<div class="pheader clearfix"><?php echo isset($aBadword['iAutoID'])?'编辑':'增加'?>敏感词</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iAutoID" type="hidden" value="<?php echo isset($aBadword['iAutoID'])?$aBadword['iAutoID']:''?>">
		<div class="form-group">
			<label for="sWord" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 敏感词：</label>
			<div class="col-sm-10">
				<input name="sWord" type="text" validate="!length:1-50" value="<?php echo isset($aBadword['sWord'])?$aBadword['sWord']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<?php if(isset($aBadword['iAutoID'])){ ?>
    	<?php if(isset($aBadword['iUpdateTime']) && $aBadword['iUpdateTime'] > 0){ ?>
    	<div class="form-group">
    		<label for="iMoney" class="col-sm-2 control-label"> 更新时间：</label>
    		<div class="col-sm-10">
    			<?php echo date('Y-m-d H:i:s' , $aBadword['iUpdateTime']); ?>
    		</div>
    	</div>
    	<?php } ?>
    	<div class="form-group">
    		<label for="iMoney" class="col-sm-2 control-label"> 创建时间：</label>
    		<div class="col-sm-10">
    			<?php echo date('Y-m-d H:i:s' , $aBadword['iCreateTime']); ?>
    		</div>
    	</div>
    	<?php } ?>
    	<div class="btn-toolbar text-center">
        	<button id="save" class="btn btn-primary">保存</button>
        	<button id="cancel"class="btn" onclick="location.href='/admin/badword/list/';return false;">取消</button>
        </div>
	</form>
</div>
<script type="text/javascript">
$(function() {
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            location.href = '/admin/badword/list/';
	        }
	    }, 'json');
		return false;
	}});
});
</script>