<div class="pheader clearfix">发送账号</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <div class="form-group col-sm-12">
            <label for="title" class="col-sm-3 control-label"> <span class="tubiao">*</span>标题：</label>
            <div class="col-sm-9">
                <input name="title" type="text" value="<?php echo $aMail['title']?>" class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group col-sm-12">
            <label for="sendto" class="col-sm-3 control-label"> <span class="tubiao">*</span>收件人：</label>
            <div class="col-sm-9">
                <input name="sendto"  type="text" value="<?php echo $aMail['sendto']?>" class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div> 

        <div class="form-group col-sm-12">
            <label for="content" class="col-sm-3 control-label"> <span class="tubiao">*</span>邮件正文：</label>
            <div class="col-sm-9">
                <textarea style="margin-top: 0px; margin-bottom: 0px; height: 222px;" name="content" class="form-control input-validate"><?php echo $aMail['content']?></textarea>
            </div>
        </div>

        <div class="btn-toolbar text-center col-sm-12">
            <button id="save" class="btn btn-primary">发送</button>
            <a class="text-right btn btn-default" href="/company/employee/list">返回</a>
        </div>      
    </form>
</div>

<script type="text/javascript">
$(function() {
    $("#myform").validate({submitHandler: function(form) {
        $.post(form.action, $(form).serialize(), function(ret){
            alert(ret.data);
            if (ret.status) {
               location.href = '/company/mail/setmail?employeeId=<?php echo $aMail['employeeId']?>';             
            }
        }, 'json');
        return false;
    }});
});
</script>