<div class="dialog">
	<div class="panel panel-default">
		<p class="panel-heading no-collapse text-center">修改密码</p>
		<div class="panel-body">
			<form class="form-horizontal" role="form">
				<div class="form-group">
				    <label class="col-sm-3 control-label">旧密码：</label>
					<div class="col-sm-8">
					    <input id="oldpass" validate="!length:6-20" type="password" class="form-control input-validate">
						<span class="validate_checktip"></span>
					</div>
				</div>
				<div class="form-group">
				    <label class="col-sm-3 control-label">新密码：</label>
					<div class="col-sm-8">
					    <input id="newpass" validate="!length:6-20" type="password" class="form-control input-validate">
						<span class="validate_checktip"></span>
					</div>
				</div>
				<div class="form-group col-sm-8">
				    <a href="javascript:;" id="confirm" class="btn btn-primary pull-right">确认</a>
				</div>
				<div class="clearfix"></div>
			</form>
		</div>
	</div>
</div>
<script>
$('#confirm').click(function(){
	if ($('#oldpass').val().trim().length < 3) {
		alert('请输入旧密码！');
		$('#oldpass').focus();
		return false;
	}
	if ($('#newpass').val().trim().length < 3) {
		alert('请输入新密码！');
		$('#newpass').focus();
		return false;
	}
	$.post('/admin/user/chgpwd', {'oldpass':$('#oldpass').val().trim(), 'newpass':$('#newpass').val().trim()}, function(ret){
	    alert(ret.data);
	    $('#oldpass').focus();
	}, 'json');
})
</script>