<!doctype html>
<html lang="zh-cn"><head>
        <meta charset="utf-8">
        <title><?php echo isset($aMeta['title']) ? $aMeta['title'] : '' ?></title>
        <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
        <meta name="keywords" content="<?php echo isset($aMeta['keywords']) ? $aMeta['keywords'] : '' ?>">
        <meta name="description" content="<?php echo isset($aMeta['description']) ? $aMeta['description'] : '' ?>">
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="<?php echo $sStaticRoot ?>/font-awesome/css/font-awesome.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/backend/css/common.css">
    <?php if (!empty($sProjectName)) {//每个项目一个自己的css文件 ?>
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/backend/css/<?php echo $sProjectName; ?>common.css">
    <?php } ?>
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/jquery-1.11.1.min.js"></script>
        <script src="<?php echo $sStaticRoot ?>/backend/plugin/chosen/chosen.jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/backend/plugin/chosen/chosen.min.css">
        <!--[if lt IE 9]>
                <script src="<?php echo $sStaticRoot ?>/js/html5shiv.js"></script>
        <![endif]-->
        <script type="text/javascript">
            var global = {
                static_url: '<?php echo $sStaticRoot?>'
            };
        </script>
    </head>
    <body>
        <?php if (!empty($aCurrUser)) { ?>
            <div class="navbar" role="navigation">
                <div class="navbar-header">
                    <!-- <a href="/"><span class="navbar-brand"><img style="height:20px;margin-top:5px;" src="<?php echo $sStaticRoot ?>/backend/img/logo.png"></span></a> -->
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown hidden-xs">
                            <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-sitemap"></i> <?php echo $__aCityList__[$iCurrCityID] ?>
                                <i class="fa fa-caret-down"></i>
                            </a> -->
                            <!-- <ul class="dropdown-menu city-menu">
                                <?php foreach ($__aCurrUserCityList__ as $k => $v) {
 ?>
                                        <li><a href="/admin/index/change/id/<?php echo $k ?>"><?php echo $v ?></a></li>
        <?php
    } ?>
                            </ul> -->
                        </li>
                        <li class="dropdown hidden-xs">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="fa fa-user"></span> <?php echo $aCurrUser['sRealName'] ? $aCurrUser['sRealName'] : $aCurrUser['sUserName'] ?>
                                <i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu user-menu">
                                <?php if ($aCurrUser['iType'] == 1) { ?>
                                <li><a href="/admin/user/chgpwd">修改密码</a></li>                                
                                <?php } ?>
                                <?php 
                                    if ($aCurrUser['iType'] == 1) {
                                        $type = 1;
                                    }
                                    if ($aCurrUser['iType'] == 2) {
                                        $type = 2;
                                    }
                                    if ($aCurrUser['iType'] == 4) {
                                        $type = 4;   
                                    }
                                ?>
                                <li><a href="/admin/logout/admintype/<?php echo $type ?>">登出</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="sidebar-nav">
                <ul>
                    <?php foreach ($__aMenuTree__ as $v) { ?>
                        <li><a href="javascript:void(0)" data-target="#navmenu<?php echo $v['iMenuID'] ?>" class="nav-header <?php echo $v['iCurr'] ? '' : 'collapsed' ?>" data-toggle="collapse" >
                                <i class="<?php echo $v['sIcon'] ?>"></i> <?php echo $v['sMenuName'] ?><i class="fa fa-collapse"></i></a>
                        </li>
                                <?php if (!empty($v['aChild'])) { ?>
                            <li>
                                <ul id="navmenu<?php echo $v['iMenuID'] ?>" class="nav nav-list collapse <?php echo $v['iCurr'] ? 'in' : '' ?>">
                            <?php foreach ($v['aChild'] as $c) { ?>

                                    <?php if (!empty($c['aChild'])) { ?>
                                            <li>
                                               <a href="javascript:void(0)" data-target="#navmenu_child<?php echo $c['iMenuID'] ?>" class="nav-header nav_child <?php echo $c['iCurr'] ? '' : 'collapsed' ?>" data-toggle="collapse" >
                                                <i class="<?php echo $c['sIcon'] ?>"></i> <?php echo $c['sMenuName'] ?><i class="fa fa-collapse"></i></a>
                                            </li>
                                            <li>
                                                <ul id="navmenu_child<?php echo $c['iMenuID'] ?>" class="nav nav-list nav-list_child collapse <?php echo $c['iCurr'] ? 'in' : '' ?>" >
                                                    <?php foreach ($c['aChild'] as $leaf) { ?>
                                                     <li <?php echo $leaf['iCurr'] ? 'class="active"' : '' ?>><a class="leafchild" href="<?php echo $leaf['sUrl'] ?>"><span class="fa fa-caret-right"></span>  <?php echo $leaf['sMenuName'] ?></a></li>
                                                    <?php } ?>
                                                </ul>
                                            </li>

                                     <?php }else{ ?>

                                        <li <?php echo $c['iCurr'] ? 'class="active"' : '' ?>><a href="<?php echo $c['sUrl'] ?>"><span class="fa fa-caret-right"></span> <?php echo $c['sMenuName'] ?></a></li>
                                       <?php } ?>
                              <?php } ?>
                                </ul>
                            </li>
                <?php }
            } ?>

                </ul>
            </div>
            <div class="content" style="padding:0px"><?php include $_script; ?></div>
<?php } else { ?>
    <?php include $_script; ?>
<?php } ?>
        <div class="actGotop" id="backtop" style="display: block;">
            <a href="javascript:;" title="返回顶部"></a>
        </div>
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/alert.js"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/validate.js"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/phpjs.min.js"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/backend/js/common.js"></script>
        <script type="text/javascript"><?php echo @$__showDebugInfo__ ?></script>
    </body>
</html>