
<!doctype html>

<html>
<head>

<title>安心体检用户中心</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="MobileOptimized" content="width">
<meta name="HandheldFriendly" content="true">
<meta name="viewport" content="width=device-width"  /><!-- media setting -->
<meta http-equiv="cleartype" content="on"><!-- MS important -->
<meta name="apple-mobile-web-app-capable" content="yes"><!-- hide ios topbar -->      
<meta content="telephone=no" name="format-detection" /><!-- stop call phone -->

<!-- Facicon 57*57 / Retina 114*114 / ipad 72*72 / Ios desktop -->    
<link rel="apple-touch-icon-precomposed" href="iphone_icon_57.png" sizes="57x57"/>
<link rel="apple-touch-icon-precomposed" href="iphone_icon_114.png" sizes="114x114"/>
<link rel="apple-touch-icon-precomposed" href="iphone_icon_72.png" sizes="72x72"/>    		
<link rel="apple-touch-startup-image" href="iphone_icon_57.png" />

<script src="<?php echo $sStaticRoot ?>/backend/js/phoneAgent.js"></script>


<script src="<?php echo $sStaticRoot ?>/backend/js/jquery.easing.1.3.js"></script>	
<script src='<?php echo $sStaticRoot ?>/backend/js/idangerous.swiper-2.1.min.js'></script>
<script src="<?php echo $sStaticRoot ?>/backend/js/function.js"></script>
<script src="<?php echo $sStaticRoot ?>/backend/js/jquery-2.1.1.min.js"></script>
<link rel="stylesheet" href="<?php echo $sStaticRoot ?>/backend/css/ciic.css" type="text/css" media="all">
</head>

<body>
<div id="main">
     <div id="header">
        <div id="logo" class="fl">安心体检</div>
        <div class="tl_nb"><img src="<?php echo $sStaticRoot ?>/backend/img/tp_number.png" /></div>
        <div id="switch"><a href='/tj'/><button type="button">切换个人用户登录</button></a></div>
     </div>
     
     <div id="sign">
         <div class="br_ic_5_6"><img src="<?php echo $sStaticRoot ?>/backend/img/banner_icon_5_6.png" /></div>
         <div class="swiper_fr">
         <div class="br_ic_5">
              <div class="br_ic_5_1"><img src="<?php echo $sStaticRoot ?>/backend/img/banner_icon_5_1.png" /></div>
              <div class="br_ic_5_2 mt_10"><img src="<?php echo $sStaticRoot ?>/backend/img/banner_icon_5_2.png" /></div>
              <div class="br_ic_5_3 mt_10"><img src="<?php echo $sStaticRoot ?>/backend/img/banner_icon_5_3.png" /></div>
              <div class="br_ic_5_4"><img src="<?php echo $sStaticRoot ?>/backend/img/banner_icon_5_4.png" /></div>
              <div class="br_ic_5_5"><img src="<?php echo $sStaticRoot ?>/backend/img/banner_icon_5_5.png" /></div>
              <div class="br_ic_5_7"><img src="<?php echo $sStaticRoot ?>/backend/img/banner_icon_5_7.png" /></div>
              <div class="br_ic_5_8 mt_10"><img src="<?php echo $sStaticRoot ?>/backend/img/banner_icon_5_8.png" /></div>
           <!--   <div class="br_ic_5_9 mt_10"><img src="images/banner_icon_5_3.png" /></div>
              <div class="br_ic_5_10"><img src="images/banner_icon_5_4.png" /></div>
              <div class="br_ic_5_11"><img src="images/banner_icon_5_5.png" /></div> -->
         </div>
           <div class="sign_fr">
           <div id="sign_fr_shadow"></div>
           <div class="sign_fr_box">
           <h5>管理用户登录</h5>
           <form class="form-horizontal" method="post" action="/admin/signin" role="form" id="myform">
               <input id="username" name="username" type="text" class="form-control" placeholder="帐号">
               <input id="password" name="password" type="password" class="form-control" placeholder="密码"/>
               <input type="hidden" value="<?php echo !empty($iType) ? $iType : 1 ?>" name="type">
               <button id="signin" type="button">登录</button>
               <button type="button" id="forget"></button>
          </form>
           </div>
           </div>
         </div>
     </div>
     
     <div id="footer">
         <img src="<?php echo $sStaticRoot ?>/backend/img/ciic_logo.png" />
         <p>上海中盈保险经纪有限公司</p>
         <p>沪ICP备11037892号 Copyright©2012- 2015 中盈保险网版权所有</p>
     </div>
</div>
</body>

<script>
    $('#signin').click(function () {
        if ($('#username').val().trim().length < 3) {
            alert('请输入用户名！');
            $('#username').focus();
            return false;
        }
        if ($('#password').val().trim().length < 3) {
            alert('请输入用户密码！');
            $('#password').focus();
            return false;
        }
        var form = $("#myform");
        $.post(form.attr('action'), form.serialize(), function (ret) {
            if (ret.status) {
                location.href = ret.data.sUrl;
            } else {
                alert(ret.data);
            }
        }, 'json');
        return false;
    });
</script>
</html>
