<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title> 安心服务 www.51joying.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" /><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/backend/css/Window.HrShop.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/backend/css/Window.HrShopAlert.css" />
        <link rel="stylesheet" href="<?php echo $sStaticRoot ?>/backend/css/HrShop.css" type="text/css" />
        <link rel="stylesheet" href="<?php echo $sStaticRoot ?>/backend/css/panel.css" type="text/css" />
        <script src="<?php echo $sStaticRoot ?>/js/jquery-1.9.1.min.js" type="text/javascript"></script>
        <script src="<?php echo $sStaticRoot ?>/js/common.js" type="text/javascript"></script>
        <script src="<?php echo $sStaticRoot ?>/js/panel.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/public.js"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/product-tab.js"></script>
        <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=lmOVF1bhmFfjilcLnHpWFlMR"></script>
        <script type="text/javascript" src="http://webapi.amap.com/maps?v=1.3&key=4bfffe2dca93bbf875de0181774419c4&plugin=AMap.Autocomplete,AMap.PlaceSearch"></script>
        <!-- <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/bootstrap/css/bootstrap.css"> -->
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/bootstrap/js/bootstrap.min.js"></script>
        <!-- <link rel="stylesheet" href="<?php echo $sStaticRoot ?>/font-awesome/css/font-awesome.css"> -->
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/validate.js"></script>
        <script type="text/javascript">
            var timeout = 500;
            var closetimer = 0;
            var ddmenuitem = 0;
            function jsddm_timer() {
                closetimer = window.setTimeout(jsddm_close, timeout);
            }
            function jsddm_canceltimer() {
                if (closetimer) {
                    window.clearTimeout(closetimer);
                    closetimer = null;
                }
            }
            function jsddm_open() {
                $("#divusercenter").addClass("hd_login_hover");
                $("#usercenter").css("display", "block");
            }
            function jsddm_close() {
                $("#divusercenter").removeClass("hd_login_hover");
                $("#usercenter").css("display", "none");
            }

            function producttype_open() {
                $("#allCategoryHeader").css("display", "block");
            }
            function producttype_close() {
                $("#allCategoryHeader").css("display", "none");
            }
            function ul_addborder(obj) {
                obj.css.addClass("bd_ccc");
            }
            $(document).ready(function () {
                $('#jsddm').bind('mouseover', jsddm_open);
                $('#jsddm').bind('mouseout', jsddm_close);
                $("#divusercenter").bind('mouseover', jsddm_open);
                $('#divusercenter ').bind('mouseout', jsddm_close);
                $("#allSortOuterbox").bind('mouseover', producttype_open);
                $('#allSortOuterbox ').bind('mouseout', producttype_close);
            });
            function addFav() {
                var url = window.location;
                var title = document.title + "-" + $("span[id*='lblProductName']").text();
                var ua = navigator.userAgent.toLowerCase();
                if (ua.indexOf("360se") > -1) {
                    alert("由于360浏览器功能限制，请按 Ctrl+D 手动收藏！");
                }
                else if (ua.indexOf("msie 8") > -1) {
                    window.external.AddToFavoritesBar(url, title); //IE8
                }
                else if (document.all) {
                    try {
                        window.external.addFavorite(url, title);
                    } catch (e) {
                        alert('您的浏览器不支持,请按 Ctrl+D 手动收藏!');
                    }
                }
                else if (window.sidebar) {
                    window.sidebar.addPanel(title, url, "");
                }
                else {
                    alert('您的浏览器不支持,请按 Ctrl+D 手动收藏!');
                }
            }
            function ShowMessage(str)
            {
                alert(str);
            }
        </script>
        <link href="<?php echo $sStaticRoot ?>/backend/css/WebResource.axd.css" type="text/css" rel="stylesheet" class="Telerik_stylesheet" />
        </head>
        <body>
            <div id="homePage_head">
                <div class="hd_global_top_bar"  id="global_top_bar">
                    <div class="wrap clearfix">
                        <?php if (!empty($aUser['iUserID'])) { ?>
                        <div class="hd_topbar_left clearfix" style="padding-left:110px;" >
                            <span style="float: left;">
                                <span id="lblUserName"><b><?php echo $aUser['sRealName'] ?></b>，您好！</span></span>
                            <div id="global_unlogin" class="hd_unlogin_wrap">
                                <div class="hd_login_wrap" id="divusercenter">
                                    <a id="jsddm" href="/index/record/list/" class="hd_user_center fl" >个人中心</a>
                                </div>
                            </div>
                            <a id="linkOut" class="logout blue_link none" href="/index/account/logout">退出</a>
                        </div>
                        <?php } else { ?>
                        <div class="wrap clearfix">
                            <div class="hd_topbar_left clearfix" style="padding-left:110px">
                                <span style="float: left;">
                                    <span id="lblUserName"></span></span>
                            </div>
                            <div class="hd_top_manu clearfix">
                                <ul id="SingleUser" class="clearfix">
                                    <li class="hd_menu_tit">
                                        <a href="/index/account/cdlogin">个人登录</a>/
                                        <a href="/index/account/register">注册</a>
                                    </li>
                                </ul>
                                <ul class="clearfix">
                                    <li class="hd_menu_tit hd_my_favorite" id="glShouCang"><a target="_blank" href="#" onclick="addFav();" rel="sidebar"><i></i>加入收藏夹</a> </li>
                                </ul>
                            </div>
                        </div>
                        <?php } ?>
                    </div>
                </div>
                <div id="topbanner" class="wrap">
                    <div class="banner_img">
                    </div>
                </div>
                <div class="wrap clearfix" id="site_header">
                    <div id="logo_areaID" class="hd_logo_area fl clearfix" style="padding-left: 110px;">
                        <a href="" class="fl">
                            <img id="imgLogo" src="<?php echo $sStaticRoot ?>/backend/img/ciiclogo.png" /></a>
                    </div>
                    <div style="float:right; padding-right:130px; color:orangered; font-size:18px; font-weight:bold; padding-top:20px ">
                        咨询电话：400-816-6768 &nbsp;&nbsp;&nbsp;&nbsp
                    </div>
                    <div class="hd_head_search" >
                    </div>
                </div>
                <div id="headerNav" class="hd_header_nav headerNav_channel ">
                    <div class="hd_fixed_bg">
                    </div>
                    <div class="wrap2" style="z-index: 1000;">
                        <div id="allSortOuterbox">
                            <h2 class="hd_all_sort_link fl">
                                <a href="#" class="fl" style="background-image: none; width: 90px;"></a>
                            </h2>

                        </div>
                        <div class="headerNavWrap" id="global_menu" style="width: 800px;">
                            <ul id="wideScreenTabShowID" class="headerNavMain clearfix">
                                <li><a href="/">首页</a></li>
                                <li><a href="/index/web/list">安心体检</a></li>
                                <li><a href="/index/cooper">合作伙伴</a></li>
                                <li><a href="/index/about">关于我们</a></li>
                            </ul>
                        </div>
                        <div id="divShop" style="padding-top: 10px; padding-left: 30px; float: left; "><img src="<?php echo $sStaticRoot ?>/backend/img/shop.png" alt="" width="20px" height="20px;" />&nbsp;
                            <a href="/index/web/cartlist" style="font-size: 15px; font-weight: bold; color: #FFFFFF;">购物车</a>
                            <span style="font-size: 15px; font-weight: bold; color: #FFFFFF;">(<?php echo $aChart ? count($aChart) : 0 ?>)</span>
                        </div>
                    </div>
                </div>
            </div>
            <div id="wrap">
                <?php include $_script; ?>
            </div>
            <div class="page_fixed">
                <a class="fixed_gotop" id="fixed_gotop" href="#">回到顶部</a>
            </div>
            <div class="base_pop" id="divMap" style="width: 800px; height: 550px; display: none; z-index: 888;">
                <div class="pop_hd">
                    <a class="pop_close" onclick="closeTos()" href="javascript:void(0)">×</a>
                    <h3>
                        <span id="main_lblCompanyName2">Label</span></h3>
                    <div class="input-container" id="showmap" style="height:480px;">
                        
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                function ShowMap(suppliername, sLat, sLng) {
                    popUp("divMap");
                    $("span[id$='lblCompanyName2']").text(suppliername);
                    setLatLng(sLat, sLng);
                    return false;
                }
            </script>

            <div class="clear">
            </div>
            <!--footer-->
            <div class="hz-footer bt-e2 bgf9">
                <div class="hz-wrapper">
                    <div class="fl pt15 pb15 wid-01 bt-ef tc lh26 fc8">

                        <div style="margin:0px auto; width:600px;">
                            <div style="float:left; padding: 20px 0px 20px 0px;"  id="dt_footer">
                                上海中盈保险经纪有限公司&nbsp;&nbsp;
                                <a class="pr5 lk-f8" href="http://www.miitbeian.gov.cn/" rel="nofollow" target="_blank">沪ICP备11037892号</a>Copyright<em class="pl5 pr5">©</em>2012-
                                <script language="JavaScript" type="text/javascript">
                                    Btoday = new Date();
                                    document.write(Btoday.getFullYear());</script><br />
                                <a class="pr5 pl5 lk-f8" href="#" target="_blank">中盈保险网</a>版权所有</div>
                            <div style="float:left; margin-left:30px;"><img src="<?php echo $sStaticRoot ?>/backend/img/qr_code.jpg" width="80" height="80" alt="" /></div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="ctl00_HrShopWindowManager" style="z-index:7002;display:none;">
                <!-- 2012.3.1016.40 --><div id="ctl00_WinSmall" style="display:none;">
                    <div id="ctl00_WinSmall_C">

                    </div><input id="ctl00_WinSmall_ClientState" name="ctl00_WinSmall_ClientState" type="hidden" />
                </div><div id="ctl00_WinLarge" style="display:none;">
                    <div id="ctl00_WinLarge_C">

                    </div><input id="ctl00_WinLarge_ClientState" name="ctl00_WinLarge_ClientState" type="hidden" />
                </div><div id="ctl00_HrShopWindowManager_alerttemplate" style="display:none;">
                    <div class="DialogStyle" style="display: block; width: 100%; height: 240px;">
                        <div class="mainArea">
                            <h3 class="NoB">
                                信息提示</h3>
                            <div class="topToolbar">
                                <a onclick="$find('{0}').close();" href="javascript:void(0);">
                                    <img src="/Content/images/icon_r_b_close.png" /></a>
                            </div>
                            <div class="content" style="height: 120px; overflow-y: auto;">
                                {1}
                            </div>
                            <div class="ButtonArea">
                                <a onclick="$find('{0}').close();" class="Bu1" href="javascript:void(0);">确定</a>
                            </div>
                        </div>
                    </div>
                </div><div id="ctl00_HrShopWindowManager_prompttemplate" style="display:none;">
                    <div class="rwDialogPopup radprompt">          
                        <div class="rwDialogText">
                            {1}             
                        </div>      
                        <div>
                            <script type="text/javascript">
                                function RadWindowprompt_detectenter(id, ev, input)
                                {
                                    if (!ev)
                                        ev = window.event;
                                    if (ev.keyCode == 13)
                                    {
                                        var but = input.parentNode.parentNode.getElementsByTagName("A")[0];
                                        if (but)
                                        {
                                            if (but.click)
                                                but.click();
                                            else if (but.onclick)
                                            {
                                                but.focus();
                                                var click = but.onclick;
                                                but.onclick = null;
                                                if (click)
                                                    click.call(but);
                                            }
                                        }
                                        return false;
                                    }
                                    else
                                        return true;
                                }
                            </script>
                            <input title="Enter Value" onkeydown="return RadWindowprompt_detectenter('{0}', event, this);" type="text"  class="rwDialogInput" value="{2}" />
                        </div>
                        <div>
                            <a onclick="$find('{0}').close(this.parentNode.parentNode.getElementsByTagName('input')[0].value);"             
                               class="rwPopupButton" href="javascript:void(0);" ><span class="rwOuterSpan"><span class="rwInnerSpan">##LOC[OK]##</span></span></a>
                            <a onclick="$find('{0}').close(null);" class="rwPopupButton"  href="javascript:void(0);"><span class="rwOuterSpan"><span class="rwInnerSpan">##LOC[Cancel]##</span></span></a>
                        </div>
                    </div>                     
                </div><div id="ctl00_HrShopWindowManager_confirmtemplate" style="display:none;">
                    <div class="rwDialogPopup radconfirm">          
                        <div class="rwDialogText">
                            {1}             
                        </div>                      
                        <div>
                            <a onclick="$find('{0}').close(true);"  class="rwPopupButton" href="javascript:void(0);" ><span class="rwOuterSpan"><span class="rwInnerSpan">##LOC[OK]##</span></span></a>
                            <a onclick="$find('{0}').close(false);" class="rwPopupButton"  href="javascript:void(0);"><span class="rwOuterSpan"><span class="rwInnerSpan">##LOC[Cancel]##</span></span></a>
                        </div>
                    </div>      
                </div><input id="ctl00_HrShopWindowManager_ClientState" name="ctl00_HrShopWindowManager_ClientState" type="hidden" />
            </div>

            <!--message bar-->
            <ul class="right-side-flyelem show">
                <a href="#">
                    <li class="rsf-items fa fa-arrow-circle-up side-icon" style="background:url('<?php echo $sStaticRoot ?>/backend/img/ciictop.png') no-repeat right center;"></li>
                </a>
                <a hre="javascript:void(0);">
                    <li class="rsf-items  fa fa-qq fa-qq3 side-icon" style="background:url('<?php echo $sStaticRoot ?>/backend/img/wx.png') no-repeat right center;" onmousemove="showqrcode(this);" onmouseout="hideqrcode();"></li>

                </a>
                <!-- <a href="../Account/ActivityApp.aspx" class='jb_btn on confirm'>
                    <li class="rsf-items fa-message glyphicon glyphicon-edit side-icon" style="background:url('<?php echo $sStaticRoot ?>/backend/img/list.png') no-repeat right center;"></li>
                </a> -->
                <a hre="javascript:void(0);">
                    <li class="rsf-items  fa fa-phone side-icon" style="background:url('<?php echo $sStaticRoot ?>/backend/img/tel.png') no-repeat right center;"></li>
                </a>
                <a href="">
                    <li class="rsf-items  fa fa-question-circle side-icon" style="background:url('<?php echo $sStaticRoot ?>/backend/img/question.png') no-repeat right center;"></li>
                </a>
            </ul>
            <div id="divQr_Code" style="position: absolute; display:none;"><img src="<?php echo $sStaticRoot ?>/backend/img/qr_code.jpg" width="110px" height="110px" /></div>


            <input type="hidden" name="ctl00$client" id="client" value="0" />
            <div id="backgroundPopup" style="height: 924px; width: 100%; display: none; opacity: 0.5;">
            </div>
            <script type="text/javascript">
                if($("#overlay_cart").length>0){
                    $("#dt_footer").css("padding-bottom","55px");
                }
            AMap.service('AMap.Geocoder',function(){//回调函数
                //实例化Geocoder
                geocoder = new AMap.Geocoder({
                    city: ""//城市，默认全国
                });
            })

            function setLatLng (lat, lng) {
                if ($('#showmap').length) {
                    var map = new AMap.Map('showmap', {
                        resizeEnable: true,
                        center: [lat, lng],
                        zoom: 13
                    });
                    var marker = new AMap.Marker({
                        position: map.getCenter()
                    });
                    marker.setMap(map);

                    // 设置鼠标划过点标记显示的文字提示
                    // marker.setTitle('');
                    // 设置label标签
                    marker.setLabel({//label默认蓝框白底左上角显示，样式className为：amap-marker-label
                        offset: new AMap.Pixel(20, 20),//修改label相对于maker的位置
                    });
                }
            }

            

                function showqrcode(obj) {
                    $("#divQr_Code").show();
                    var offsettop = $(obj).offset().top;
                    var offsetleft = $(obj).offset().left;
                    $("#divQr_Code").css({'top': offsettop + 45 + 'px', 'left': offsetleft - 115 + 'px'});
                }
                function hideqrcode() {
                    $("#divQr_Code").hide();
                }

                function fGetCode() {
                    if (document.getElementById("getcode")) {
                        document.getElementById("getcode").src = "../../Master/ValidateCode.aspx?" + Math.random();
                    }
                }
                fGetCode();

                function ShowLogin() {
                    if ($("input[id$='client']").val() == "0") {
                        popUp("tos");
                        return false;
                    }
                    else {
                        return true;
                    }

                }
                $("document").ready(function () {

                    if ($("#main_lblProductCount").text() != '') {

                        $("#lblShopNum").text($("#main_lblProductCount").text());
                    }
                    else {

                        $("#divShop").hide();
                    }
                });
            </script>
        </body>
        </html>
