<!doctype html>
<html lang="zh-cn">
    <head>
        <meta charset="utf-8">
        <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
        <meta name="keywords" content="">
        <meta name="description" content="">
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot; ?>/backend/css/common.css">
        <script type="text/javascript" src="<?php echo $sStaticRoot; ?>/js/jquery-1.11.1.min.js"></script>
        <script src="<?php echo $sStaticRoot; ?>/backend/plugin/chosen/chosen.jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot; ?>/backend/plugin/chosen/chosen.min.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="<?php echo $sStaticRoot ?>/backend/css/HrShop.css" type="text/css" />
        <link rel="stylesheet" href="<?php echo $sStaticRoot ?>/font-awesome/css/font-awesome.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/backend/css/common.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/bootstrap/css/bootstrap.css">
        <!--[if lt IE 9]>
                <script src="<?php echo $sStaticRoot; ?>/js/html5shiv.js"></script>
        <![endif]-->
        <script type="text/javascript">
            var global = {
                static_url: '<?php echo $sStaticRoot; ?>'
            };
        </script>
        <style>
        #homePage_head{border-bottom:1px solid #ccc;}
        </style>
    </head>
    <body>
        <div id="homePage_head">
            <div class="hd_global_top_bar"  id="global_top_bar">
                <div class="wrap clearfix">                    
                    <?php if (!empty($aUser['iUserID'])) { ?>
                        <div class="hd_topbar_left clearfix" style="padding-left:110px;" >
                            <span style="float: left;">
                                <span id="lblUserName"><b><?php echo $aUser['sRealName'] ?></b>，您好！</span></span>
                            <div id="global_unlogin" class="hd_unlogin_wrap">
                                <div class="hd_login_wrap" id="divusercenter">
                                    <a id="jsddm" href="/index/record/list/" class="hd_user_center fl" >个人中心</a>
                                </div>
                            </div>
                            <a id="linkOut" class="logout blue_link none" href="/index/account/logout">退出</a>
                        </div>
                    <?php } else { ?>
                        <div class="wrap clearfix">
                            <div class="hd_topbar_left clearfix" style="padding-left:110px">
                                <span style="float: left;">
                                    <span id="lblUserName"></span></span>
                            </div>
                            <div class="hd_top_manu clearfix">
                                <ul id="SingleUser" class="clearfix">
                                    <li class="hd_menu_tit">
                                        <a href="/index/account/cdlogin">个人登录</a>/
                                        <a href="/index/account/register">注册</a>
                                    </li>
                                </ul>
                                <ul class="clearfix">
                                    <li class="hd_menu_tit hd_my_favorite" id="glShouCang"><a target="_blank" href="#" onclick="addFav();" rel="sidebar"><i></i>加入收藏夹</a> </li>
                                </ul>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
            <div id="topbanner" class="wrap">
                <div class="banner_img">
                </div>
            </div>
            <div class="wrap clearfix" id="site_header">
                <div id="logo_areaID" class="hd_logo_area fl clearfix" style="padding-left: 110px;">
                    <a href="" class="fl">
                        <img id="imgLogo" src="<?php echo $sStaticRoot ?>/backend/img/ciiclogo.png" /></a>
                </div>
                <div style="float:right; padding-right:130px; color:orangered; font-size:18px; font-weight:bold; padding-top:20px ">
                    咨询电话：400-816-6768 &nbsp;&nbsp;&nbsp;&nbsp
                </div>
                <div class="hd_head_search" >
                </div>
            </div>
            <div id="headerNav" class="hd_header_nav headerNav_channel ">
                <div class="hd_fixed_bg">
                </div>
                <div class="wrap2" style="z-index: 1000;">
                    <div id="allSortOuterbox">
                        <h2 class="hd_all_sort_link fl">
                            <a href="#" class="fl" style="background-image: none; width: 90px;"></a>
                        </h2>

                    </div>
                    <div class="headerNavWrap" id="global_menu" style="width: 800px; height:45px;">
                        <ul id="wideScreenTabShowID" class="headerNavMain clearfix">
                            <li><a href="/">首页</a></li>
                            <li><a href="/index/web/list">安心体检</a></li>
                            <li><a href="/index/cooper">合作伙伴</a></li>
                            <li><a href="/index/about">关于我们</a></li>
                        </ul>
                    </div>
                    <div id="divShop" style="padding-top: 10px; padding-left: 30px; float: left; "><img src="<?php echo $sStaticRoot ?>/backend/img/shop.png" alt="" width="20px" height="20px;" />&nbsp;
                        <a href="/index/web/cartlist" style="font-size: 15px; font-weight: bold; color: #FFFFFF;">购物车</a>
                        <span style="font-size: 15px; font-weight: bold; color: #FFFFFF;">(<?php echo $aChart ? count($aChart) : 0 ?>)</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="sidebar-nav">
            <ul>
                <li>
                    <a href="javascript:void(0)" data-target="#navmenu53" class="nav-header collapsed" data-toggle="collapse" ><i class="fa fa-lock"></i> 个人中心<i class="fa fa-collapse"></i></a>
                </li>
                <li>
                    <ul id="navmenu53" class="nav nav-list ">        		
                        <li><a href="/index/account/baseinfo"><span class="fa fa-caret-right"></span>我的信息</a></li>
                        <!-- <li><a href="/index/account/safe"><span class="fa fa-caret-right"></span>账户安全</a></li> -->
                        <li><a href="/index/account/resetpwd"><span class="fa fa-caret-right"></span>修改密码</a></li>
                        <!-- <li><a href=""><span class="fa fa-caret-right"></span>用户体系</a></li> -->
                        <!-- <li><a href=""><span class="fa fa-caret-right"></span>在线咨询</a></li> -->
                        <!-- <li><a href=""><span class="fa fa-caret-right"></span>常用者信息</a></li> -->
                    </ul>
                </li>

                <li><a href="javascript:void(0)" data-target="#navmenu45" class="nav-header collapsed" data-toggle="collapse" >
                        <i class="fa fa-lock"></i> 订单中心<i class="fa fa-collapse"></i></a>
                </li>
                <li>
                    <ul id="navmenu45" class="nav nav-list ">
                        <li><a href="/index/order/list/type/1"><span class="fa fa-caret-right"></span>我的支付订单</a></li>
                        <li><a href="/index/record/list/"><span class="fa fa-caret-right"></span>我的体检记录</a></li>
                        <!-- <li><a href="/index/order/score"><span class="fa fa-caret-right"></span>评价管理</a></li> -->
                    </ul>
                </li>
        </div>
        <div class="content" style="padding:0px"><?php include $_script; ?></div>
        <div class="actGotop" id="backtop" style="display: block;">
            <a href="javascript:;" title="返回顶部"></a>
        </div>
        <script src="<?php echo $sStaticRoot ?>/js/jquery-1.9.1.min.js" type="text/javascript"></script>
        <script src="<?php echo $sStaticRoot ?>/js/common.js" type="text/javascript"></script>
        <script src="<?php echo $sStaticRoot ?>/js/panel.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot; ?>/js/alert.js"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot; ?>/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot; ?>/js/validate.js"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot; ?>/js/phpjs.min.js"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/public.js"></script>
        <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/product-tab.js"></script>
        <script type="text/javascript" src="http://webapi.amap.com/maps?v=1.3&key=4bfffe2dca93bbf875de0181774419c4&plugin=AMap.Autocomplete,AMap.PlaceSearch"></script>
        <script type="text/javascript">
            function ShowMap(suppliername, sLat, sLng) {
                popUp("divMap");
                $("span[id$='lblCompanyName2']").text(suppliername);
                setLatLng(sLat, sLng);
                return false;
            }
            AMap.service('AMap.Geocoder',function(){//回调函数
                //实例化Geocoder
                geocoder = new AMap.Geocoder({
                    city: ""//城市，默认全国
                });
            })

            function setLatLng (lat, lng) {
                if ($('#showmap').length) {
                    var map = new AMap.Map('showmap', {
                        resizeEnable: true,
                        center: [lat, lng],
                        zoom: 13
                    });
                    var marker = new AMap.Marker({
                        position: map.getCenter()
                    });
                    marker.setMap(map);

                    // 设置鼠标划过点标记显示的文字提示
                    // marker.setTitle('');
                    // 设置label标签
                    marker.setLabel({//label默认蓝框白底左上角显示，样式className为：amap-marker-label
                        offset: new AMap.Pixel(20, 20),//修改label相对于maker的位置
                    });
                }
            }
        </script>
    </body>
</html>