<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <title><?php echo isset($aMeta['title']) ? $aMeta['title'] : '' ?></title>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0"/>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="format-detection" content="telephone=no">
    <meta name="keywords" content="<?php echo isset($aMeta['keywords']) ? $aMeta['keywords'] : '' ?>">
    <meta name="description" content="<?php echo isset($aMeta['description']) ? $aMeta['description'] : '' ?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/bootstrap/css/bootstrap.css">
    <!--<link href="http://cdn.bootcss.com/bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet">-->

    <link rel="stylesheet" href="<?php echo $sStaticRoot ?>/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/backend/css/wxcommon.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/backend/css/nav.css">


    <script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $sStaticRoot ?>/backend/js/fenye_search.js"></script>
    <script src="<?php echo $sStaticRoot ?>/backend/plugin/chosen/chosen.jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/backend/plugin/chosen/chosen.min.css">
    <!--[if lt IE 9]>
    <script src="<?php echo $sStaticRoot ?>/js/html5shiv.js"></script>
    <![endif]-->
    <script type="text/javascript">
        shareObj = {
            appId: "<?php echo $signPackage["appId"];?>",
            timestamp: '<?php echo $signPackage["timestamp"];?>',
            nonceStr: '<?php echo $signPackage["nonceStr"];?>',
            signature: '<?php echo $signPackage["signature"];?>',
            link:'<?php echo $sCurrUrl?>',
            imgUrl: "",
            title: "",
            iShareType: ""
        };
    </script>
    <script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
    <script type="text/javascript" src="<?php echo $sStaticRoot ?>/backend/js/wx.js"></script>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-fixed-top navbar-blue text-center clearfix">
        <?php if (!empty($iHomeIcon)) {
        ?>
        <div class="homeicon">
                <a href="<?php echo !empty($sIndexUrl) ? $sIndexUrl : '' ?>"
                   class="fa fa-2x fa-home btn-icon"></a>
        </div>
        <?php
        } ?>
        <span class="menutitle"><?php echo !empty($sTitle) ? $sTitle : '' ?></span>
        <?php if (!empty($iCartIcon)) {
            ?>
            <a class="cartbtn btn btn-primary pull-right"
               href="<?php echo !empty($sCartlistUrl) ? $sCartlistUrl : 'javascript:;' ?>">
                <i class="fa fa-shopping-cart fa-lg"></i> <?php echo !empty($aCommonLang[33]) ? $aCommonLang[33] : '' ?>
                (<span class="cartnumber"><?php echo !empty($aChart) ? count($aChart) : 0 ?></span>)</a>
        <?php
        } ?>
    </nav>
    <?php include $_script; ?>
    <?php if (empty($iCartFoot)) {
        ?>
        <div id="footer">
            <div>
                    <span class="col-xs-12"><b><a
                                href="<?php echo $sAboutUrl ?>"><?php echo !empty($aCommonLang[25]) ? $aCommonLang[25] : '' ?></a></b> | <b><a
                                href="<?php echo $sPartnerUrl ?>"><?php echo !empty($aCommonLang[26]) ? $aCommonLang[26] : '' ?></a></b>
                    </span>
            </div>
            <div>
            <span class="col-xs-12"><?php echo !empty($aCommonLang[27]) ? $aCommonLang[27] : '' ?>：<a
                    href="tel:<?php echo !empty($sTel) ? $sTel : '' ?>"><?php echo !empty($sPhoneNum) ? $sPhoneNum : '' ?></a></span>

            </div>
        </div>
    <?php
    }?>
</div>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/alert.js"></script>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/validate.js"></script>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/phpjs.min.js"></script>
<!--<script type="text/javascript" src="--><?php //echo $sStaticRoot ?><!--/backend/js/common.js"></script>-->
<script type="text/javascript"><?php echo @$__showDebugInfo__ ?></script>
<script>
    var cartlist = '<?php echo $sCartlistUrl?>';
    function addCart(location)
    {
        var productid = $('#iProductID').val();
        var Url = '<?php echo $sAddCartUrl;?>';
        var seccussmsg = '<?php echo !empty($aCommonLang[36]) ? $aCommonLang[36] : '' ?>';
        var failmsg = '<?php echo !empty($aCommonLang[37]) ? $aCommonLang[37] : '' ?>';
        $.get(Url, {id: productid}, function (ret) {
            if (ret.status) {
                if (location) {
                    window.location.href = location;
                    return false;
                }
                $('.cartnumber').html(ret.data);
                alert(seccussmsg);
            } else {
                alert(failmsg);
            }
        }, 'json');
    }
    $('#cartbtn').click(function () {//加入购物车
        addCart();
    });
    $('#buybtn').click(function () {//立即结算
        addCart(cartlist);
    });

</script>
</body>
</html>