<div class="row c mb10">
    <div class="page_location" style="padding-left: 30px;">
        <a title="首页" href="#">首页</a><span class="location_next">&gt;</span><span>合作伙伴</span>
    </div>
</div>

<!-- 中间  -->
<div id="public_c" class="margin_1">
    <div class="public_c">
        <div class="w_950 margin_1 float_l">
            <table cellpadding="0" cellspacing="0" border="0" width="100%">
                <tr>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r16_c8.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r15_c6.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r15_c4.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r15_c2.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r12_c8.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r12_c6.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r12_c2.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r11_c4.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r7_c4.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r7_c2.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r6_c8.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r5_c6.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r2_c8.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r2_c6.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r2_c4.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r2_c2.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/meinian.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/ciming.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                        <img src="<?php echo $sStaticRoot ?>/backend/img/aikang.jpg" alt="0" style="border:1px solid #CCCCCC; width:194px; height:122px" />
                    </td>
                    <td>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="clear">
</div>
