<div class="div_welcome_picbg">

    <div class="div_welcome_cen_picbg">

        <div class="div_welcome_big_banner">

        </div>
    </div>
    <!-- banner end -->
</div>
<!-- 中间  -->
<div id="public_c" class="margin_1">
    <div class="public_c" style="width:1000px">

        <!-- 为什么选择中盈安心服务/用户看中盈安心服务  -->
        <div class="w_950 float_l" style="width:1000px">
            <!-- 为什么选择中盈安心服务  -->
            <div class="why_chhz border_1 float_l">
                <div class="why_chhz_tt background_1 border_2">
                    为什么选择中盈安心服务？</div>
                <div class="why_chhzt">
                    <div class="why_chhzth_l">
                        <div class="why_chhzth_l_2">
                            <font style="color: #666">传统代理人（败）</font></div>
                        <div class="why_chhzth_l_3">
                            传统代理人一般只能为您提供一家公司产品。</div>
                        <div class="why_chhzth_l_4">
                            传统代理人经常为您推荐佣金最丰厚的产品而不是最适合您的产品。</div>
                        <div class="why_chhzth_l_5">
                            在理赔环节，传统代理人只能为您提供资料递送的便利，并不能为您真正解决“理赔难”的保险通病。</div>
                    </div>
                    <div class="why_chhzth_r">
                        <div class="why_chhzth_r_2">
                            <font style="color: #666">中盈安心服务团队（胜）</font></div>
                        <div class="why_chhzth_r_3">
                            我们优选各家公司优质产品，选择面更广，且产品容易进行比较。</div>
                        <div class="why_chhzth_r_4">
                            我们深知一份保险对一个家庭的重要性，我们秉承中立无倾向的立场向您推荐最适合您的险种或者给您最中肯的建议。用我们专业的服务换取您的满意体验！</div>
                        <div class="why_chhzth_r_5">
                            我们的专家理赔团队不仅提供理赔的跟进，更为您提供全面的理赔分析。我们始终站在用户的角度，维护您的最大权益。</div>
                    </div>
                </div>
            </div>
            <!-- 为什么选择中盈安心服务 over-->
            <!-- 用户看中盈安心服务  -->
            <div class="user_see border_1 float_r">
                <div class="user_see_tt background_1 border_2">
                    用户看中盈安心服务</div>
                <div class="user_seet">
                    <div id="tabcontent1" class="user_seet_2">
                        <span>因为理赔选择中盈安心服务</span>
                        <p>
                            我是上海一投保客户，在中盈安心服务给我儿子买了份某保险公司的产品，我儿子因打篮球导致韧带损伤，用了将近两万元的治疗费用。我提交了资料给保险公司，结果保险公司拒赔了，说是投保前就有的旧伤引起的，中盈安心服务理赔人员得知该情况后，咨询了数位骨科专家医生，得知，这种急性前交叉韧带损伤，几天内靠股骨上端出现吸收表现完全可能，而且胫骨残端保留，说明是新伤。</p>
                        <p>
                            在中盈安心服务的帮助下，跟保险公司理赔部门多次沟通协调，两个月后我终于拿到了全额的赔款！</p>
                    </div>
                    <div id="tabcontent2" class="user_seet_2 display">
                        <span>保险，不买贵的，买对的！</span>
                        <p>
                            我28岁，刚结婚，有房贷，收入较稳定。我对于保险有种本能的抗拒，但是看着朋友们都相继为自己和家人购买了保险。特别是看到近期发生在我们身边的事故，更使我下决心为我和先生购买合适的保险。有保险公司业务人员向我推荐了万能险，可年缴6000元/人，主要保10万重疾。可家庭才刚形成，1年两个人就要1万多，缴费压力比较大。我就此特咨询了中盈安心服务健康险专家，才知道万能险不适合我，从保障角度并不能解决我担心的问题。感谢中盈安心服务，这才是我真正想要的保险服务！</p>
                    </div>
                    <div id="tabcontent3" class="user_seet_2 display">
                        <span>我收获的不只是保单</span>
                        <p>
                            我来自湖南益阳，在深圳工作，家庭压力较大，有房贷，妻子是家庭主妇。今年4月份宝宝出生，如今都6个月大了。因为宝宝从出生以后经常生病，住了几次医院。有某保险人员建议我给孩子购买分红型保险+重疾险，共计7480元。在我犹豫的时候咨询了中盈安心服务的保险专家，得知应该先给大人做足保障再考虑孩子的保障，优先从意外和健康型保险开始投保，分红险是在做足保障的前提下，再考虑。感谢中盈安心服务以中立的立场帮我们家庭设立了合适的保险方案。</p>
                    </div>
                </div>
            </div>
            <!-- 用户看中盈安心服务 over-->
        </div>
        <!-- 为什么选择中盈安心服务/用户看中盈安心服务 over-->
        <div class="clear">
        </div>
        <!-- 文本信息  -->
        <div class="w_950 margin_1 float_l">
            <div class="health_caset float_l border_1">

                <div class="health_pbp_o float_l" name="2F">
                    <p>
                        常见问题</p>
                    <table id="main_RepList_Left" cellspacing="0" style="width:100%;border-collapse:collapse;">
                        <?php if ($aFaq['aList']) {
                        foreach ($aFaq['aList'] as $key => $value) {
                            if ($key % 2 == 0) { echo('<tr>'); ?>
                            <td>
                                <div style="float: left; width: 450px; padding-left: 20px; font-size: 13px; line-height: 25px;">
                                    <span id="main_RepList_Left_lblID_0" style="display: none;">1</span>
                                    <span style="font-weight: bold;">·</span>
                                    <a id="main_RepList_Left_lnkDetail_0" title="<?php echo $value['sTitle'] ?>" href="/index/news/id/<?php echo $value['iAutoID']?>" target="_blank"><?php echo $value['sTitle'] ?></a>
                                </div>
                            </td>
                            <?php } else { ?>
                            <td>
                                <div style="float: left; width: 450px; padding-left: 20px; font-size: 13px; line-height: 25px;">
                                    <span id="main_RepList_Left_lblID_0" style="display: none;">1</span>
                                    <span style="font-weight: bold;">·</span>
                                    <a id="main_RepList_Left_lnkDetail_0" title="<?php echo $value['sTitle'] ?>" href="/index/news/id/<?php echo $value['iAutoID']?>" target="_blank"><?php echo $value['sTitle'] ?></a>
                                </div>
                            </td>
                            <?php echo('</tr>'); } } } ?>
                    </table>
                </div>
            </div>
        </div>
        <!-- 文本信息 over-->
        <div class="clear">
        </div>
    </div>
</div>
<!-- 中间 over-->
<div class="clear">
</div>
