<div class="pheader clearfix"><?php echo isset($aCity['iCityID'])?'编辑':'增加'?>城市</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
		<div class="form-group">
			<label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 新密码：</label>
			<div class="col-sm-10">
				<input name="sPassword" type="text" value="" class="form-control">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 重复密码：</label>
			<div class="col-sm-10">
				<input name="sRePassword" type="text" value="" class="form-control">
			</div>
		</div>
    	<div class="btn-toolbar text-center">
        	<button id="savebtn" class="btn btn-primary">确认修改</button>
        </div>
	</form>
</div>
<script type="text/javascript">
$(function() {
	$("#savebtn").click(function(){
		var form = $('#myform');
	    $.post(form.action?form.action:location.href, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            //location.href = '/admin/city/list/';
	        }
	    }, 'json');
		return false;
	});
});
</script>