<div style="margin-top:1px;"></div>
<div class="cf2 login_w gray_border" style="margin: 20px auto;padding-bottom: 1px;">
	<dl class="tab_nav login_nav">
		<dd>
			<a href="javascript:;" class="<?php echo $iType==1?'tab_light':''?>">广告主登录</a>
			<a href="javascript:;" class="<?php echo $iType==2?'tab_light':''?>">自媒体登录</a>
		</dd>
	</dl>

	<input type="hidden" name="retUrl" id="retUrl" value="<?php echo $retUrl?>">
	<div class="tab_box login_t_box">
		<div>
			<form action="/user/login" method="post">
				<input type="hidden" name="type" value="1">
				<dl class="login_box">
					<dt>
						<div class="input_text">
							<span class="l_1 png"></span>
							<input type="text" name="user" class="login_text r login_text_top" placeholder="请输入登录邮箱">
				            <label class="error user" style="display: none"></label>
						</div>

						<div class="input_text">
							<span class="l_2 png"></span>
							<input type="password" name="pass" class="login_text r login_text_top"	placeholder="请输入登录密码">
				            <label class="error pass" style="display: none"></label>
						</div>

						<div>
							<input type="text" name="code" class="login_text hover_input"
								placeholder="输入验证码" style="width: 100px;">
							<a href="javascript:;" style="padding-left: 1em;">
								<img class="verifyimage" style="width: 120px; height: 40px"
									src="/verify/image/type/1" alt="">
							</a>
				            <label class="error code" style="display: none"></label>
						</div>
					</dt>
					<dd>
						<input type="button" class="login_btn_i" value="确认登录">
						<p>
							<span class="r blue_link"><a href="/user/forget/type/1.html">忘记密码</a></span><span
								class="l red_link">没有帐户？<a href="/user/register.html?type=1">立即注册</a></span>
						</p>
					</dd>
				</dl>
			</form>
		</div>
		<!--end广告主登录-->
		<div>
			<form action="/user/login" method="post">
				<input type="hidden" name="type" value="2">
				<dl class="login_box">
					<dt>
						<div class="input_text">
							<span class="l_1"></span>
							<input type="text" name="user" class="login_text r login_text_top" placeholder="请输入登录邮箱">
				            <label class="error user" style="display: none"></label>
						</div>

						<div class="input_text">
							<span class="l_2"></span>
							<input type="password" name="pass" class="login_text r login_text_top"	placeholder="请输入登录密码">
				            <label class="error pass" style="display: none"></label>
						</div>

						<div>
							<input type="text" name="code" class="login_text hover_input"
								placeholder="输入验证码" style="width: 100px;">
							<a href="javascript:;" style="padding-left: 1em;">
								<img class="verifyimage" style="width: 120px; height: 40px"
									src="/verify/image/type/2" alt="">
							</a>
				            <label class="error code" style="display: none"></label>
						</div>
					</dt>
					<dd>
						<input type="button" class="login_btn_i" value="确认登录">
						<p>
							<span class="r blue_link"><a href="/user/forget/type/2.html">忘记密码</a></span><span
								class="l red_link">没有帐户？<a href="/user/register.html?type=2">立即注册</a></span>
						</p>
					</dd>
				</dl>
			</form>
		</div>
		<!--end自媒体登录-->
	</div>
	<!--end标签内容-->
</div>
<!--end中间区域-->
<script type="text/javascript">
$(function(){
	$('.login_btn_i').click(function(){
		var form = $(this).parents('form').get(0);
		var type = $(form).find('input[name=type]').val();
    	$.post(form.action?form.action:location.href, $(form).serialize(), function(ret){
	        if (ret.status) {
		        go_user_home(form); 
	        } else {
	        	$(form).find('label.error').hide();
	        	for (var key in ret.data) {
		        	$(form).find('.' + key).html(ret.data[key]).show();
	        	}
	        	resetVerifyImage($(form).find('.verifyimage').get(0));
	        }
	    }, 'json');
		return false;
	});

	function go_user_home(form){
		if ($('#retUrl').val().length > 0) {
			location.href = $('#retUrl').val();
			return ;
		}
		var type = $(form).find('input[name=type]').val();
		if (type == 1) {
		    location.href = '/acenter/index.html';
		} else {
    		location.href = '/mcenter/index.html';
		}
    }
    
	function resetVerifyImage(img){
		var src = img.src.substring(0, img.src.indexOf('?')) + '';
		src = src.length == 0 ? img.src : src;
		img.src = src + '?r=' + Math.random();
	}
	$('.verifyimage').click(function(){
		resetVerifyImage(this);
	});
});
</script>