<!doctype html>
<!--[if IEMobile 7]><html lang="zh-hans" class="iem7" xmlns="http://www.w3.org/1999/xhtml" dir="ltr"><![endif]-->
<!--[if lte IE 6]><html lang="zh-hans" class="lt-ie10 lt-ie9 lt-ie8 lt-ie7" xmlns="http://www.w3.org/1999/xhtml" dir="ltr"><![endif]-->
<!--[if (IE 7)&(!IEMobile)]><html lang="zh-hans" class="lt-ie10 lt-ie9 lt-ie8 ie7" xmlns="http://www.w3.org/1999/xhtml" dir="ltr"><![endif]-->
<!--[if IE 8]><html lang="zh-hans" class="lt-ie10 lt-ie9 ie8" xmlns="http://www.w3.org/1999/xhtml" dir="ltr"><![endif]-->
<!--[if IE 9]><html lang="zh-hans" class="lt-ie10 ie9" xmlns="http://www.w3.org/1999/xhtml" dir="ltr"><![endif]-->
<html>
<head>
<meta charset="utf-8">
<title>安心体检用户中心</title>
<meta http-equiv="cleartype" content="on">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<meta name="MobileOptimized" content="width">
<meta name="HandheldFriendly" content="true">
<meta name="viewport" content="width=device-width"  /><!-- media setting -->
<meta http-equiv="cleartype" content="on"><!-- MS important -->
<meta name="apple-mobile-web-app-capable" content="yes"><!-- hide ios topbar -->      
<meta content="telephone=no" name="format-detection" /><!-- stop call phone -->

<!-- Facicon 57*57 / Retina 114*114 / ipad 72*72 / Ios desktop -->    
<link rel="apple-touch-icon-precomposed" href="<?php echo $sStaticRoot?>/backend/img/iphone_icon_57.png" sizes="57x57"/>
<link rel="apple-touch-icon-precomposed" href="<?php echo $sStaticRoot?>/backend/img/iphone_icon_114.png" sizes="114x114"/>
<link rel="apple-touch-icon-precomposed" href="<?php echo $sStaticRoot?>/backend/img/iphone_icon_72.png" sizes="72x72"/>    		
<link rel="apple-touch-startup-image" href="<?php echo $sStaticRoot?>/backend/img/iphone_icon_57.png" />

<script src="<?php echo $sStaticRoot?>/backend/js/phoneAgent.js"></script>
<script src="<?php echo $sStaticRoot?>/backend/js/jquery-2.1.1.min.js"></script>

<script src='<?php echo $sStaticRoot?>/backend/js/idangerous.swiper-2.1.min.js'></script>
<script src="<?php echo $sStaticRoot?>/backend/js/function.js"></script>
<link rel="stylesheet" href="<?php echo $sStaticRoot?>/backend/css/ciic.css" type="text/css" media="all">
</head>

<body>
<form id="myform" action="" method="post">
<div id="main">
    <div id="sign_2">
    <div id="br_lt"><img src="<?php echo $sStaticRoot?>/backend/img/border_left.png" /></div>
    <div id="logo" class="logo_2">安心体检</div>
    
           <div class="sign_fr_box active">
           <h5>帐号登录</h5>
           <input name="sUserName" type="text" placeholder="帐号"/>
           <input type="password" name="sPassword" placeholder="密码"/>
           <input type="text" name="sCode" id="verify" placeholder="验证码"/>
           <!-- id="sCode" -->
          <img width="80" height="36" class="l" id="verify_nb" alt="看不清楚.点击更换" style="cursor: pointer; margin-left:5px;" src=".">
          <button id="login" type="button">登录</button>
           <a href="/index/account/register" class=""><button type="button" id="forget">免费注册</button></a>           
           <a href="/index/account/forgetpwd" class=""><button type="button" id="forget">忘记密码</button></a>
           </div>

           <div class="switch">
              <a id="main_hlLogin" href="/index/account/cdlogin"><button type="button">体检卡登录</button></a>
              <a id="main_hlLogin" href="/index/account/idlogin"><button type="button">身份证登录</button></a>
           </div>
           <div class="tl_nb"><img src="<?php echo $sStaticRoot?>/backend/img/tp_number_bl.png" /></div>
           
     <div id="footer_2">
         <div id="qr_code"><img src="<?php echo $sStaticRoot?>/backend/img/qr_code.jpg" width="100" /></div>
         <img src="<?php echo $sStaticRoot?>/backend/img/ciic_logo.png" />
         <p>上海中盈保险经纪有限公司</p>
         <p>沪ICP备11037892号
         <p>Copyright©2012- 2015</p>
         <p>中盈保险网版权所有</p>
     </div>
    </div>
    <div id="banner_2" style='height:640px'>
    <div class="br_ic_9"><img src="<?php echo $sStaticRoot?>/backend/img/banner_icon_4.png" /></div>
    </div>
</div>
</form>
</body>

<script>
var CodeUrl = '/index/verify/image?type=<?php echo $iCodeType ?>';
var UcenterUrl = '/index/record/list';
function codeChange()
{
    $('#verify_nb').attr('src',CodeUrl+'&'+Math.random());
}
codeChange();
$('#verify_nb').click(function(){
    codeChange();
});
$('#login').click(function(){
    var CanSummit = 1;
    var form = $('#myform');
    if (CanSummit) {
        $.post(form.action, $(form).serialize(), function (ret) {
            if (ret.status) {
                //跳转第二步
                alert('登陆成功！');
                window.location = UcenterUrl;
                return true;
            } else {
                alert(ret.data);
                codeChange();
                return false;
            }
        }, 'json');
    }
    return false;
})
</script>
</html>
