<div class="pheader clearfix">体检人员名单</div>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="">
        <div class="row">
            <div class="form-group col-sm-3">
                <label>请款编号：</label>
                <input type="text" value="<?php echo !empty($aParam['sBalanceCode']) ? $aParam['sBalanceCode'] : '' ?>" class="form-control" name="sBalanceCode" style="width: 130px">
            </div>
            <div class="form-group col-sm-3">
                <label>状态：</label>
                <select name="iStatus" class="form-control" style="width: 100px">
                    <option value="-1" <?php echo empty($aParam['iStatus'])  ? 'selected' : '' ?>>全部</option>
                    <?php foreach ($aBalanceStatus as $k => $v) { ?>
                        <option value="<?php echo $k ?>" <?php echo isset($aParam['iStatus']) && $aParam['iStatus'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>

            <div class="form-group col-sm-5">
                <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
            </div>
        </div>
    </form>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center">凭证编号</th>
            <th class="text-center">请款月份</th>
            <th class="text-center">金额</th>
            <th class="text-center">状态</th>
            <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php if ($aList['aList']) {
            foreach ($aList['aList'] as $key => $aBalance) { ?>
                <tr>                   
                    <td class="text-center"><?php echo $aBalance['sBalanceCode'] ?></td>
                    <td class="text-center"><?php echo $aBalance['sMonth'] ?></td>
                    <td class="text-center"><?php echo $aBalance['iSMoney'] ?></td>                 
                    <td class="text-center"><?php echo $aBalance['sStatus'] ?></td>
                    <td class="text-center">
                        <?php if ($aBalance['iStatus'] == 1) { ?>
                        <a href="/supplier/balance/sign/iBalanceID/<?php echo $aBalance['iBalanceID']?>">查看</a>
                        <?php } else { ?>
                        <a href="/supplier/balance/detail/id/<?php echo $aBalance['iBalanceID']?>">查看</a>
                        <?php } ?>
                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
    <?php echo !empty($aList['aPager']) ? $aList['aPager'] : '' ?>
</div>

<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/laydate/laydate.js"></script>