<div class="buy_pro_main">
    <div class="page_location">
        <a href="#">体检机构</a><span class="location_next">&gt;</span>
        <span id="main_lblTitle" class="f_c_999"></span>
    </div>
    <div  style=" padding-left:15px; padding-right:15px;">
        <div class="pro_big_img_info pt10 pb10" style="width: 100%">
            <div class="summary c" style="border-bottom:none;">
                <div class="c">
                    <ul style="width: 100%">
                        <li>
                            <span id="main_lblCompanyName" style="font-size: 18px; font-weight: bold;">
                                <?php echo $aStore['sName']?>
                            </span>&nbsp;&nbsp;&nbsp;&nbsp;
                            <span id="main_lblCityName"><?php echo $aCity[$aStore['iCityID']]?></span>
                            /<span id="main_lblAreaName"><?php echo $aRegion[$aStore['iRegionID']]?></span>&nbsp;&nbsp;&nbsp;&nbsp;
                            <img src="<?php echo $sStaticRoot?>/backend/img/dw.gif" alt="" onclick="ShowMap();" style="cursor:pointer;" />
                        </li>
                        <li>
                            <span class="f_c_999">具体地址：</span>
                            <span id="main_lblAddress" class="f_c_999">上海市静安区西康路608号</span>
                        </li>
                        <li><span class="f_c_999">营业时间：</span><span id="main_lblWorkDay" class="f_c_999">周二到周日 7:30-10:30  周二到周日值班到14:30</span>
                        </li>
                        <li><span class="f_c_999">附近交通：</span><span id="main_lblTrafficLine" class="f_c_999">地铁7号线至昌平路站；                        113路至昌平路西康路-公交车站</span>
                        </li>
                        <li><span class="f_c_999">咨询电话：</span><span id="main_lblPhone" class="f_c_999">4006803373</span>
                        </li>
                        <li class="summary_other c"><span class="f_c_999 fl">点击分享：</span>
                            <div class="bdsharebuttonbox fl mt5">
                                <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq"
                                    data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_weixin" data-cmd="weixin"
                                        title="分享到微信"></a><a href="#" class="bds_more" data-cmd="more"></a>
                            </div>
                            <script type="text/javascript">
                                window._bd_share_config = { "common": { "bdSnsKey": {}, "bdText": "", "bdMini": "2", "bdMiniList": false, "bdPic": "", "bdStyle": "0", "bdSize": "16" }, "share": {} }; with (document) 0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];
                            </script>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div style="width:100%">
        <div class="mt10">
            <div class="search_con" style="border-top: 3px solid #0D8FE3;">
                
                    
                        <table class="table_dailiList" style="margin-top: 10px; margin-bottom: 10px; float: left;" width="100%">
                            <tr>
                                <td>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td style="width: 70%">
                                                    <span id="main_RepList_lblProductName_0" style="color:Orange;font-size:16px;font-weight:bold;margin-bottom: 20px;">安心基础套餐PC</span><br />
                                                </td>
                                                <td style="width: 30%; text-align: right; font-size:20px; font-weight:bold; color:orange; ">
                                                    0.01元
                                                    
                                                    
                                                    <input type="hidden" name="ctl00$main$RepList$ctl01$hidXPoint" id="main_RepList_hidXPoint_0" value="121.45284" />
                                                    <input type="hidden" name="ctl00$main$RepList$ctl01$hidYPoint" id="main_RepList_hidYPoint_0" value="31.241429" />
                                                </td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td rowspan="2" style="line-height:25px;">
                                                    <span id="main_RepList_lblInfo_0">基础健康体检套餐，除了对心、肺、肝、胆、肾等重要器官设置全面超声检查，针对女性疾病进行了常规检查，同时重点关注了甲状腺功能，及早发现甲状腺潜在的危险因素，是一套适用于职场工作的男女基础健康检查的套餐。</span>
                                                </td>
                                                <td>

                                                </td>
                                            </tr>
                                            <tr>
                                                
                                                <td style="line-height: 20px; text-align: right; " rowspan="2">
                                                    <input type="submit" name="ctl00$main$RepList$ctl01$btnAddShopCar" value="加入购物车" id="main_RepList_btnAddShopCar_0" class="btn_submit_blue" style="background-color:Orange;" />
                                                    <input type="submit" name="ctl00$main$RepList$ctl01$btnDetail" value="查看详细" id="main_RepList_btnDetail_0" class="btn_submit_blue" />
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 10px;"></td>
                            </tr>
                        </table>
                    
                        <table class="table_dailiList" style="margin-top: 10px; margin-bottom: 10px; float: left;" width="100%">
                            <tr>
                                <td>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td style="width: 70%">
                                                    <span id="main_RepList_lblProductName_1" style="color:Orange;font-size:16px;font-weight:bold;margin-bottom: 20px;">安心经典套餐PC</span><br />
                                                </td>
                                                <td style="width: 30%; text-align: right; font-size:20px; font-weight:bold; color:orange; ">
                                                    610.00元
                                                    
                                                    
                                                    <input type="hidden" name="ctl00$main$RepList$ctl02$hidXPoint" id="main_RepList_hidXPoint_1" value="121.45284" />
                                                    <input type="hidden" name="ctl00$main$RepList$ctl02$hidYPoint" id="main_RepList_hidYPoint_1" value="31.241429" />
                                                </td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td rowspan="2" style="line-height:25px;">
                                                    <span id="main_RepList_lblInfo_1">在安心基础套餐基础增加了高密度脂蛋白胆固醇、低密度脂蛋白胆固醇的筛查，此二项是针对胆固醇更进一步的检查，其指标对心血管疾病的预防有着非常重要的临床意义，同时更加关注了男性的前列腺功能和女性的子宫、乳腺功能，除了常规的彩色B超外，还增加了男女性不同的肿瘤指标筛查，此款体检产品有利于长期工作压力大，工作繁忙的白领人士对自己身体做一个综合性的健康评估，及早发现危害健康的危险因素。</span>
                                                </td>
                                                <td>

                                                </td>
                                            </tr>
                                            <tr>
                                                
                                                <td style="line-height: 20px; text-align: right; " rowspan="2">
                                                    <input type="submit" name="ctl00$main$RepList$ctl02$btnAddShopCar" value="加入购物车" id="main_RepList_btnAddShopCar_1" class="btn_submit_blue" style="background-color:Orange;" />
                                                    <input type="submit" name="ctl00$main$RepList$ctl02$btnDetail" value="查看详细" id="main_RepList_btnDetail_1" class="btn_submit_blue" />
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 10px;"></td>
                            </tr>
                        </table>
                    
                        <table class="table_dailiList" style="margin-top: 10px; margin-bottom: 10px; float: left;" width="100%">
                            <tr>
                                <td>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td style="width: 70%">
                                                    <span id="main_RepList_lblProductName_2" style="color:Orange;font-size:16px;font-weight:bold;margin-bottom: 20px;">安心精英套餐PC</span><br />
                                                </td>
                                                <td style="width: 30%; text-align: right; font-size:20px; font-weight:bold; color:orange; ">
                                                    1,160.00元
                                                    
                                                    
                                                    <input type="hidden" name="ctl00$main$RepList$ctl03$hidXPoint" id="main_RepList_hidXPoint_2" value="121.45284" />
                                                    <input type="hidden" name="ctl00$main$RepList$ctl03$hidYPoint" id="main_RepList_hidYPoint_2" value="31.241429" />
                                                </td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td rowspan="2" style="line-height:25px;">
                                                    <span id="main_RepList_lblInfo_2">安心精英套餐在安心经典套餐健康筛查的基础增加了眼压检查，预防青光眼的发病；对胃部疾病的危害因素幽门螺杆菌进行筛查，加强了心脑血管、甲状腺功能及肝脏的细项检查，此套体检产品在基础的健康检查上更加关注了身体的隐性疾病，如因血脂等因素导致的心脑血管疾病、消化道疾病、甲状腺疾病、肝脏疾病等，有利于对隐性疾病的了解及控制。此套体检产品适用于工作6年以上，长期在办公室与电脑为伍的人群，此类人群缺乏良好的作息时间，缺乏适当的运动及休息，不注意饮食规律频繁应酬，工作家庭生活压力大，长期的不良生活习惯导致隐性疾病的滋长，而此款产品针对常见多发的危害因素进行全面的筛查，做到防微杜渐。</span>
                                                </td>
                                                <td>

                                                </td>
                                            </tr>
                                            <tr>
                                                
                                                <td style="line-height: 20px; text-align: right; " rowspan="2">
                                                    <input type="submit" name="ctl00$main$RepList$ctl03$btnAddShopCar" value="加入购物车" id="main_RepList_btnAddShopCar_2" class="btn_submit_blue" style="background-color:Orange;" />
                                                    <input type="submit" name="ctl00$main$RepList$ctl03$btnDetail" value="查看详细" id="main_RepList_btnDetail_2" class="btn_submit_blue" />
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 10px;"></td>
                            </tr>
                        </table>
                    
                        <table class="table_dailiList" style="margin-top: 10px; margin-bottom: 10px; float: left;" width="100%">
                            <tr>
                                <td>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td style="width: 70%">
                                                    <span id="main_RepList_lblProductName_3" style="color:Orange;font-size:16px;font-weight:bold;margin-bottom: 20px;">安心卓越套餐PC</span><br />
                                                </td>
                                                <td style="width: 30%; text-align: right; font-size:20px; font-weight:bold; color:orange; ">
                                                    1,620.00元
                                                    
                                                    
                                                    <input type="hidden" name="ctl00$main$RepList$ctl04$hidXPoint" id="main_RepList_hidXPoint_3" value="121.45284" />
                                                    <input type="hidden" name="ctl00$main$RepList$ctl04$hidYPoint" id="main_RepList_hidYPoint_3" value="31.241429" />
                                                </td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td rowspan="2" style="line-height:25px;">
                                                    <span id="main_RepList_lblInfo_3">安心卓越套餐是一款细致全面的健康普查产品。在基本的健康检查项目基础上，重点对于女性的高发病种宫颈癌做了女性宫颈TCT检查，预防宫颈早期病变；心脏彩超的检查，能够更细致的观察心血管结构，了解心脏各组成部分的形态以及功能状态；经颅多普勒则是了解颅内及颅外各血管、脑动脉环血管及其分支的血流情况，判断有无硬化、狭窄、缺血、畸形、痉挛等血管病变，对脑血管疾病进行动态监测；同时针对口腔、骨质疏松症等进行筛查。此款体检产品增适用于工作多年，工作压力较大，经常熬夜，饮食无规律的男女性人群，是全面体检的不二选择。</span>
                                                </td>
                                                <td>

                                                </td>
                                            </tr>
                                            <tr>
                                                
                                                <td style="line-height: 20px; text-align: right; " rowspan="2">
                                                    <input type="submit" name="ctl00$main$RepList$ctl04$btnAddShopCar" value="加入购物车" id="main_RepList_btnAddShopCar_3" class="btn_submit_blue" style="background-color:Orange;" />
                                                    <input type="submit" name="ctl00$main$RepList$ctl04$btnDetail" value="查看详细" id="main_RepList_btnDetail_3" class="btn_submit_blue" />
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 10px;"></td>
                            </tr>
                        </table>
                    
                        <table class="table_dailiList" style="margin-top: 10px; margin-bottom: 10px; float: left;" width="100%">
                            <tr>
                                <td>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td style="width: 70%">
                                                    <span id="main_RepList_lblProductName_4" style="color:Orange;font-size:16px;font-weight:bold;margin-bottom: 20px;">安心红日套餐PC</span><br />
                                                </td>
                                                <td style="width: 30%; text-align: right; font-size:20px; font-weight:bold; color:orange; ">
                                                    1,320.00元
                                                    
                                                    
                                                    <input type="hidden" name="ctl00$main$RepList$ctl05$hidXPoint" id="main_RepList_hidXPoint_4" value="121.45284" />
                                                    <input type="hidden" name="ctl00$main$RepList$ctl05$hidYPoint" id="main_RepList_hidYPoint_4" value="31.241429" />
                                                </td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td rowspan="2" style="line-height:25px;">
                                                    <span id="main_RepList_lblInfo_4">安心红日套餐是针对中老年人易发及潜在的疾病进行筛查，在心脑血管疾病方面除了常规的检查外，增加了颈颅多普勒、血流变、颈动脉彩超、心脏彩超等项目，让体检者进一步了解身体各部位的功能状态，对心脑血管疾病进行动态监测；同时通过肝病、肾病、高血脂、骨质疏松等慢性病及常见高发的肿瘤进行筛查，准确的提供早期预警，让中老年人更好的了解目前身体状况，及早发现潜在的危害健康危险因素，并对中老年人的个人健康给出综合性的评估。</span>
                                                </td>
                                                <td>

                                                </td>
                                            </tr>
                                            <tr>
                                                
                                                <td style="line-height: 20px; text-align: right; " rowspan="2">
                                                    <input type="submit" name="ctl00$main$RepList$ctl05$btnAddShopCar" value="加入购物车" id="main_RepList_btnAddShopCar_4" class="btn_submit_blue" style="background-color:Orange;" />
                                                    <input type="submit" name="ctl00$main$RepList$ctl05$btnDetail" value="查看详细" id="main_RepList_btnDetail_4" class="btn_submit_blue" />
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 10px;"></td>
                            </tr>
                        </table>
                    
                        <table class="table_dailiList" style="margin-top: 10px; margin-bottom: 10px; float: left;" width="100%">
                            <tr>
                                <td>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td style="width: 70%">
                                                    <span id="main_RepList_lblProductName_5" style="color:Orange;font-size:16px;font-weight:bold;margin-bottom: 20px;">肾功能</span><br />
                                                </td>
                                                <td style="width: 30%; text-align: right; font-size:20px; font-weight:bold; color:orange; ">
                                                    100.00元
                                                    
                                                    
                                                    <input type="hidden" name="ctl00$main$RepList$ctl06$hidXPoint" id="main_RepList_hidXPoint_5" value="121.45284" />
                                                    <input type="hidden" name="ctl00$main$RepList$ctl06$hidYPoint" id="main_RepList_hidYPoint_5" value="31.241429" />
                                                </td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td rowspan="2" style="line-height:25px;">
                                                    <span id="main_RepList_lblInfo_5"></span>
                                                </td>
                                                <td>

                                                </td>
                                            </tr>
                                            <tr>
                                                
                                                <td style="line-height: 20px; text-align: right; " rowspan="2">
                                                    <input type="submit" name="ctl00$main$RepList$ctl06$btnAddShopCar" value="加入购物车" id="main_RepList_btnAddShopCar_5" class="btn_submit_blue" style="background-color:Orange;" />
                                                    <input type="submit" name="ctl00$main$RepList$ctl06$btnDetail" value="查看详细" id="main_RepList_btnDetail_5" class="btn_submit_blue" />
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 10px;"></td>
                            </tr>
                        </table>
                    
                        <table class="table_dailiList" style="margin-top: 10px; margin-bottom: 10px; float: left;" width="100%">
                            <tr>
                                <td>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td style="width: 70%">
                                                    <span id="main_RepList_lblProductName_6" style="color:Orange;font-size:16px;font-weight:bold;margin-bottom: 20px;">肿瘤标志检测</span><br />
                                                </td>
                                                <td style="width: 30%; text-align: right; font-size:20px; font-weight:bold; color:orange; ">
                                                    120.00元
                                                    
                                                    
                                                    <input type="hidden" name="ctl00$main$RepList$ctl07$hidXPoint" id="main_RepList_hidXPoint_6" value="121.45284" />
                                                    <input type="hidden" name="ctl00$main$RepList$ctl07$hidYPoint" id="main_RepList_hidYPoint_6" value="31.241429" />
                                                </td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td rowspan="2" style="line-height:25px;">
                                                    <span id="main_RepList_lblInfo_6"></span>
                                                </td>
                                                <td>

                                                </td>
                                            </tr>
                                            <tr>
                                                
                                                <td style="line-height: 20px; text-align: right; " rowspan="2">
                                                    <input type="submit" name="ctl00$main$RepList$ctl07$btnAddShopCar" value="加入购物车" id="main_RepList_btnAddShopCar_6" class="btn_submit_blue" style="background-color:Orange;" />
                                                    <input type="submit" name="ctl00$main$RepList$ctl07$btnDetail" value="查看详细" id="main_RepList_btnDetail_6" class="btn_submit_blue" />
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 10px;"></td>
                            </tr>
                        </table>
                    
                        <table class="table_dailiList" style="margin-top: 10px; margin-bottom: 10px; float: left;" width="100%">
                            <tr>
                                <td>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td style="width: 70%">
                                                    <span id="main_RepList_lblProductName_7" style="color:Orange;font-size:16px;font-weight:bold;margin-bottom: 20px;">骨密度</span><br />
                                                </td>
                                                <td style="width: 30%; text-align: right; font-size:20px; font-weight:bold; color:orange; ">
                                                    80.00元
                                                    
                                                    
                                                    <input type="hidden" name="ctl00$main$RepList$ctl08$hidXPoint" id="main_RepList_hidXPoint_7" value="121.45284" />
                                                    <input type="hidden" name="ctl00$main$RepList$ctl08$hidYPoint" id="main_RepList_hidYPoint_7" value="31.241429" />
                                                </td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td rowspan="2" style="line-height:25px;">
                                                    <span id="main_RepList_lblInfo_7">诊断骨质疏松，预测骨折危险性</span>
                                                </td>
                                                <td>

                                                </td>
                                            </tr>
                                            <tr>
                                                
                                                <td style="line-height: 20px; text-align: right; " rowspan="2">
                                                    <input type="submit" name="ctl00$main$RepList$ctl08$btnAddShopCar" value="加入购物车" id="main_RepList_btnAddShopCar_7" class="btn_submit_blue" style="background-color:Orange;" />
                                                    <input type="submit" name="ctl00$main$RepList$ctl08$btnDetail" value="查看详细" id="main_RepList_btnDetail_7" class="btn_submit_blue" />
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 10px;"></td>
                            </tr>
                        </table>
                    
                        <table class="table_dailiList" style="margin-top: 10px; margin-bottom: 10px; float: left;" width="100%">
                            <tr>
                                <td>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td style="width: 70%">
                                                    <span id="main_RepList_lblProductName_8" style="color:Orange;font-size:16px;font-weight:bold;margin-bottom: 20px;">测试ABC47</span><br />
                                                </td>
                                                <td style="width: 30%; text-align: right; font-size:20px; font-weight:bold; color:orange; ">
                                                    900.00元
                                                    
                                                    
                                                    <input type="hidden" name="ctl00$main$RepList$ctl09$hidXPoint" id="main_RepList_hidXPoint_8" value="121.45284" />
                                                    <input type="hidden" name="ctl00$main$RepList$ctl09$hidYPoint" id="main_RepList_hidYPoint_8" value="31.241429" />
                                                </td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td rowspan="2" style="line-height:25px;">
                                                    <span id="main_RepList_lblInfo_8"></span>
                                                </td>
                                                <td>

                                                </td>
                                            </tr>
                                            <tr>
                                                
                                                <td style="line-height: 20px; text-align: right; " rowspan="2">
                                                    <input type="submit" name="ctl00$main$RepList$ctl09$btnAddShopCar" value="加入购物车" id="main_RepList_btnAddShopCar_8" class="btn_submit_blue" style="background-color:Orange;" />
                                                    <input type="submit" name="ctl00$main$RepList$ctl09$btnDetail" value="查看详细" id="main_RepList_btnDetail_8" class="btn_submit_blue" />
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 10px;"></td>
                            </tr>
                        </table>
                    
                    
                <br />
                <span id="main_GridViewPager0"><div class="page"><li><a href='javascript:;'>上一页</a></li><li><a  class="page_cut"  href="javascript:__doPostBack('ctl00$main$GridViewPager0','1') " >1</a></li><li><a href='javascript:;'>下一页</a></li></div></span>
            <br />
        </div>
    </div>
    </div>
    
    <div class="overlay">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="ListInfo">
            <tr>
                <td style="text-align: right; font-weight: bold;">我的购物车：
                    <span id="main_lblProductCount">1</span>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="submit" name="ctl00$main$btnCale" value="结算" id="main_btnCale" class="btn_submit_blue" />
                </td>
            </tr>
        </table>
    </div>
</div>





