<div id="searchNav">
        <div id="subSchBox" style="padding-bottom: 10px; background-image: none; background-color: #f0f6ff">
            <table width="100%" border="0" cellspacing="0" cellpadding="0" class="ListInfo" style="float: left;">
                <tr>
                    <td style="width: 50%;">所在地区：
                        <select id="iCityID" name="iCityID" style="width:150px;">
                            <option value="0">选择城市</option>
                            <?php if (!empty($aCitys)) {
                            foreach ($aCitys as $key => $value){ ?>
                                <option value="<?php echo $key ?>"><?php echo $value ?></option>
                            <?php } } ?>
                        </select>
                        <select id="iRegionID" name="iRegionID" style="width:150px;">
                            <option selected="selected" value="0">选择区</option>
                        </select>
                    </td>
                    <td style="width: 30%; padding-right: 20px;">体检机构：
                        <select id="iSupplierID" name="iSupplierID" style="width:150px;">
                            <option selected="selected" value='0'>请选择</option>
                            <?php if (!empty($aSupplier)) {
                                foreach ($aSupplier as $key => $value){ ?>
                                    <option value="<?php echo $key ?>"><?php echo $value ?></option>
                                <?php } } ?>
                        </select>
                    </td>
                </tr>
            </table>
        </div>
        <input type="hidden" id="iProductID" value="<?php echo $iProductID ?>">
</div> 
<div style="width: 100%">
    <div class="mt10">
        <div class="search_con store-item-list clearfix" style="border-top: 1px solid #0D8FE3;">
                
        </div>
    </div>
</div>

<script>
    $(function(){
        var getreginUrl = '<?php echo $sGetRegionUrl; ?>';
        var getstoreUrl = '<?php echo $sGetStoreUrl; ?>';
        var detailUrl = '<?php echo $sDetailUrl.'id/'.$aProduct['sProductCode']; ?>';
        var storeUrl = '<?php echo $sStoreDetailUrl; ?>';
        change();

        function citychange()
        {
            var cid = $('#iCityID').find('option:selected').val();
            $('#iRegionID').empty();
            $.post(getreginUrl, {iCityID: cid}, function(ret){
                if (ret.status) {
                    $('#iRegionID').append('<option value="0">全部</option>');
                    $.each(ret.data, function(i,e) {
                        $('#iRegionID').append('<option value="'+e.iRegionID+'">'+e.sRegionName+'</option>');
                    });
                    change();
                    return false;
                }else {
                    alert('请求数据失败!');
                }
            }, 'json');
        }

        function change()
        {
            var cid = $('#iCityID').find('option:selected').val();
            var rid = $('#iRegionID').find('option:selected').val();
            var sid = $('#iSupplierID').find('option:selected').val();
            var pid = $('#iProductID').val();
            $.post(getstoreUrl, {iCityID: cid,iRegionID:rid,iSupplierID:sid,iProductID:pid}, function(ret){
                if (ret.status) {
                    if (ret.data.aList) {
                        var html = '';
                        $('.store-item-list').html('');
                        $.each(ret.data.aList, function(i,e) {
                            html += '<table class="table_dailiList" style="margin-top: 10px; margin-bottom: 10px; float: left;" width="100%"><tr><td><table><thead><tr><td style="width: 70%">'+
                                '<a id="" href="javascript::void(0)" style="color: #0D8FE3; text-decoration: none;"><span id="" style="font-size:16px;">'+e.detail.sName+'</span>'+
                                    '<span class="font_gray">/'+e.detail.sCityName+'/'+e.detail.sRegionName+'</span></a><a id="main_RepList_lnkMap_0" onclick="ShowMap(\''+e.detail.sName+'\','+e.detail.iX+', '+ e.detail.iY +')"><img src="<?php echo $sStaticRoot?>/backend/img/dw.gif" alt="" />查看地图</a></td><td style="width: 30%; text-align: right; font-size: 20px; font-weight: bold; color: orange;">'+
                                        '<input type="hidden" name="" id="main_RepList_hidXPoint_0" value="" /><input type="hidden" name="" id="main_RepList_hidYPoint_0" value="" /></td></tr></thead><tbody><tr><td style="line-height: 20px;">具体地址：'+e.detail.sAddress+'</td><td style="line-height: 20px; text-align: right;" rowspan="2"></td></tr><tr><td style="line-height: 20px;">联系电话：'+e.detail.sTel+'</td></tr><tr><td colspan="2" style="line-height: 20px;">营业时间：'+e.detail.sWorktime+'</td></tr></tbody></table></td></tr><tr><td style="height: 10px;"></td></tr></table>  ';
                        });
                        $('.store-item-list').append(html);
                    }
                    return false;
                }else {
                    alert('请求数据失败!');
                }
            }, 'json');
        }

        $('#iCityID').on('change',function(){
            citychange();
        });

        $('#iRegionID').on('change',function(){
            change();
        });

        $('#iSupplierID').on('change',function(){
            change();
        });

        $('.store-menu').on('click',function(){
            window.location.href = detailUrl;
        });
    })
</script>
