<div class="pheader clearfix"><?php echo isset($aLevel['iAutoID'])?'编辑':'增加'?>职级</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <input name="iDeptID" type="hidden" value="<?php echo isset($aLevel['iAutoID']) ? $aLevel['iAutoID'] : ''?>">

		<div class="form-group col-sm-9">
			<label for="sLevelName" class="col-sm-3 control-label"> <span class="tubiao">*</span>职级名称：</label>
			<div class="col-sm-9">
				<input name="sLevelName" validate="!clength:1-20" placeholder="请输入职级名称" type="text" value="<?php echo isset($aLevel['sLevelName']) ? $aLevel['sLevelName'] : ''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>

		<div class="form-group col-sm-9">
			<label for="sRemark" class="col-sm-3 control-label">排序：</label>
			<div class="col-sm-9">
				<input name="iRank" validate="!clength:0-20" type="text" value="<?php echo isset($aLevel['iRank']) ? $aLevel['iRank'] : ''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>			
		</div>

    	<div class="form-groupbtn-toolbar text-center col-sm-9">
        	<button id="save" class="btn btn-primary">保存</button>
        	<button id="cancel"class="btn" onclick="location.href='/company/level?>';return false;">取消</button>
        </div>
    </form>
</div>

<script type="text/javascript">
$(function() {
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	           location.href = '/company/level';
	        }
	    }, 'json');
		return false;
	}});
});
</script>