<div class="pheader clearfix"><?php echo isset($aDept['iAutoID'])?'编辑':'增加'?>公司架构</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <input name="iDeptID" type="hidden" value="<?php echo isset($aDept['iAutoID']) ? $aDept['iAutoID'] : ''?>">
            <div class="form-group col-sm-9">
                <label for="iParentID" class="col-sm-3 control-label">上级机构：</label>
                <div class="col-sm-9">
                    <select name="iParentID" class="form-control input-validate" <?php echo $selectable; ?>>
                        <?php if(empty($aDept['iParentID'])) { ?>
                        <option value="0" <?php echo $aDept['iParentID'] == 0 ? 'selected' : ''?>>--</option>
                        <?php }?>					
                        <?php foreach ($aDeptSet as $k => $v) { ?>
                        <option value="<?php echo $k?>" <?php echo isset($aDept['iParentID']) && $aDept['iParentID'] == $k ? 'selected' : ''?>><?php echo $v?></option>
                        <?php }?>
                    </select>
                </div>
            </div>	
            <div class="form-group col-sm-9">
                <label for="sNumber" class="col-sm-3 control-label"> <span class="tubiao">*</span>机构编号：</label>
                <div class="col-sm-9">
                    <input name="sNumber" validate="!clength:1-20" placeholder="请输入机构编号" type="text" value="<?php echo isset($aDept['sNumber']) ? $aDept['sNumber'] : ''?>" class="form-control input-validate" <?php echo $readable; ?>>
                    <span class="validate_checktip"></span>
                </div>
            </div>
        
           <div class="form-group col-sm-9">
                <label for="sDeptName" class="col-sm-3 control-label"> <span class="tubiao">*</span>机构名称：</label>
                <div class="col-sm-9">
                    <input name="sDeptName" validate="!clength:1-20" placeholder="请输入机构名称" type="text" value="<?php echo isset($aDept['sDeptName']) ? $aDept['sDeptName'] : ''?>" class="form-control input-validate" <?php echo $readable; ?>>
                    <span class="validate_checktip"></span>
                </div>
            </div>
            <div class="form-group col-sm-9">
                <label for="sDeptName" class="col-sm-3 control-label"> 负责人：</label>
                <div class="col-sm-9">
                    <input name="sCharger" placeholder="请输入负责人" type="text" value="<?php echo isset($aDept['sCharger']) ? $aDept['sCharger'] : ''?>" class="form-control input-validate" <?php echo $readable; ?>>                    
                </div>
            </div>
            <div class="form-group col-sm-9">
                <label for="sPhone" class="col-sm-3 control-label"> 电话：</label>
                <div class="col-sm-9">
                    <input name="sPhone"  placeholder="请输入机构电话" type="text" value="<?php echo isset($aDept['sPhone']) ? $aDept['sPhone'] : ''?>" class="form-control input-validate" <?php echo $readable; ?>>                    
                </div>
            </div>
            
            <div class="form-group col-sm-9">
                <label for="sMobile" class="col-sm-3 control-label">手机：</label>
                <div class="col-sm-9">
                    <input name="sMobile"  placeholder="请输入手机" type="text" value="<?php echo isset($aDept['sMobile']) ? $aDept['sMobile'] : ''?>" class="form-control input-validate" <?php echo $readable; ?>>                    
                </div>
            </div>
        
            <div class="form-group col-sm-9">
                <label for="sPostNumber" class="col-sm-3 control-label"> 邮编：</label>
                <div class="col-sm-9">
                    <input name="sPostNumber"  placeholder="请输入邮编" type="text" value="<?php echo isset($aDept['sPostNumber']) ? $aDept['sPostNumber'] : ''?>" class="form-control input-validate" <?php echo $readable; ?>>
                </div>
            </div>
            
            <div class="form-group col-sm-9">
                <label for="sMail" class="col-sm-3 control-label"> 邮箱：</label>
                <div class="col-sm-9">
                    <input name="sMail" placeholder="请输入邮箱" type="text" value="<?php echo isset($aDept['sMail']) ? $aDept['sMail'] : ''?>" class="form-control input-validate" <?php echo $readable; ?>>
                </div>
            </div>
        
            <div class="form-group col-sm-9">
                <label for="sFax" class="col-sm-3 control-label"> 传真：</label>
                <div class="col-sm-9">
                    <input name="sFax"  placeholder="请输入传真" type="text" value="<?php echo isset($aDept['sFax']) ? $aDept['sFax'] : ''?>" class="form-control input-validate" <?php echo $readable; ?>>
                </div>
            </div>
            
            <div class="form-group col-sm-9">
                <label for="sAddress" class="col-sm-3 control-label"> 地址：</label>
                <div class="col-sm-9">
                    <input name="sAddress" placeholder="请输入地址" type="text" value="<?php echo isset($aDept['sAddress']) ? $aDept['sAddress'] : ''?>" class="form-control input-validate" <?php echo $readable; ?>>
                </div>
            </div>
            
            <div class="form-group col-sm-9">
                <label for="sPhotoAddress" class="col-sm-3 control-label"> 影像件地址：</label>
                <div class="col-sm-9">
                    <input name="sPhotoAddress"  placeholder="请输入影像件地址" type="text" value="<?php echo isset($aDept['sPhotoAddress']) ? $aDept['sPhotoAddress'] : ''?>" class="form-control input-validate" <?php echo $readable; ?>>
                </div>
            </div>
        
            <div class="form-group col-sm-9">
                <label for="sPhotoUrl" class="col-sm-3 control-label"> 影像件域名：</label>
                <div class="col-sm-9">
                    <input name="sPhotoUrl" placeholder="请输入影像件域名" type="text" value="<?php echo isset($aDept['sPhotoUrl']) ? $aDept['sPhotoUrl'] : ''?>" class="form-control input-validate" <?php echo $readable; ?>>
                </div>
            </div>
            

            <div class="form-group col-sm-9">
                <label for="sRemark" class="col-sm-3 control-label"> 备注：</label>
                <div class="col-sm-9">
                    <textarea name="sRemark" class="form-control input-validate"><?php echo isset($aDept['sRemark']) 
                            ? $aDept['sRemark'] : ''?></textarea>
                </div>
            </div>

    	<div class="form-groupbtn-toolbar text-center col-sm-9">
            <button id="save" class="btn btn-primary">保存</button>
            <button id="cancel"class="btn" onclick="location.href='<?php echo $sDeptUrl . '/iDeptID/' . $aDept['iAutoID']?>';return false;">取消</button>
        </div>
    </form>
</div>

<script type="text/javascript">
$(function() {
    $("#myform").validate({submitHandler: function(form) {
        $.post(form.action, $(form).serialize(), function(ret){
            alert(ret.data);
            if (ret.status) {
               location.href = '<?php echo $sDeptUrl . '/iDeptID/' . $aDept['iAutoID']?>';
            }
        }, 'json');
            return false;
    }});
});
</script>