<div class="pheader clearfix"><?php echo isset($aUser['iUserID']) ? '编辑' : '增加' ?>员工信息</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <input name="iUserID" type="hidden" value="<?php echo !empty($aUser['iUserID']) ? $aUser['iUserID'] : '' ?>">
        <div class="form-group">
            <label for="sUserName" class="col-sm-2 control-label"> 员工编号：</label>
            <div class="col-sm-10">
                <input name="sUserName" type="text" disabled="disabled" value="<?php echo isset($aUser['sUserName'])?$aUser['sUserName']:'自动生成'?>" class="form-control input-validate">
            </div>
        </div>

        <div class="form-group">
            <label for="sMobile" class="col-sm-2 control-label"> <span class="tubiao">*</span>员工姓名：</label>

            <div class="col-sm-10">
                <input name="sRealName" validate="!clength:1-10" placeholder="请输入员工姓名" type="text"
                       value="<?php echo !empty($aUser['sRealName']) ? $aUser['sRealName'] : '' ?>"
                       class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group">
            <label for="iLevel" class="col-sm-2 control-label">性别：</label>

            <div class="col-sm-10">
                <select name="iSex" class="form-control input-validate">
                    <?php foreach ($aSex as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aUser['iSex']) && $aUser['iSex'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="sMobile" class="col-sm-2 control-label"> <span class="tubiao">*</span>身份证：</label>

            <div class="col-sm-10">
                <input name="sIdentityCard" validate="!required:true" placeholder="请输入员工身份证" type="text"
                       value="<?php echo !empty($aUser['sIdentityCard']) ? $aUser['sIdentityCard'] : '' ?>"
                       class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group">
            <label for="iLevel" class="col-sm-2 control-label">部门：</label>

            <div class="col-sm-10">
                <select name="iDeptID" class="form-control input-validate">
                    <?php foreach ($aDepartment as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aUser['iDeptID']) && $aUser['iDeptID'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="iLevel" class="col-sm-2 control-label">职级：</label>

            <div class="col-sm-10">
                <select name="iJobGradeID" class="form-control input-validate">
                    <?php foreach ($aLevel as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aUser['iJobGradeID']) && $aUser['iJobGradeID'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="sJobTitleName" class="col-sm-2 control-label">职位：</label>

            <div class="col-sm-10">
                <input name="sJobTitleName" placeholder="请输入员工职位" type="text"
                       value="<?php echo !empty($aUser['sJobTitleName']) ? $aUser['sJobTitleName'] : '' ?>"
                       class="form-control input-validate">
            </div>
        </div>

        <div class="form-group">
            <label for="sEmail" class="col-sm-2 control-label">公司邮箱：</label>

            <div class="col-sm-10">
                <input name="sEmail" placeholder="请输入员工公司邮箱" type="text"
                       value="<?php echo !empty($aUser['sEmail']) ? $aUser['sEmail'] : '' ?>"
                       class="form-control input-validate">
            </div>
        </div>

        <div class="form-group">
            <label for="sMobile" class="col-sm-2 control-label"> <span class="tubiao">*</span>手机号码：</label>

            <div class="col-sm-10">
                <input name="sMobile" validate="!mobile:true" placeholder="请输入联系人手机号码" type="text"
                       value="<?php echo !empty($aUser['sMobile']) ? $aUser['sMobile'] : '' ?>"
                       class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group">
            <label for="iStatus" class="col-sm-2 control-label">账号状态：</label>

            <div class="col-sm-10">
                <select name="iStatus" class="form-control input-validate">
                    <?php foreach ($aStatus as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aUser['iStatus']) && $aUser['iStatus'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="sRemark" class="col-sm-2 control-label">备注：</label>

            <div class="col-sm-10">
				<textarea name="sRemark" class="form-control input-validate"><?php echo !empty($aUser['sRemark']) ? $aUser['sRemark'] : '' ?></textarea>
            </div>
        </div>

        <div class="btn-toolbar text-center">
            <button id="save" class="btn btn-primary">保存</button>
            <button id="cancel" class="btn" onclick="window.history.back(-1);return false;">返回</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(function () {
        $("#myform").validate({
            submitHandler: function (form) {
                var url = '/admin/user/clientemployee/?id=<?php echo !empty($iUserID)?$iUserID:''?>';
                $.post(form.action, $(form).serialize(), function (ret) {
                    alert(ret.data);
                    if (ret.status) {
                        location.href = url;
                    }
                }, 'json');
                return false;
            }
        });
    });
</script>