<div class="activate_w cf2" style="background: #fff; padding: 4em 0;">
	<dl class="activate_w activate_note">
		<dt>
			<img src="/front/images/tool/icon_tips.png" class="png" alt="ok">
		</dt>
		<dd>
			<h4>付款失败！</h4>
			<p>
				您的订单: <a class="olda"><?php echo $iOrderID?></a>，付款失败<br>
				请重新支付或者电话联系我们的客服 <font color="bule">400- 878-9551</font>
			</p>
			<ul class="cf2">
				<li><h5>你还可以</h5></li>
			</ul>
			<div>
				<a href="/ad/wpay/id/<?php echo $iOrderID?>.html" class="red_btn_t">重新支付</a>
				<a href="/ad/add.html" class="gray_btn">重新下单</a>
			</div>
		</dd>
	</dl>
</div>