<div class="pheader clearfix"><?php echo isset($aCommunicate['iID']) ? '编辑' : '增加' ?>沟通记录</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <input name="iID" type="hidden" value="<?php echo isset($aCommunicate['iID']) ? $aCommunicate['iID'] : '' ?>">

        <div class="form-group">
            <label for="iTime" class="col-sm-2 control-label"> <span class="tubiao">*</span>沟通日期：</label>

            <div class="col-sm-10">
                <input name="iTime" validate="!datetime:true" placeholder="请选择沟通日期" type="text"
                       value="<?php echo !empty($aCommunicate['iTime']) ? date('Y-m-d H:i:s', $aCommunicate['iTime']) : '' ?>"
                       class="form-control input-validate laydatetime">
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group">
            <label for="sContent" class="col-sm-2 control-label"> <span class="tubiao">*</span>沟通内容：</label>

            <div class="col-sm-10">
				<textarea name="sContent" validate="!clength:1-2000" class="form-control input-validate"><?php echo !empty($aCommunicate['sContent']) ? $aCommunicate['sContent'] : '' ?></textarea>
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group">
            <label for="sRealName" class="col-sm-2 control-label"> <span class="tubiao">*</span>联系人：</label>

            <div class="col-sm-10">
                <input name="sRealName" validate="!clength:1-10" placeholder="请输入联系人姓名" type="text"
                       value="<?php echo !empty($aCommunicate['sRealName']) ? $aCommunicate['sRealName'] : '' ?>"
                       class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group">
            <label for="sMobile" class="col-sm-2 control-label"> <span class="tubiao">*</span>联系电话：</label>

            <div class="col-sm-10">
                <input name="sMobile" validate="!mobile:true" placeholder="请输入联系人手机号码" type="text"
                       value="<?php echo !empty($aCommunicate['sMobile']) ? $aCommunicate['sMobile'] : '' ?>"
                       class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group">
            <label for="iLevel" class="col-sm-2 control-label">重程度要：</label>

            <div class="col-sm-10">
                <select name="iLevel" class="form-control input-validate">
                    <?php foreach ($aCommunicateLevel as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aCommunicate['iLevel']) && $aCommunicate['iLevel'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="iResult" class="col-sm-2 control-label">沟通结果：</label>

            <div class="col-sm-10">
                <select name="iResult" class="form-control input-validate">
                    <?php foreach ($aCommunicateResult as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aCommunicate['iResult']) && $aCommunicate['iResult'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>

        <div class="btn-toolbar text-center">
            <input type="hidden" name="iUserID" value="<?php echo !empty($iUserID) ? $iUserID : '' ?>">
            <button id="save" class="btn btn-primary">保存</button>
            <button id="cancel" class="btn" onclick="window.history.back(-1);return false;">返回</button>
        </div>
    </form>
</div>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/laydate/laydate.js"></script>
<script type="text/javascript">
    $(function () {
        $("#myform").validate({
            submitHandler: function (form) {
                var url = '/admin/user/communicate/?id=<?php echo isset($iUserID)?$iUserID:''?>';
                $.post(form.action, $(form).serialize(), function (ret) {
                    alert(ret.data);
                    if (ret.status) {
                        location.href = url;
                    }
                }, 'json');
                return false;
            }
        });
    });
</script>