<div class="main-content">

    <div class="container" style="padding-top:60px;">
        <div>
            <p style="font-size:18px; font-weight:bold;">
                中盈简介
            </p>
    <span class="float_l" style="font-size: 15px; line-height: 25px;">
        &nbsp;&nbsp;&nbsp;&nbsp;上海中盈保险经纪有限公司的主要股东是中国国际技术智力合作公司（上海分公司）。中智是唯一一家经国务院批准，可以在全国各省市直接设立机构进行作业的全国性人力资源专业服务公司。中盈也是中智旗下唯一的一家保险经纪公司。<br>
        <br>
        &nbsp;&nbsp;&nbsp;&nbsp;中盈保险经纪有限公司 总部设立于上海，并已在北京、江苏等一线省市开设了分支机构。同时逐步建立以国内主要中心城市为依托、向境外辐射的主导市场。我们以专业和诚信为广大客户提供最佳的保险方案与优质的服务。致力于将公司发展成为具备全球经营能力的综合性保险经纪公司。<br>
        <br>
        &nbsp;&nbsp;&nbsp;&nbsp;上海中盈保险经纪有限公司原身为成立于2005年6月的上海中盈保险代理有限公司，于2010年在中国保监会批准下正式翻牌成为保险经纪公司。我们经过几年的努力，公司取得了长足的进步，积累了众多优质客户。我们的客户遍及房地产及金融业、汽车及零部件制造业、工程建设、物流及运输业、人力资源服务等各个行业。<br>
        <br>
        &nbsp;&nbsp;&nbsp;&nbsp;我们坚守“诚信第一，客户至上”的理念，为客户提供一流水准的服务，并通过合作求得共赢。
    </span>
        </div>
        <div>
            <p style="font-size:18px; font-weight:bold;">
                我们的优势
            </p>
    <span class="float_l" style="font-size: 15px; line-height: 25px;">
        &nbsp;&nbsp;&nbsp;&nbsp;在于丰富的经验以及专业化的服务。上海中盈保险经纪有限公司由技术全面、经验丰富、诚信敬业的团队组成，可以胜任为客户提供风险管理、保险安排、理赔管理等一揽子服务。我们注重服务效率，可对客户的要求做出快速反应，以此协助客户制定最佳保险方案。<br>
        <br>
        &nbsp;&nbsp;&nbsp;&nbsp;1. 我们的财产险和寿险健康险专业化服务团队，可以为您提供包括风险勘查、方案设计、投保安排、日常服务、理赔在内的各种专业化服务。
        <br>
        <br>
        &nbsp;&nbsp;&nbsp;&nbsp;2. 我们的高效健康险服务平台，我们根据市场需求并集合多年保险服务经验自行开发了一套基于工作流引擎和规则引擎的医疗理赔系统--智盈通。可以极大缩短医疗索赔的时效，切实保障了客户的利益。同时，服务团队中的专业全科医生、护士以及拥有多年理赔经验的理赔员协同配合，充分发挥各自优势，从而能够为您提供良好的服务。<br>
        <br>
        &nbsp;&nbsp;&nbsp;&nbsp;3. 我们与国内外保险公司都有广泛的合作，您可以获得最好的保险条件和价格。
        <br>
        <br>
        &nbsp;&nbsp;&nbsp;&nbsp;4. 我们与知名大学和研究机构建立有长期良好合作关系，在专业领域可以获得所需外部技术支持。这将有助于您提高专业风险管理水平。
    </span>
        </div>
        <div>
            <p style="font-size:18px; font-weight:bold;">
                我们的服务
            </p>
    <span class="float_l" style="font-size: 15px; line-height: 25px;">
        <span style="color: Orange; font-weight: bold;">了解客户需求</span><br>
        悉心听取客户关于自身风险情况的估计及目前保险现状，了解客户需求。在收到客户授权后，我们开展进一步工作。<br>
        <br>
        <span style="color: Orange; font-weight: bold;">风险勘察</span><br>
        可派遣专业人员替客户就项目进行风险勘查，提供改善风险的可行方法，减低出险的机会。如果项目的风险得到改善，将有助于保险公司商谈承保条件。<br>
        <br>
        <span style="color: Orange; font-weight: bold;">风险评估与分析</span><br>
        通过实地勘察与走访了解客户所面临的风险，协助客户鉴别和衡量风险的性质和程度，就风险的评估、确定、自留、转移等，向客户提供专业化的意见。<br>
        <br>
        <span style="color: Orange; font-weight: bold;">保险方案设计</span><br>
        根据客户项目的特点，为客户量身设计合适的保险方案，并征得保险公司认可，从而实行合理可行的保障范围，为客户争取更佳的保障。<br>
        <br>
        <span style="color: Orange; font-weight: bold;">询价与比较报价</span><br>
        要求保险公司根据设计的方案提供报价以便做出比较。在得到保险公司的报价后，就各家保险公司的承保条件，服务质量等提供专业建议，协助客户选择保险公司。<br>
        <br>
        <span style="color: Orange; font-weight: bold;">投保安排</span><br>
        根据客户的选择向选定的保险公司投保，并代为办理投保所需的一切手续。在投保后，协助保险公司准备相关文件以确保保单的内容达到客户的要求。收到保险公司出具的保险单后，帮助客户审核保单。<br>
        <br>
        <span style="color: Orange; font-weight: bold;">保险咨询</span><br>
        在保险期间，如客户对保险事宜有咨询需求，我们将及时提供服务。此外，我们将密切关注保险市场的变化，必要时，我们会马上告知客户，并为客户做出分析判断。<br>
        <br>
        <span style="color: Orange; font-weight: bold;">索赔处理</span><br>
        在保单生效后，我们将告知客户有关索赔程序，根据客户要求，制作保单摘要并提供索赔程序手册或员工福利手册。在索赔出现时，将协助客户办理索赔，跟进赔案处理进程并监督保险公司及时完成；应客户要求参与索赔谈判，以帮助客户争取公平合理的赔偿。<br>
        <br>
        <span style="color: Orange; font-weight: bold;">保险回顾</span><br>
        阶段性地回顾客户的保险计划与保险执行情况，跟踪保险公司服务承诺的履行，对客户风险状况的变化提出相应的改进意见等。<br>
        <br>
    </span>
        </div>
        <div>
            <p style="font-size:18px; font-weight:bold;">
                联系我们
            </p>
    <span class="float_l" style="font-size: 15px; line-height: 25px;">
        上海总公司联系地址：上海市徐汇区衡山路922号建汇大厦30楼 <br>
        联系电话：400 816 6768 或 021-64078781 <br>
        传真电话：021-54510291
    </span>
        </div>

    </div>
</div>