<div class="row row-main-margin">
<table cellpadding="0" cellspacing="0" border="0" width="100%">
    <tbody><tr>
        <td style="width: 25%">
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r16_c8.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td style="width: 25%">
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r15_c6.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td style="width: 25%">
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r15_c4.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td style="width: 25%">
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r15_c2.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
    </tr>
    <tr>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r12_c8.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r12_c6.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r12_c2.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r11_c4.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
    </tr>
    <tr>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r7_c4.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r7_c2.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r6_c8.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r5_c6.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
    </tr>
    <tr>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r2_c8.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r2_c6.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r2_c4.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/hzbxgs_r2_c2.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
    </tr>
    <tr>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/meinian.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/ciming.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
            <img class="img-responsive" src="<?php echo $sStaticRoot ?>/backend/img/aikang.jpg" alt="0" style="border:1px solid #CCCCCC; ">
        </td>
        <td>
        </td>
    </tr>
    </tbody></table>
</div>