<div class="row <?php echo empty($hassnotoremenu) ? 'row-main-margin' : '';?>">
    <?php if (empty($hassnotoremenu)){
        ?>
        <div class="store-menu">
            <div class="store-menu-title">
                <?php echo !empty($aProduct['sProductName']) ? !empty($aProduct['sAlias']) ? $aProduct['sAlias'] : $aProduct['sProductName'] : '' ?>
            </div>
            <div class="store-menu-price">
                <i class="fa fa-cny"></i><span class="red"><?php echo !empty($aProduct['iPrice']) ? $aProduct['iPrice'] : '' ?></span>元
            </div>
            <div class="pointer">
                <i class="fa fa-chevron-right"></i>
            </div>
        </div>
    <?php
    } ?>
    <div class="store-content">
        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">门店所在地区：</label>
            <div class="col-xs-3 store-select-div">
                <select id="iCityID" name="iCityID" class="form-control input-validate store-select">
                    <option value="0" selected="">请选择</option>
                    <?php if (!empty($aCitys)) {
                        foreach ($aCitys as $key => $value){
                            ?>
                            <option value="<?php echo $key ?>"><?php echo $value ?></option>
                    <?php
                        }
                    } ?>
                </select>
            </div>

            <div class="col-xs-3 store-select-div">
                <select id="iRegionID" name="iRegionID" class="form-control input-validate store-select">
                    <option value="0">全部</option>
                </select>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">所属体检品牌：</label>

            <div class="col-xs-7 store-select-div">
                <select id="iSupplierID" name="iRegionID" class="form-control input-validate store-select">
                    <option value="0">全部</option>
                    <?php if (!empty($aSupplier)) {
                        foreach ($aSupplier as $key => $value){
                            ?>
                            <option value="<?php echo $key ?>"><?php echo $value ?></option>
                        <?php
                        }
                    } ?>
                </select>
            </div>
        </div>
        <div class="border-bottom1"></div>
        <div class="store-item-list"  id="store-item-list">
        </div>
    </div>
<input type="hidden" id="iProductID" value="<?php echo $iProductID ?>">
<?php if (empty($iCartBur)){
    ?>
    <nav class="navbar navbar-fixed-bottom">
        <div class="container-fluid text-center clearfix navbar-white">
            <a id="buybtn" class="btn btn-warning navbar-btn col-xs-4 col-xs-offset-1 active" href="javascript:;"
               role="button">
                <i class="fa fa-rmb fa-lg"></i> <?php echo !empty($aCommonLang[34]) ? $aCommonLang[34] : '' ?></a>
            <a id="cartbtn" class="btn btn-default navbar-btn col-xs-4 col-xs-offset-1 active" href="javascript:;"
               role="button">
                <i class="fa fa-shopping-cart fa-lg"></i> <?php echo !empty($aCommonLang[35]) ? $aCommonLang[35] : '' ?>
            </a>
        </div>
    </nav>
    <?php
} ?>
</div>
<script>
    var listObj={
        pagenumber:1,
        initList:function(){
            var _this=this;
            commonObj.moreUrl =  '<?php echo $sGetStoreUrl; ?>';//设置下拉分页url
            commonObj.appendId="store-item-list";//设置下拉分页外层id
            var cid = $('#iCityID').find('option:selected').val();
            var rid = $('#iRegionID').find('option:selected').val();
            var sid = $('#iSupplierID').find('option:selected').val();
            var pid = $('#iProductID').val();
            //下滑分页数据
            commonObj.pageData={page:listObj.pagenumber,iCityID: cid,iRegionID:rid,iSupplierID:sid,iProductID:pid,t:true};
            //下滑分页回调函数
            commonObj.searchCallBack=function(res){
                $(".loaddiv").hide();
                var dataLength=res.data.aList.length;
                if(dataLength>0){
                    listObj.pagenumber++;
                    commonObj.ajaxstatus=true;
                    commonObj.pageData.page=listObj.pagenumber;
                    var htmlArray=[];
                        $.each(res.data.aList, function(i,e) {
                            var star = _this.initStar(e.detail.sLevel);
                            htmlArray[i]= '<div class="store-item">'+
                            '<div class="store-item-title">'+e.detail.sName+'</div>'+
                            '<div class="store-item-city">('+e.detail.sCityName+'/'+e.detail.sRegionName+')</div>'+star+
                            '<div><span class="store-item-label">网点地址：</span>'+e.detail.sAddress+'</div>'+
                            '<div><span class="store-item-label">联系电话：</span>'+e.detail.sTel+'</div>'+
                            '<div><span class="store-item-label">营业时间：</span>'+e.detail.sWorktime+'</div>'+
                            '</div>';
                            //$('#iRegionID').append('<option value="'+e.iRegionID+'">'+e.sRegionName+'</option>');
                        });
                        
                    $("#"+commonObj.appendId).append(htmlArray.join(""));
                }else{
                    commonObj.fenyestatus=false
                }
            }
            if(_this.pagenumber==1){
                _this.change();
                  commonObj.scrollNextPage();
            }else{
                //下滑分页触发
                commonObj.scrollNextPage();
            }


        },
        initStar:function(point){
            var starhtml = '<div class="store-item-level">';
            var starnum = Math.floor(point);
            for (i=0;i<starnum;i++)
            {
                starhtml += '<i class="fa fa-lg fa-star"></i>';
            }
            if (starnum != point) {
                starhtml += '<i class="fa fa-lg fa-star-half-o"></i>';
                starnum += 1;
            }

            for (i=0;i<5-starnum;i++)
            {
                starhtml += '<i class="fa fa-lg fa-star-o"></i>';
            }
            starhtml += '</div>';
            return starhtml;
        },
        change:function(){
            var _this=this;
            var cid = $('#iCityID').find('option:selected').val();
            var rid = $('#iRegionID').find('option:selected').val();
            var sid = $('#iSupplierID').find('option:selected').val();
            var pid = $('#iProductID').val();
            $.post("<?php echo $sGetStoreUrl; ?>", {iCityID: cid,iRegionID:rid,iSupplierID:sid,iProductID:pid}, function(ret){
                if (ret.status) {
                    if (ret.data.aList) {
                        var html = '';
                        $.each(ret.data.aList, function(i,e) {
                            var star = _this.initStar(e.detail.iShopLevel);
                            html += '<div class="store-item">'+
                            '<div class="store-item-title">'+e.detail.sName+'</div>'+
                            '<div class="store-item-city">('+e.detail.sCityName+'/'+e.detail.sRegionName+')</div>'+star+
                            '<div><span class="store-item-label">网点地址：</span>'+e.detail.sAddress+'</div>'+
                            '<div><span class="store-item-label">联系电话：</span>'+e.detail.sTel+'</div>'+
                            '<div><span class="store-item-label">营业时间：</span>'+e.detail.sWorktime+'</div>'+
                            '</div>';
                            //$('#iRegionID').append('<option value="'+e.iRegionID+'">'+e.sRegionName+'</option>');
                        });
                        $('#store-item-list').html(html);
                        _this.pagenumber++;
                        commonObj.ajaxstatus=true;
                        commonObj.pageData.page=_this.pagenumber;
                    }
                    return false;
                }else {
                    alert('请求数据失败!');
                }
            }, 'json'); 
        }
    }
    
    $(function(){
        var getreginUrl = '<?php echo $sGetRegionUrl; ?>';
        var detailUrl = '<?php echo $sDetailUrl.'id/'.$aProduct['sProductCode']; ?>';
       listObj.initList();

        function citychange()
        {
            var cid = $('#iCityID').find('option:selected').val();
            $('#iRegionID').empty();
            $.post(getreginUrl, {iCityID: cid}, function(ret){
                if (ret.status) {
                    $('#iRegionID').append('<option value="0">全部</option>');
                    $.each(ret.data, function(i,e) {
                        $('#iRegionID').append('<option value="'+e.iRegionID+'">'+e.sRegionName+'</option>');
                    });
                    listObj.pagenumber=1;
                    commonObj.ajaxstatus=true;
                    commonObj.pageData.page=listObj.pagenumber;
                     listObj.initList();
                    return false;
                }else {
                    alert('请求数据失败!');
                }
            }, 'json');
        }

        $('#iCityID').on('change',function(){
            citychange();
        });

        $('#iRegionID').on('change',function(){
            listObj.pagenumber=1;
            commonObj.ajaxstatus=true;
            commonObj.pageData.page=listObj.pagenumber;
            listObj.initList();
        });

        $('#iSupplierID').on('change',function(){
            listObj.pagenumber=1;
            commonObj.ajaxstatus=true;
            commonObj.pageData.page=listObj.pagenumber;
             listObj.initList();
        });

        $('.store-menu').on('click',function(){
            window.location.href = detailUrl;
        });

    })
</script>