<style>
    .search-form .form-group {
        margin-bottom: 15px;
    }
</style>
<div class="pheader clearfix">员工列表</div>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="/company/employee/list">
        <div class="row">

            <div class="form-group col-sm-3">
                <label>员工编号：</label>
                <input type="text" value="<?php echo !empty($aParam['sUserName']) ? $aParam['sUserName'] : '' ?>" class="form-control" name="sUserName" style="width: 100px">
            </div>

            <div class="form-group col-sm-3">
                <label>员工职级：</label>
                <select name="iLevelID" class="form-control" style="width: 100px">
                    <option value="0" <?php echo empty($aParam['iLevelID'])  ? 'selected' : '' ?>>全部</option>
                    <?php foreach ($aLevel as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aParam['iLevelID']) && $aParam['iLevelID'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>

            <div class="form-group col-sm-3">
                <label>所属机构：</label>
                <select name="iDeptID" class="form-control" style="width: 100px">
                    <option value="0" <?php echo empty($aParam['iDeptID'])  ? 'selected' : '' ?>>全部</option>
                    <?php foreach ($aDeptSet as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aParam['iDeptID']) && $aParam['iDeptID'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>

            <div class="form-group col-sm-3">
                <label>员工姓名：</label>
                <input type="text" value="<?php echo !empty($aParam['sRealName']) ? $aParam['sRealName'] : '' ?>"
                       class="form-control" name="sRealName" style="width: 100px">
            </div>

            <div class="form-group col-sm-8">
                <label>账号状态：</label>
                <select name="iStatus" class="form-control" style="width: 100px">
                    <option value="0" <?php echo empty($aParam['iStatus'])  ? 'selected' : '' ?>>全部</option>
                    <?php foreach ($aState as $k => $v) { ?>
                        <option value="<?php echo $k ?>" <?php echo isset($aParam['iStatus']) && $aParam['iStatus'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>              
                
                <a class="text-right btn btn-default" href='/company/employee/add'>添加员工</a>
                <a class="text-right btn btn-default" href='/company/excel/importemployee'>导入</a>
                <a class="text-right btn btn-default" href='/company/excel/export'>导出</a>
                <a class="text-right btn btn-default" href='/company/mail/setmultimail'>批量发送账号</a>
                <a id="batch_transfer" class="text-right btn btn-default">批量转移员工</a>
                <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
            </div>
        </div>
    </form>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center"><input id="news_all_check" name="news_all_check" value="" type='checkbox'></th>
            <th class="text-center">员工编号</th>
            <th class="text-center">员工姓名</th>
            <th class="text-center">机构名称</th>
            <th class="text-center">邮箱</th>
            <th class="text-center">联系电话</th>
            <th class="text-center">职级</th>
            <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php if ($aList['iTotal'] > 0) {
            foreach ($aList['aList'] as $key => $aUser) { ?>
                <tr>
                    <td class="text-center"><input type='checkbox' name='news_check_id' 
                    id="news_check_id_<?php echo $aUser['iUserID'];?>" value="<?php echo $aUser['iUserID'];?>"></td>
                    <td class="text-center"><?php echo $aUser['sUserName'] ?></td>
                    <td class="text-center"><?php echo $aUser['sRealName'] ?></td>
                    <td class="text-center"><?php echo $aDeptSet[$aUser['iDeptID']] ?></td>
                    <td class="text-center"><?php echo $aUser['sEmail'] ?></td>
                    <td class="text-center"><?php echo $aUser['sMobile'] ?></td>
                    <td class="text-center"><?php echo $aLevel[$aUser['iJobGradeID']] ?></td>
                    <td class="text-center">
                        <a href="/company/employee/detail?iEmployeeID=<?php echo $aUser['iUserID'] ?>" title="查看详情">查看</a>
                        <a href="/company/mail/setmail?employeeId=<?php echo $aUser['iUserID'] ?>" title="发送账号">发送账号</a>                        
                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
    <?php echo !empty($aList['aPager']) ? $aList['aPager'] : '' ?>
</div>

<input id='ids' value='' type='hidden'/>
<div class='modal fade' id='tModal'>
    <div class='modal-dialog'>
        <div class='modal-content'>
            <div class='modal-body'>
                <form class='form-horizontal'>
                    <div class="form-group col-sm-4">
                        <label>将选中人员转移至：</label>
                        <select id='deptID' name="deptID" class="" style="width: 100px">
                            <?php foreach ($aDeptSet as $k => $v) { ?>
                                <option value="<?php echo $k ?>" ><?php echo $v ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </form>
                <button type='button' class='btn btn-primary' id='tSave'>确定</button>
        </div>
    </div>
</div>

<script>
    $('#batch_transfer').bind('click', {
        msg : '没有选中的员工'        
    }, piliang);

    function piliang(event) {
        var msg = event.data.msg;
        var url = event.data.url;
        var ids = '';

        $("input[name='news_check_id']").each(function() {
            if ($(this).prop('checked')) {
                ids += $(this).val() + ',';
            }
        });
        if (ids == '') {
            alert(msg);
            return false;
        }

        ids = ids.substring(0, ids.length-1);
        $('#ids').val(ids);
        if ($('#ids').val() != '') {
            $('#tModal').modal('show');    
        } else {
            $('#ids').val(ids);
        }        
    }

    $('#tSave').click(function() {
        $.ajax({
            url : '/company/employee/transfer',
            type : 'post',
            data : {
                employeeIds : $('#ids').val(),
                iDeptID : $('#deptID').val()                
            },
            dataType : 'json',
            success : function(ret) {
                alert(ret.data);
                if (ret.status) {
                    window.location.reload();
                }
            }
        });
    });

    $('#news_all_check').click(function() {
        var is_checked = $(this).prop('checked');
        $("input[name='news_check_id']").each(function() {
            $(this).prop('checked', is_checked);
        });
    });

</script>