<div class="pheader clearfix">修改登录邮箱</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <div class="form-group col-sm-9">
            <label for="" class="col-sm-3 control-label">当前邮箱：</label>
            <div class="col-sm-9">
                <span ><?php echo $sMail; ?></span>
            </div>
        </div>

        <div class="form-group col-sm-9">
            <label for="sMail" class="col-sm-3 control-label">新的邮箱：</label>
            <div class="col-sm-9">
                <input name="sMail" type="" value="" class="form-control input-validate">
            </div>
        </div>

        <div class="form-group col-sm-9">
            <label for="sConfirmPwd" class="col-sm-3 control-label">友情提醒：</label>
            <div class="col-sm-9">
                <span>与贵公司有关的提醒消息将发送至此邮箱，请注意查收。</span>
            </div>
        </div>

        <div class="form-groupbtn-toolbar text-center col-sm-9">
            <a href='javascript:void(0)' class='import btn btn-primary'>修改</a>
        </div>

        <div class="modal fade" id="iModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="pheader clearfix">用户密码确认</div>
                    <div class="pbody clearfix form-group col-sm-9">
                        <label for="sPassword" class="col-sm-3 control-label">输入密码：</label>
                        <div class="col-sm-9">
                            <input id='sPassword' name="sPassword" type="password" value="" class="form-control input-validate">
                        </div>
                    </div>
                    <div class="modal-footer">                        
                        <button id="save" class="btn btn-primary">保存</button>
                    </div>
                </div>
            </div>
        </div>
        <input type='hidden' value=2 id="iType" name="iType" />

        <hr/>
        <div class="pbody clearfix" style="margin-top: 220px">是否允许员工接收订单邮件</div>
        <div class="form-group col-sm-9" style="margin-top: 20px">
            <label for="" class="col-sm-3 control-label">是否允许：</label>
                <input type='radio' name='iAllow' value='1'
                <?php echo 1 == $aValue['iAllow'] ? 'checked': '';?>>是</input>
                <input type='radio' name='iAllow' value='2' 
                <?php echo empty($aValue['iAllow']) || 2 == $aValue['iAllow'] ? 'checked': '';?>>否</input>
        </div>

        <div class="form-group col-sm-9">
            <label for="sReceiveMail" class="col-sm-3 control-label">员工订单收件箱：</label>
            <div class="col-sm-9">
                <input name="sReceiveMail" value="<?php echo $aValue['sReceiveMail'];?>" class="form-control input-validate">
            </div>
        </div>

        <div class="form-group col-sm-9">
            <label for="sConfirmPwd" class="col-sm-3 control-label">友情提醒：</label>
            <div class="col-sm-9">
                <span>如果允许员工接收订单邮件，那么系统会把订单邮件发送至员工的个人邮箱，如果不允许，系统将会把订单邮件发送至“员工订单收件箱”的地址。</span>
            </div>
        </div>

        <div class="form-groupbtn-toolbar text-center col-sm-9">
            <button id="save" class="btn btn-primary">保存</button>
        </div>
    </form>


</div>

<script type="text/javascript">
$(function() {
    $('.import').on('click', function() {
        $('#iType').val(1);
        $('#sPassword').val('');
        $('#iModal').modal('show');
    });

    $("#myform").validate({submitHandler: function(form) {
        $.post(form.action, $(form).serialize(), function(ret){
            alert(ret.data);
            if (ret.status) {
                window.location.reload();
            }
        }, 'json');
        return false;
    }});
});
</script>