<div class="row <?php echo empty($hassnotoremenu) ? 'row-main-margin' : ''; ?>">
    <div class="reservestore-content">

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">体检人：</label>

            <div class="col-xs-7 store-select-div">
                <div><?php echo !empty($aUser['sRealName']) ? $aUser['sRealName'] : '' ?></div>
                <div><?php echo !empty($aSex[$aUser['iSex']]) ? $aSex[$aUser['iSex']] : '' ?>
                    <?php echo !empty($aMarriage[$aUser['iMarriage']]) ? '（'.$aMarriage[$aUser['iMarriage']].'）' : '' ?>
                </div>
                <div><?php echo !empty($aUser['sIdentityCard']) ? $aUser['sIdentityCard'] : '' ?></div>
                <div class="detail-pointer">
                    <a href="<?php echo $sUserInfoEditUrl . 'id/' . $aParam['id'].'/pid/'.$aParam['pid'] ?>" class="detail-pointer-herf">查看详情</a>
                    <i class="fa fa-chevron-right"></i>
                </div>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">体检卡号：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aCard['sCardCode']) ? $aCard['sCardCode'] : '' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">有效期：</label>

            <div class="col-xs-7 store-select-div">
                <?php if ((empty($aCard['sStartDate']) ||  $aCard['sStartDate'] == '0000-00-00') && (empty($aCard['sEndDate']) ||  $aCard['sEndDate'] == '0000-00-00')) {
                    ?>
                    无
                <?php
                } else {
                    ?>
                    <?php echo !empty($aCard['sStartDate']) && $aCard['sStartDate'] != '0000-00-00' ? $aCard['sStartDate'] : '-' ?>
                    至<?php echo !empty($aCard['sEndDate']) && $aCard['sEndDate'] != '0000-00-00' ? $aCard['sEndDate'] : '-' ?>
                <?php
                } ?>

            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">个人支付金额：</label>

            <div class="col-xs-7 store-select-div">
                ￥<span class="red"><?php echo !empty($sNeedPrice) ? $sNeedPrice : '0.00' ?></span>元
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">体检套餐：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aUpProduct['sProductName']) ? !empty($aUpProduct['sAlias']) ? $aUpProduct['sAlias'] : $aUpProduct['sProductName'] : '' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">门店所在地区：</label>

            <div class="col-xs-3 store-select-div">
                <select id="iCityID" name="iCityID" class="form-control input-validate store-select">
                    <option value="0" selected="">请选择</option>
                    <?php if (!empty($aCitys)) {
                        foreach ($aCitys as $key => $value) {
                            ?>
                            <option value="<?php echo $key ?>"><?php echo $value ?></option>
                        <?php
                        }
                    } ?>
                </select>
            </div>

            <div class="col-xs-3 store-select-div">
                <select id="iRegionID" name="iRegionID" class="form-control input-validate store-select">
                    <option value="0">全部</option>
                </select>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">所属体检品牌：</label>

            <div class="col-xs-7 store-select-div">
                <select id="iSupplierID" name="iRegionID" class="form-control input-validate store-select">
                    <option value="0">全部</option>
                    <?php if (!empty($aSupplier)) {
                        foreach ($aSupplier as $key => $value) {
                            ?>
                            <option value="<?php echo $key ?>"><?php echo $value ?></option>
                        <?php
                        }
                    } ?>
                </select>
            </div>
        </div>
        <div class="border-bottom1"></div>
<!--
        <div class="store-item-list1">
            <div class="store-item">
                <div class="store-item-title">adad</div>
                <div class="store-item-city">(北京/怀柔)</div>
                <div class="store-item-level"><i class="fa fa-lg fa-star-o"></i><i class="fa fa-lg fa-star-o"></i><i
                        class="fa fa-lg fa-star-o"></i><i class="fa fa-lg fa-star-o"></i><i
                        class="fa fa-lg fa-star-o"></i></div>
                <div><span class="store-item-label">网点地址：</span></div>
                <div><span class="store-item-label">联系电话：</span></div>
                <div><span class="store-item-label">营业时间：</span></div>
                <div class="distance"><span class="distance-label">直线距离</span>：<span>1.8</span>KM</div>
                <div class="reserve-module clearfix">
                    <button type="button" id="add-query" class="btn btn-warning">立即预约</button>
                    <div class="map"><i class="fa fa-2x fa-map-marker"></i><a href="">查看地图</a></div>
                </div>
            </div>
        </div>
        -->
        <div class="store-item-list" id="store-item-list">
        </div>
    </div>
    <input type="hidden" id="iProductID" value="<?php echo !empty($aParam['upid']) ? $aParam['upid'] : $aParam['pid'] ?>">
    <input type="hidden" id="pid" value="<?php echo !empty($aParam['pid']) ? $aParam['pid'] : 0 ?>">
    <input type="hidden" id="upid" value="<?php echo !empty($aParam['upid']) ? $aParam['upid'] : 0 ?>">
    <input type="hidden" id="iChannelType" value="<?php echo !empty($iChannelType) ? $iChannelType : 0 ?>">
</div>
<script>
  var listObj={
        pagenumber:1,
        productid:$('#pid').val(),
        uproductid:$('#upid').val(),
        initList:function(){
            var _this=this;
            commonObj.moreUrl =  '<?php echo $sGetStoreUrl; ?>';//设置下拉分页url
            commonObj.appendId="store-item-list";//设置下拉分页外层id
            var cid = $('#iCityID').find('option:selected').val();
            var rid = $('#iRegionID').find('option:selected').val();
            var sid = $('#iSupplierID').find('option:selected').val();
            var pid = $('#iProductID').val();
            var iChannelType = $('#iChannelType').val();
            //下滑分页数据
            commonObj.pageData={page:listObj.pagenumber,iCityID: cid,iRegionID:rid,iSupplierID:sid,iProductID:pid,iChannelType:iChannelType,t:true};
            //下滑分页回调函数
            commonObj.searchCallBack=function(res){
                $(".loaddiv").hide();
                var dataLength=res.data.aList.length;
                if(dataLength>0){
                    listObj.pagenumber++;
                    commonObj.ajaxstatus=true;
                    commonObj.pageData.page=listObj.pagenumber;
                    var htmlArray=[];
                        $.each(res.data.aList, function (i, e) {
                            var star = _this.initStar(e.detail.iShopLevel);
                            htmlArray [i]= '<div data-lat="'+e.detail.iY+'" data-lng="'+e.detail.iX+'" class="store-item need_distance">' +
                            '<div class="store-item-title">' + e.detail.sName + '</div>' +
                            '<div class="store-item-city">(' + e.detail.sCityName + '/' + e.detail.sRegionName + ')</div>' + star +
                            '<div><span class="store-item-label">网点地址：</span>' + e.detail.sAddress + '</div>' +
                            '<div><span class="store-item-label">联系电话：</span>' + e.detail.sTel + '</div>' +
                            '<div><span class="store-item-label">营业时间：</span>' + e.detail.sWorktime + '</div>' +
                            '<div class="distance"><span class="distance-label">直线距离</span>：<span class="curr_distance">0</span>KM</div>' +
                            '<div class="reserve-module clearfix">' +
                            '<a type="button" href="'+ '<?php echo $sReserveCommitUrl; ?>'+'id/'+  '<?php echo $aParam['id'] ?>' + '/sid/'+e.detail.iStoreID+'/pid/'+_this.productid+'/upid/'+_this.uproductid+'" class="btn btn-warning">立即预约</a>' +
                            '<div class="map"><i class="fa fa-2x fa-map-marker"></i><a href="'+'<?php echo $sMapUrl ?>'+'id/'+ e.detail.iStoreID+'">查看地图</a> </div>' +
                            '</div>' +
                            '</div>';
                            //$('#iRegionID').append('<option value="'+e.iRegionID+'">'+e.sRegionName+'</option>');
                        });
                        
                    $("#"+commonObj.appendId).append(htmlArray.join(""));
                }else{
                    commonObj.fenyestatus=false
                }
            }
            if(_this.pagenumber==1){
                _this.change();
                  commonObj.scrollNextPage();
            }else{
                //下滑分页触发
                commonObj.scrollNextPage();
            }
        },
        initStar:function(point){
            var starhtml = '<div class="store-item-level">';
            var starnum = Math.floor(point);
            for (i=0;i<starnum;i++)
            {
                starhtml += '<i class="fa fa-lg fa-star"></i>';
            }
            if (starnum != point) {
                starhtml += '<i class="fa fa-lg fa-star-half-o"></i>';
                starnum += 1;
            }

            for (i=0;i<5-starnum;i++)
            {
                starhtml += '<i class="fa fa-lg fa-star-o"></i>';
            }
            starhtml += '</div>';
            return starhtml;
        },
        change:function(){
            var _this=this;
            var cid = $('#iCityID').find('option:selected').val();
            var rid = $('#iRegionID').find('option:selected').val();
            var sid = $('#iSupplierID').find('option:selected').val();
            var pid = $('#iProductID').val();
            var iChannelType = $('#iChannelType').val();
            $.post('<?php echo $sGetStoreUrl; ?>', {iCityID: cid, iRegionID: rid, iSupplierID: sid, iProductID: pid,iChannelType:iChannelType}, function (ret) {
                if (ret.status) {
                    if (ret.data.aList) {
                        var html = '';
                        $.each(ret.data.aList, function (i, e) {
                            var star = _this.initStar(e.detail.iShopLevel);
                            html += '<div data-lat="'+e.detail.iY+'" data-lng="'+e.detail.iX+'" class="store-item need_distance">' +
                            '<div class="store-item-title">' + e.detail.sName + '</div>' +
                            '<div class="store-item-city">(' + e.detail.sCityName + '/' + e.detail.sRegionName + ')</div>' + star +
                            '<div><span class="store-item-label">网点地址：</span>' + e.detail.sAddress + '</div>' +
                            '<div><span class="store-item-label">联系电话：</span>' + e.detail.sTel + '</div>' +
                            '<div><span class="store-item-label">营业时间：</span>' + e.detail.sWorktime + '</div>' +
                            '<div class="distance"><span class="distance-label">直线距离</span>：<span class="curr_distance">0</span>KM</div>' +
                            '<div class="reserve-module clearfix">' +
                            '<a type="button" href="'+ '<?php echo $sReserveCommitUrl; ?>'+'id/'+  '<?php echo $aParam['id'] ?>' + '/sid/'+e.detail.iStoreID+'/pid/'+_this.productid+'/upid/'+_this.uproductid+'" class="btn btn-warning">立即预约</a>' +
                            '<div class="map"><i class="fa fa-2x fa-map-marker"></i><a href="'+'<?php echo $sMapUrl ?>'+'id/'+ e.detail.iStoreID+'">查看地图</a> </div>' +
                            '</div>' +
                            '</div>';
                            //$('#iRegionID').append('<option value="'+e.iRegionID+'">'+e.sRegionName+'</option>');
                        });
                        $('.store-item-list').html(html);
                        _this.pagenumber++;
                        commonObj.ajaxstatus=true;
                        commonObj.pageData.page=_this.pagenumber;
                        getNeedDistance();
                    }
                    return false;
                } else {
                    alert('请求数据失败!');
                }
            }, 'json');
        }
    }
    
    $(function () {
        var getreginUrl = '<?php echo $sGetRegionUrl; ?>';
        var detailUrl = '<?php echo $sDetailUrl.'id/'.$aProduct['sProductCode']; ?>';
        listObj.initList();

        function citychange() {
            var cid = $('#iCityID').find('option:selected').val();
            $('#iRegionID').empty();
            $.post(getreginUrl, {iCityID: cid}, function (ret) {
                if (ret.status) {
                    $('#iRegionID').append('<option value="0">全部</option>');
                    $.each(ret.data, function (i, e) {
                        $('#iRegionID').append('<option value="' + e.iRegionID + '">' + e.sRegionName + '</option>');
                    });
                    listObj.pagenumber=1;
                    commonObj.ajaxstatus=true;
                    commonObj.pageData.page=listObj.pagenumber;
                     listObj.initList();
                    return false;
                } else {
                    alert('请求数据失败!');
                }
            }, 'json');
        }

        $('#iCityID').on('change', function () {
            citychange();
        });

        $('#iRegionID').on('change', function () {
            listObj.pagenumber=1;
            commonObj.ajaxstatus=true;
            commonObj.pageData.page=listObj.pagenumber;
            listObj.initList();
        });

        $('#iSupplierID').on('change', function () {
            listObj.pagenumber=1;
            commonObj.ajaxstatus=true;
            commonObj.pageData.page=listObj.pagenumber;
            listObj.initList();
        });

        $('.store-menu').on('click', function () {
            window.location.href = detailUrl;
        });
    })
</script>