<div class="row <?php echo empty($hassnotoremenu) ? 'row-main-margin' : ''; ?>">
    <div class="reservestore-content">

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">体检套餐：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aProduct['sProductName']) ? !empty($aProduct['sAlias']) ? $aProduct['sAlias'] : $aProduct['sProductName'] : '' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">体检机构：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aStore['sName']) ? $aStore['sName'] : '' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">具体地址：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aStore['sAddress']) ? $aStore['sAddress'] : '' ?>
            </div>
        </div>

        <div class="border-bottom2"></div>

        <div class="form-group clearfix" style="margin-top: 20px;">
            <label for="iProductType" class="col-xs-4 control-label">体检人姓名：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aUser['sRealName']) ? $aUser['sRealName'] : '' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">性别：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aSex[$aUser['iSex']]) ? $aSex[$aUser['iSex']] : '性别未知' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">婚姻状况：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aMarriage[$aUser['iMarriage']]) ? $aMarriage[$aUser['iMarriage']] : '婚姻状况未知' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">身份证号：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aUser['sIdentityCard']) ? $aUser['sIdentityCard'] : '' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">生日：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aUser['sBirthDate']) ? $aUser['sBirthDate'] : '' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">手机：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aUser['sMobile']) ? $aUser['sMobile'] : '' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">邮箱：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aUser['sEmail']) ? $aUser['sEmail'] : '' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">体检预约日期：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo !empty($aCardProduct['iOrderTime']) ? date('Y-m-d', $aCardProduct['iOrderTime']) . '(周' . $aWeekarray[date('w', $aCardProduct['iOrderTime'])] . ')' : '' ?>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">书面报告领取：</label>

            <div class="col-xs-7 store-select-div">
                <?php echo $aCard['iGetReportType'] == 0 ? '自取（体检报告出具后，请带好参检者身份证原件前往体检门店自行提取）' : '快递（体检当日到体检门店前台填写快递单并支付快递费用）' ?>
            </div>
        </div>
        <?php
        if ($aCardProduct['iBookStatus'] != 2 && $aCardProduct['iBookStatus'] != 5 && $aCardProduct['iOrderTime'] > time()) {
            ?>
            <div class="form-group clearfix">
                <label for="iProductType" class="col-xs-4 control-label">供应商确认状态：</label>

                <div class="col-xs-7 store-select-div">
                <span
                    class="red list-label"> <?php echo !empty($aPreStatus[$aCardProduct['iPreStatus']]) ? $aPreStatus[$aCardProduct['iPreStatus']] : '' ?></span>
                </div>
            </div>
            <div class="cart-return">
                <input type="button" id="change_time" value="预约改期" class="form-control btn-warning">
            </div>
            <div class="cart-return">
                <input type="button"
                       data-hasupgrade="<?php echo !empty($aCardProduct['iLastProductID']) ? $aCardProduct['iLastProductID'] : 0 ?>"
                       id="cancel_appointment" value="取消预约" class="form-control btn-danger">
            </div>
            <div class="cart-return">
                <input class="form-control" id="reback" value="返回" type="button">
            </div>
        <?php
        } else {
            ?>
            <div class="form-group clearfix">
                <label for="iProductType" class="col-xs-4 control-label">到检状态：</label>

                <div class="col-xs-7 store-select-div">
                <span
                    class="red list-label"> <?php echo (!empty($aCardProduct['iBookStatus']) && ($aCardProduct['iBookStatus'] == 2 || $aCardProduct['iBookStatus'] == 5)) ? '已到检' : '未到检' ?></span>
                </div>
            </div>
            <div class="form-group clearfix">
                <label for="iProductType" class="col-xs-4 control-label">出报告状态：</label>

                <div class="col-xs-7 store-select-div">
                <span
                    class="red list-label"> <?php echo (!empty($aCardProduct['iBookStatus']) && $aCardProduct['iBookStatus'] == 5 ) ? '已出报告' : '未出报告' ?></span>
                </div>
            </div>
        <?php
        } ?>

    </div>
</div>
<script>
    $(function () {
        var cardid = '<?php echo $aParam['id']; ?>';
        var productid = '<?php echo $aParam['pid']; ?>';
        var changeUrl = '<?php echo $sReserveCommitUrl.'id/'.$aParam['id'].'/sid/'.$aCardProduct['iStoreID'].'/pid/'.$aParam['pid'].'/type/1';?>';
        var cancelAppointmentUrl = '<?php echo $sReserveCancelUrl?>';
        var rebackUrl = '<?php echo $sCardlistUrl ?>';
        var recancelmsg = '您确定要取消预约吗？';
        var recanelmsg2 = '您确定要取消预约吗？';
        $('#change_time').click(function () {
            location.href = changeUrl;
        });
        $('#cancel_appointment').click(function () {
            var hasupgrade = $(this).data('hasupgrade');
            var msg = hasupgrade ? recanelmsg2 : recancelmsg;
            if (confirm(msg)) {
                $.get(cancelAppointmentUrl, {id: cardid, pid: productid}, function (ret) {
                    if (ret.status) {
                        alert(ret.data);
                        if (location) {
                            window.location.href = rebackUrl;
                        }
                    } else {
                        alert(ret.data);
                        return false;
                    }
                }, 'json');
            }
        });
        $('#reback').click(function () {
            location.href = rebackUrl;
        });
    })
</script>