<div class="row <?php echo empty($hassnotoremenu) ? 'row-main-margin' : ''; ?>">
    <div class="order-attention1">
        此处为全部体验门店信息，不通过体检套餐试用范围略有差异，可通过“体检购买”模块，浏览某体检套餐所支持的门店信息
    </div>
    <div class="reservestore-content">
        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">门店所在地区：</label>

            <div class="col-xs-3 store-select-div">
                <select id="iCityID" name="iCityID" class="form-control input-validate store-select">
                    <option value="0" selected="">请选择</option>
                    <?php
                    if (!empty($aCitys)) {
                        foreach ($aCitys as $key => $value) {
                            ?>
                            <option value="<?php echo $key ?>"><?php echo $value ?></option>
                            <?php
                        }
                    }
                    ?>
                </select>
            </div>

            <div class="col-xs-3 store-select-div">
                <select id="iRegionID" name="iRegionID" class="form-control input-validate store-select">
                    <option value="0">全部</option>
                </select>
            </div>
        </div>

        <div class="form-group clearfix">
            <label for="iProductType" class="col-xs-4 control-label">所属体检品牌：</label>

            <div class="col-xs-7 store-select-div">
                <select id="iSupplierID" name="iRegionID" class="form-control input-validate store-select">
                    <option value="0">全部</option>
                    <?php
                    if (!empty($aSupplier)) {
                        foreach ($aSupplier as $key => $value) {
                            ?>
                            <option value="<?php echo $key ?>"><?php echo $value ?></option>
        <?php
    }
}
?>
                </select>
            </div>
        </div>
        <div class="border-bottom1"></div>
        <div class="store-item-list" id="store-item-list">
        </div>
    </div>
</div>
<script>
    var listObj = {
        pagenumber: 1,
        initList: function () {
            var _this = this;
            commonObj.moreUrl = '<?php echo $sGetStoreListUrl; ?>';//设置下拉分页url
            commonObj.appendId = "store-item-list";//设置下拉分页外层id
            var cid = $('#iCityID').find('option:selected').val();
            var rid = $('#iRegionID').find('option:selected').val();
            var sid = $('#iSupplierID').find('option:selected').val();
            var pid = $('#iProductID').val();
            //下滑分页数据
            commonObj.pageData = {page: listObj.pagenumber, iCityID: cid, iRegionID: rid, iSupplierID: sid, iProductID: pid, t: true};
            //下滑分页回调函数
            commonObj.searchCallBack = function (res) {
                $(".loaddiv").hide();
                var dataLength = res.data.aList.length;
                if (dataLength > 0) {
                    listObj.pagenumber++;
                    commonObj.ajaxstatus = true;
                    commonObj.pageData.page = listObj.pagenumber;
                    var htmlArray = [];
                    $.each(res.data.aList, function (i, e) {
                        var star = _this.initStar(e.sLevel);
                        htmlArray[i]= '<div class="store-item">' +
                                '<div class="store-item-title">' + e.sName + '</div>' +
                                '<div class="store-item-city">(' + e.sCityName + '/' + e.sRegionName + ')</div>' + star +
                                '<div><span class="store-item-label">网点地址：</span>' + e.sAddress + '</div>' +
                                '<div><span class="store-item-label">联系电话：</span>' + e.sTel + '</div>' +
                                '<div><span class="store-item-label">营业时间：</span>' + e.sWorktime + '</div>' +
                                '<div class="distance"><span class="distance-label">直线距离</span>：<span>1.8</span>KM</div>' +
                                '<div class="storemap"><i class="fa fa-2x fa-map-marker"></i><a href="' + '<?php echo $sMapUrl ?>' + 'id/' + e.iStoreID + '">查看地图</a> </div>' +
                                '</div>';
                    });

                    $("#" + commonObj.appendId).append(htmlArray.join(""));
                } else {
                    commonObj.fenyestatus = false
                }
            }
            if (_this.pagenumber == 1) {
                _this.change();
                commonObj.scrollNextPage();
            } else {
                //下滑分页触发
                commonObj.scrollNextPage();
            }


        },
        initStar: function (point) {
            var starhtml = '<div class="store-item-level">';
            var starnum = Math.floor(point);
            for (i = 0; i < starnum; i++)
            {
                starhtml += '<i class="fa fa-lg fa-star"></i>';
            }
            if (starnum != point) {
                starhtml += '<i class="fa fa-lg fa-star-half-o"></i>';
                starnum += 1;
            }

            for (i = 0; i < 5 - starnum; i++)
            {
                starhtml += '<i class="fa fa-lg fa-star-o"></i>';
            }
            starhtml += '</div>';
            return starhtml;
        },
        change: function () {
            var _this = this;
            var cid = $('#iCityID').find('option:selected').val();
            var rid = $('#iRegionID').find('option:selected').val();
            var sid = $('#iSupplierID').find('option:selected').val();
            $.post('<?php echo $sGetStoreListUrl; ?>', {iCityID: cid, iRegionID: rid, iSupplierID: sid}, function (ret) {
                if (ret.status) {
                    if (ret.data.aList) {
                        var html = '';
                        $.each(ret.data.aList, function (i, e) {
                            var star = _this.initStar(e.sLevel);
                            html += '<div class="store-item">' +
                                    '<div class="store-item-title">' + e.sName + '</div>' +
                                    '<div class="store-item-city">(' + e.sCityName + '/' + e.sRegionName + ')</div>' + star +
                                    '<div><span class="store-item-label">网点地址：</span>' + e.sAddress + '</div>' +
                                    '<div><span class="store-item-label">联系电话：</span>' + e.sTel + '</div>' +
                                    '<div><span class="store-item-label">营业时间：</span>' + e.sWorktime + '</div>' +
                                    '<div class="distance"><span class="distance-label">直线距离</span>：<span>1.8</span>KM</div>' +
                                    '<div class="storemap"><i class="fa fa-2x fa-map-marker"></i><a href="' + '<?php echo $sMapUrl ?>' + 'id/' + e.iStoreID + '">查看地图</a> </div>' +
                                    '</div>';
                        });
                        $('.store-item-list').html(html);
                        _this.pagenumber++;
                        commonObj.ajaxstatus=true;
                        commonObj.pageData.page=_this.pagenumber;
                    }
                    return false;
                } else {
                    alert(ret.data);
                    return false;
                }
            }, 'json');
        }
    }
    $(function () {
        var getreginUrl = '<?php echo $sGetRegionUrl; ?>';
        listObj.initList();

        function citychange() {
            var cid = $('#iCityID').find('option:selected').val();
            $('#iRegionID').empty();
            $.post(getreginUrl, {iCityID: cid}, function (ret) {
                if (ret.status) {
                    $('#iRegionID').append('<option value="0">全部</option>');
                    $.each(ret.data, function (i, e) {
                        $('#iRegionID').append('<option value="' + e.iRegionID + '">' + e.sRegionName + '</option>');
                    });
                    listObj.pagenumber = 1;
                    commonObj.ajaxstatus = true;
                    commonObj.pageData.page = listObj.pagenumber;
                    listObj.initList();
                    return false;
                } else {
                    alert('请求数据失败!');
                }
            }, 'json');
        }



        $('#iCityID').on('change', function () {
            citychange();
        });

        $('#iRegionID').on('change', function () {
            listObj.pagenumber = 1;
            commonObj.ajaxstatus = true;
            commonObj.pageData.page = listObj.pagenumber;
            listObj.initList();
        });

        $('#iSupplierID').on('change', function () {
            listObj.pagenumber = 1;
            commonObj.ajaxstatus = true;
            commonObj.pageData.page = listObj.pagenumber;
            listObj.initList();
        });

    })
</script>