<div class="pbody clearfix">
    <?php include('listheader.phtml'); ?>
</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="<?php echo !empty($sListUrl) ? $sListUrl : '' ?>">
        <div class="pcate clearfix">
            <div class="pmargin clearfix">
                <div class="catetitle">城市</div>
                <div class="col-sm-11">
                    <span class="cityall <?php echo !empty($aParam['aCity']) ? 'pcursor' : 'pbold' ?>">全部</span>
                    <?php if (!empty($aCity)) {
                        foreach ($aCity as $key => $value) {
                            if ($key==0) continue;
                            ?>
                            <span class="city <?php echo in_array($key,$aParam['aCity']) ? 'pbold' : 'pcursor' ?>" data-key="<?php echo $key; ?>"><?php echo $value ?></span>
                            <input <?php echo in_array($key,$aParam['aCity']) ? 'checked' : '' ?> type="checkbox" class="aCity" id="aCity_<?php echo $key; ?>" name="aCity[<?php echo $key; ?>]">
                        <?php
                        }
                    } ?>
                </div>
            </div>
            <div class="pmargin clearfix">
                <div class="catetitle">供应商</div>
                <div class="col-sm-11">
                    <span class="supplierall <?php echo !empty($aParam['aSupplier']) ? 'pcursor' : 'pbold' ?>">全部</span>
                    <?php if (!empty($aSupplier)) {
                        foreach ($aSupplier as $key => $value) {
                            if ($key==0) continue;
                            ?>
                            <span class="supplier <?php echo in_array($key,$aParam['aSupplier']) ? 'pbold' : 'pcursor' ?>" data-key="<?php echo $key; ?>"><?php echo $value ?></span>
                            <input <?php echo in_array($key,$aParam['aSupplier']) ? 'checked' : '' ?> type="checkbox" class="aSupplier" id="aSupplier_<?php echo $key; ?>" name="aSupplier[<?php echo $key; ?>]">
                        <?php
                        }
                    } ?>
                </div>
            </div>
            <div class="pmargin clearfix">
                <div class="catetitle">关键字</div>
                <div class="col-sm-11">
                    <input placeholder="支持搜索门店名称或编号" name="sKeyword" type="text" value="<?php echo !empty($aParam['sKeyword'])?$aParam['sKeyword']:''?>" class="input-margin-right input-width form-control input-validate">
                    <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
                </div>
            </div>
        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th class="text-center">产品编号</th>
                <th class="text-center">产品名称</th>
                <th class="text-center">拓展产品数量</th>
                <th class="text-center">城市数量</th>
                <th class="text-center">门店数量</th>
                <th class="text-center">价格</th>
                <th class="text-center">操作</th>
            </tr>
            </thead>
            <tbody>
            <?php if (!empty($aData['aList'])) {
                foreach ($aData['aList'] as $value) {?>
                    <tr>
                        <td class="text-center"><?php echo !empty($value['sProductCode']) ? $value['sProductCode'] : '' ?></td>
                        <td class="text-center"><?php echo !empty($value['sProductName']) ? $value['sProductName'] : '' ?></td>
                        <td class="text-center"><?php echo !empty($value['iExpandNum']) ? $value['iExpandNum'] : 0 ?></td>
                        <td class="text-center"><?php echo !empty($value['iCityNum']) ? $value['iCityNum'] : 0 ?></td>
                        <td class="text-center"><?php echo !empty($value['iStoreNum']) ? $value['iStoreNum'] : 0 ?></td>
                        <td class="text-center"><?php echo !empty($value['iManPrice']) ? $value['iManPrice'] : 0 ?></td>
                        <td class="text-center">
                            <a class="product_view" href="javascript:;" data-url="<?php echo !empty($sViewBaseInfoUrl) ? $sViewBaseInfoUrl : '' ?>?id=<?php echo $value['iProductID'] ?>" title="查看"><i
                                    class="fa fa-eye fa-large"></i></a>
                            <a class="product_eidt" href="javascript:;" data-url="<?php echo !empty($sEditBaseInfoUrl) ? $sEditBaseInfoUrl : '' ?>?id=<?php echo $value['iProductID'] ?>" title="编辑"><i
                                    class="fa fa-pencil fa-large"></i></a>
                        </td>
                    </tr>
                <?php }
            } ?>
            </tbody>
        </table>
        <?php echo !empty($aData['aPager']) ? $aData['aPager'] : '' ?>
    </form>
</div>
<script>
    //城市点击效果
    $('.city').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.cityall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#aCity_'+key).prop("checked",true);
    });
    //城市全部点击效果
    $('.cityall').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.city').addClass('pcursor').removeClass('pbold');
        $('.aCity').prop("checked", false);
    });
    //供应商点击效果
    $('.supplier').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.supplierall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#aSupplier_'+key).prop("checked",true);
    });
    //供应商全部点击效果
    $('.supplierall').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.supplier').addClass('pcursor').removeClass('pbold');
        $('.aSupplier').prop("checked", false);
    });
    $('.product_view').click(function () {
        location.href = $(this).data('url');
        return false;
    });
    $('.product_eidt').click(function () {
        location.href = $(this).data('url');
        return false;
    });
</script>