
<?php if (!empty($aEditUserHeaderInfo)) {
    include('editpriceheader.phtml');
} else {
    ?>
    <div class="pheader clearfix">第五步：增加加项包</div>
<?php
} ?>
<div class="pbody clearfix">
    <div class="ptitle clearfix">
        <span data-toggle="popover" data-trigger="hover" data-html="true" data-placement="bottom"
              data-content="<?php echo !empty($sTips) ? $sTips : '' ?>">已添加的加项包(共<span
                class="red"><?php echo count($aHasAddtion); ?></span>个)</span>
        <?php if (!empty($aHasAddtion) && !empty($aEditUserHeaderInfo)) { ?>
            <input type="button" value="删除选中加项包" class="btn btn-primary input-margin-left" id="addtion-delete-select">
        <?php } ?>
    </div>
    <?php if (!empty($aHasAddtion)) {
        ?>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <?php if (!empty($aEditUserHeaderInfo)) {
                    ?>
                    <th class="text-center th-width"><input type="checkbox" id="hasaddtionall"></th>
                <?php
                } ?>
                <th class="text-center">加项包名称</th>
                <th class="text-center">类型</th>
                <th class="text-center">编号</th>
                <th class="text-center">价格</th>
                <?php if (!empty($aEditUserHeaderInfo)) {
                    ?>
                    <th class="text-center">操作</th>
                <?php
                } ?>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($aHasAddtion as $value) { ?>
                <tr>
                    <?php if (!empty($aEditUserHeaderInfo)) {
                        ?>
                        <td class="text-center"><input class="hasaddtionlist" type="checkbox" name="hasaddtionlist[]"
                                                       value="<?php echo !empty($value['iAutoID']) ? $value['iAutoID'] : '' ?>">
                        </td>
                    <?php
                    } ?>
                    <td class="text-center"><?php echo !empty($value['sName']) ? $value['sName'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aType[$value['iType']]) ? $aType[$value['iType']] : '' ?></td>
                    <td class="text-center"><?php echo !empty($value['sCode']) ? $value['sCode'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($value['sPrice']) ? $value['sPrice'] : '' ?></td>
                    <?php if (!empty($aEditUserHeaderInfo)) {
                        ?>
                        <td class="text-center">
                            <a class="hasaddtion_del" href="javascript:;"
                               data-url="<?php echo !empty($sDeleteAddtionUrl) ? $sDeleteAddtionUrl : '' ?>?id=<?php echo $value['iAutoID'] ?>"
                               title="删除"><i
                                    class="fa fa-trash fa-large"></i></a>
                        </td>
                    <?php
                    } ?>

                </tr>
            <?php
            } ?>
            </tbody>
        </table>
    <?php
    } else {
        ?>
        <div class="clearfix">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">暂时没有添加体检加项包，请从下面的表格中选择需要添加的项目，添加之后加项包信息会在这里显示出来</div>
            <div class="col-sm-3"></div>
        </div>
    <?php
    } ?>
    <div class="ptitle clearfix"></div>
    <div class="ptitle clearfix">可添加的加项包</div>
    <form id="myform" class="form-horizontal" role="form" method="post"
          action="<?php echo !empty($sEidtUserAddtionUrl) ? $sEidtUserAddtionUrl : '' ?><?php echo 'id/'.$iProductID.'/uid/'.$sUserID.'/tid/'.$iChannelType .'/cid/'.$iChannelID ?>">
        <div class="pcate clearfix">
            <div class="pmargin clearfix">
                <div class="catetitle col-sm-1 text-center">分类</div>
                <div class="col-sm-11">
                    <span class="typeall <?php echo !empty($aParam['aType']) ? 'pcursor' : 'pbold' ?>">全部</span>
                    <?php if (!empty($aType)) {
                        foreach ($aType as $key => $value) {
                            if ($key == 0) continue;
                            ?>
                            <span class="type <?php echo in_array($key, $aParam['aType']) ? 'pbold' : 'pcursor' ?>"
                                  data-key="<?php echo $key; ?>"><?php echo $value ?></span>
                            <input <?php echo in_array($key, $aParam['aType']) ? 'checked' : '' ?> type="checkbox"
                                                                                                   class="aType"
                                                                                                   id="aType_<?php echo $key; ?>"
                                                                                                   name="aType[<?php echo $key; ?>]">
                        <?php
                        }
                    } ?>
                </div>
            </div>
            <div class="pmargin clearfix">
                <div class="catetitle col-sm-1 text-center">关键字</div>
                <div>
                    <input placeholder="支持搜索加项包名称或编号" name="sKeyword" type="text"
                           value="<?php echo !empty($aParam['sKeyword']) ? $aParam['sKeyword'] : '' ?>"
                           class="input-margin-right input-width form-control input-validate">
                    <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
                    <?php if (!empty($aEditUserHeaderInfo)) {
                        ?>
                        <input type="button" value="添加选中加项包" class="btn btn-primary" id="addtion-add-select">
                    <?php
                    } ?>
                </div>
            </div>
        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <?php if (!empty($aEditUserHeaderInfo)) {
                    ?>
                    <th class="text-center th-width"><input type="checkbox" id="addtionall"></th>
                <?php
                } ?>
                <th class="text-center">加项包名称</th>
                <th class="text-center">分类</th>
                <?php if (!empty($aEditUserHeaderInfo)) {
                    ?>
                    <th class="text-center">操作</th>
                <?php
                } ?>
            </tr>
            </thead>
            <tbody>
            <?php if (!empty($aAddtion['aList'])) {
                foreach ($aAddtion['aList'] as $value) { ?>
                    <tr>
                        <?php if (!empty($aEditUserHeaderInfo)) {
                            ?>
                            <td class="text-center"><input class="addtionlist" type="checkbox" name="addtionlist[]"
                                                           value="<?php echo !empty($value['iAddtionID']) ? $value['iAddtionID'] : '' ?>">
                            </td>
                        <?php
                        } ?>
                        <td class="text-center"><?php echo !empty($value['sName']) ? $value['sName'] : '' ?></td>
                        <td class="text-center"><?php echo !empty($aType[$value['iType']]) ? $aType[$value['iType']] : '' ?></td>
                        <?php if (!empty($aEditUserHeaderInfo)) {
                            ?>
                            <td class="text-center">
                                <a class="addtion_add" href="javascript:;"
                                   data-url="<?php echo !empty($sInsertAddtionUrl) ? $sInsertAddtionUrl : '' ?><?php echo 'id/'.$value['iAddtionID'].'/pid/'.$iProductID.'/uid/'.$sUserID.'/tid/'.$iChannelType .'/cid/'.$iChannelID ?>"
                                   title="添加"><i
                                        class="fa fa-plus fa-large"></i></a>
                            </td>                        <?php
                        } ?>
                    </tr>
                <?php }
            } ?>
            </tbody>
        </table>
        <?php echo !empty($aAddtion['aPager']) ? $aAddtion['aPager'] : '' ?>
        <div class="btn-toolbar text-center">
            <input name="iProductID" id="iProductID" type="hidden"
                   value="<?php echo !empty($iProductID) ? $iProductID : 0 ?>">
            <?php if (!empty($aEditUserHeaderInfo) && $aEditUserHeaderInfo == 1) {
                ?>
                <input type="button" id="product_eidt" class="btn btn-primary input-margin-right" value="编辑"
                       data-url="<?php echo !empty($aEditHeaderInfo[5]['editurl']) ? $aEditHeaderInfo[5]['editurl'] : '' ?>?id=<?php echo $aProduct['iProductID'] ?>">
            <?php
            } else {
                ?>
                <input type="button" data-url="<?php echo !empty($sNextUrl) ? $sNextUrl : 'javascript:;' ?>" id="next"
                       class="btn btn-primary"
                       value="<?php echo !empty($aEditUserHeaderInfo) ? '保存' : '完成' ?>">
            <?php
            } ?>
            <input type="button" value="返回列表" id="cancel" class="btn"
                   onclick="location.href='<?php echo !empty($aEditCannelUrl) ? $aEditCannelUrl.'id/'.$iProductID : 'javascript:;' ?>';return false;">
        </div>
    </form>
</div>
<!--
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/plupload/plupload.full.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/upload.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/plupload/zh_CN.js"></script>
-->
<script type="text/javascript">
    //分类加项包点击效果
    $('.type').click(function () {
        $(this).addClass('pbold').removeClass('pcursor');
        $('.typeall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#aType_' + key).prop("checked", true);
    });
    //分类全部点击效果
    $('.typeall').click(function () {
        $(this).addClass('pbold').removeClass('pcursor');
        $('.type').addClass('pcursor').removeClass('pbold');
        $('.aType').prop("checked", false);
    });
    //全选效果
    $('#addtionall').click(function () {
        if ($(this).prop("checked") == false) {
            $('.addtionlist').prop("checked", false);
        } else {
            $('.addtionlist').prop("checked", true);
        }
    });
    //全选效果
    $('#hasaddtionall').click(function () {
        if ($(this).prop("checked") == false) {
            $('.hasaddtionlist').prop("checked", false);
        } else {
            $('.hasaddtionlist').prop("checked", true);
        }
    });
    //加项包选择效果
    $('.addtionlist').click(function () {
        $('#addtionall').prop("checked", false);
    });
    //加项包选择效果
    $('.hasaddtionlist').click(function () {
        $('#hasaddtionall').prop("checked", false);
    });
    //加项包单个添加
    $('.addtion_add').click(function () {
        var url = $(this).data('url');
        if (confirm("您确认要添加该加项包吗？")) {
            $.get(url, function (ret) {
                alert(ret.data);
                if (ret.status) {
                    location.reload();
                }
            }, 'json');
        }
    });
    //加项包批量添加
    $('#addtion-add-select').click(function () {
        var select_addtion = '';
        var count_num = 0;
        var url = '<?php echo !empty($sInsertAddtionUrl) ? $sInsertAddtionUrl : '' ?><?php echo 'type/1/pid/'.$iProductID.'/uid/'.$sUserID.'/tid/'.$iChannelType .'/cid/'.$iChannelID.'/id/' ?>';
        $('.addtionlist').each(function (index, dom) {
            if ($(dom).prop('checked')) {
                select_addtion += $(dom).val() + ',';
                count_num++;
            }
        });
        if (!count_num) {
            alert('请选择要添加的加项包');
            return false;
        }
        select_addtion = select_addtion.substring(0, select_addtion.length - 1);
        url += select_addtion;
        if (confirm("您确认要添加选中的" + count_num + "个加项包吗？")) {
            $.get(url, function (ret) {
                alert(ret.data);
                if (ret.status) {
                    location.reload();
                }
            }, 'json');
        }
    });
    //加项包单个删除
    $('.hasaddtion_del').click(function () {
        var url = $(this).data('url');
        if (confirm("您确认要删除该加项包吗？")) {
            $.get(url, function (ret) {
                alert(ret.data);
                if (ret.status) {
                    location.reload();
                }
            }, 'json');
        }
    });
    //加项包批量删除
    $('#addtion-delete-select').click(function () {
        var select_addtion = '';
        var count_num = 0;
        var url = '<?php echo !empty($sDeleteAddtionUrl) ? $sDeleteAddtionUrl : '' ?>?type=1&id=';
        $('.hasaddtionlist').each(function (index, dom) {
            if ($(dom).prop('checked')) {
                select_addtion += $(dom).val() + ',';
                count_num++;
            }
        });
        if (!count_num) {
            alert('请选择要删除的加项包');
            return false;
        }
        select_addtion = select_addtion.substring(0, select_addtion.length - 1);
        url += select_addtion;
        if (confirm("您确认要删除选中的" + count_num + "个加项包吗？")) {
            $.get(url, function (ret) {
                alert(ret.data);
                if (ret.status) {
                    location.reload();
                }
            }, 'json');
        }
    });
    $('#next').click(function () {
        var ifLocation = <?php echo !empty($aEditUserHeaderInfo) ? 0 : 1 ?>;
        var operationType = '<?php echo !empty($aEditUserHeaderInfo) ? '保存' : '添加' ?>';
        alert(operationType+'成功!');
        if (ifLocation) {
            location.href = $(this).data('url');
        }
    });
    $('#product_eidt').click(function () {
        location.href = $(this).data('url');
        return false;
    });
    $(function () {
        $("[data-toggle='popover']").popover();
    });
</script>