<?php
include('editpriceheader.phtml');
?>

<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <input name="iProductID" type="hidden"
               value="<?php echo !empty($iProductID) ? $iProductID : '' ?>">
        <input name="sUserID" type="hidden"
               value="<?php echo !empty($sUserID) ? $sUserID : '' ?>">

        <div class="form-group">
            <label for="iManPrice" class="col-sm-2 control-label"> 价格（男）：</label>

            <div class="col-sm-6">
                <input name="iManPrice" type="text"
                       value="<?php echo !empty($aProduct['iManPrice']) ? $aProduct['iManPrice'] : '' ?>"
                       class="form-control input-validate onlycanint">
            </div>
        </div>

        <div class="form-group">
            <label for="iWomanPrice1" class="col-sm-2 control-label"> 价格（女-未婚）：</label>

            <div class="col-sm-6">
                <input name="iWomanPrice1" type="text"
                       value="<?php echo !empty($aProduct['iWomanPrice1']) ? $aProduct['iWomanPrice1'] : '' ?>"
                       class="form-control input-validate onlycanint">
            </div>
        </div>

        <div class="form-group">
            <label for="iWomanPrice2" class="col-sm-2 control-label"> 价格（女-已婚）：</label>

            <div class="col-sm-6">
                <input name="iWomanPrice2" type="text"
                       value="<?php echo !empty($aProduct['iWomanPrice2']) ? $aProduct['iWomanPrice2'] : '' ?>"
                       class="form-control input-validate onlycanint">
            </div>
        </div>

        <div class="form-group">
            <label for="iWomanPrice2" class="col-sm-2 control-label"> 定制名称（可选）：</label>

            <div class="col-sm-6">
                <input name="sAlias" type="text"
                       value="<?php echo !empty($aProduct['sAlias']) ? $aProduct['sAlias'] : '' ?>"
                       class="form-control input-validate">
            </div>
        </div>

        <div class="form-group">
            <label for="iProductType" class="col-sm-2 control-label">HR能否看到价格：</label>

            <div class="col-sm-3">
                <input type="radio" name="iUserCanPrice" class=""
                       value="1" <?php echo isset($aProduct['iUserCanPrice']) && $aProduct['iUserCanPrice'] == 1 ? 'checked' : '' ?>>
                是
                <input type="radio" name="iUserCanPrice" class=""
                       value="0" <?php echo empty($aProduct['iUserCanPrice']) ? 'checked' : '' ?>> 否
            </div>
        </div>
        <div class="btn-toolbar text-center">
            <input type="submit" id="next" class="btn btn-primary"
                   value="保存">
            <input type="button" value="取消" id="cancel" class="btn"
                   onclick="location.href='<?php echo !empty($aEditCannelUrl) ? $aEditCannelUrl.'id/'.$iProductID : 'javascript:;' ?>';return false;">
        </div>
    </form>
</div>
<script type="text/javascript">
    $(function () {
        $("#myform").validate({
            submitHandler: function (form) {
                $.post(form.action, $(form).serialize(), function (ret) {
                    if (ret.status) {
                        alert(ret.data);
                    } else {
                        alert(ret.data);
                    }
                }, 'json');
                return false;
            }
        });
    });
    $('.onlycanint').keyup(function(){
        var c=$(this);
        if(/[^\d]/.test(c.val())){//替换非数字字符
            var temp_amount=c.val().replace(/[^\d.]/g,'');
            $(this).val(temp_amount);
        }
    });
</script>