<ul class="nav nav-tabs">
    <li role="presentation" <?php echo $iType == 1 ? 'class="active"' : '' ?>><a href="<?php echo $iType == 1 ? 'javascript:;' : $sRCardListUrl ?>">实物体检卡列表</a></li>
    <li role="presentation" <?php echo $iType == 2 ? 'class="active"' : '' ?>><a href="<?php echo $iType == 2 ? 'javascript:;' : $sCreateRCardUrl ?>">批量生成实体卡</a></li>
</ul>
<div style="margin-bottom: 20px;"></div>