<div class="pheader clearfix"><?php echo isset($aCate['iAutoID'])?'编辑':'增加'?>类别</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <input name="iAutoID" type="hidden" value="<?php echo isset($aCate['iAutoID']) ? $aCate['iAutoID'] : ''?>">
		<div class="form-group col-sm-9">
			<label for="sCateName" class="col-sm-3 control-label"> <span class="tubiao">*</span>类别名称：</label>
			<div class="col-sm-9">
				<input name="sCateName" validate="!clength:1-20" placeholder="请输入类别名称" type="text" value="<?php echo isset($aCate['sCateName']) ? $aCate['sCateName'] : ''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>

		<?php if ($menu || $aCate['iParentID']) {
			$menu = 1;
		?>
		<div class="form-group col-sm-9">
			<label for="iParentID" class="col-sm-3 control-label"> <span class="tubiao">*</span>从属大类：</label>
			<div class="col-sm-9">
				<select name="iParentID" class="form-control input-validate">
                    <?php foreach ($category as $k => $v) {?>
                        <option value="<?php echo $k?>" <?php echo isset($aCate['iParentID']) && $aCate['iParentID'] == $k ? 'selected' : ''?>><?php echo $v?></option>
                    <?php }?>
                </select>
			</div>
		</div>
		<?php }?>

		<div class="form-group col-sm-9">
			<label for="sRemark" class="col-sm-3 control-label">检查意义：</label>
			<div class="col-sm-9">
				<textarea id='sRemark' name='sRemark' class="form-control input-validate"><?php echo isset($aCate['sRemark']) ? $aCate['sRemark'] : ''?></textarea>
                <span class="validate_checktip"></span>				
			</div>			
		</div>

    	<div class="form-groupbtn-toolbar text-center col-sm-9">
        	<button id="save" class="btn btn-primary">保存</button>
        	<button id="cancel"class="btn" onclick="location.href='/admin/category/list?type=<?php echo $menu?>';return false;">取消</button>
        </div>
    </form>
</div>

<script type="text/javascript">
$(function() {
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	           location.href = '/admin/category/list?type=<?php echo $menu?>';
	        }
	    }, 'json');
		return false;
	}});
});
</script>