<div class="pheader clearfix"><?php echo isset($aCity['iCityID'])?'编辑':'增加'?>城市</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iCityID" type="hidden" value="<?php echo isset($aCity['iCityID'])?$aCity['iCityID']:''?>">
		<div class="form-group">
			<label for="sCityName" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 城市名称：</label>
			<div class="col-sm-10">
				<input name="sCityName" validate="!length:2-20" type="text" value="<?php echo isset($aCity['sCityName'])?$aCity['sCityName']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sPassword" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 城市代码：</label>
			<div class="col-sm-10">
			    <input name="sCityCode" validate="!length:2-50" type="text" value="<?php echo isset($aCity['sCityCode'])?$aCity['sCityCode']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sPassword" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 前台是否启用：</label>
			<div class="col-sm-10">
			    <input type="radio" name="iFrontShow" value="1" <?php echo !isset($aCity['iFrontShow'])||$aCity['iFrontShow']==1?'checked':''?>> 是
			    <input type="radio" name="iFrontShow" value="0" <?php echo isset($aCity['iFrontShow'])&&$aCity['iFrontShow']==0?'checked':''?>> 否
			</div>
		</div>
		<div class="form-group">
			<label for="sPassword" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 后台是否启用：</label>
			<div class="col-sm-10">
			    <input type="radio" name="iBackendShow" value="1" <?php echo !isset($aCity['iBackendShow'])||$aCity['iBackendShow']==1?'checked':''?>> 是
			    <input type="radio" name="iBackendShow" value="0" <?php echo isset($aCity['iBackendShow'])&&$aCity['iBackendShow']==0?'checked':''?>> 否
			</div>
		</div>
    	<div class="btn-toolbar text-center">
        	<button id="save" class="btn btn-primary">保存</button>
        	<button id="cancel"class="btn" onclick="location.href='/admin/city/list/';return false;">取消</button>
        </div>
	</form>
</div>
<script type="text/javascript">
$(function() {
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            location.href = '/admin/city/list/';
	        }
	    }, 'json');
		return false;
	}});
});
</script>