<div class="pheader clearfix"><?php echo isset($aItem['iItemID'])?'编辑':'增加'?>单项</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <input name="iItemID" type="hidden" value="<?php echo isset($aItem['iItemID'])?$aItem['iItemID']:''?>">
    
        <div class="form-group col-sm-10">
            <label for="sName" class="col-sm-3 control-label"> <span class="tubiao">*</span>体检单项名称：</label>
            <div class="col-sm-9">
                <input name="sName" type="text" value="<?php echo isset($aItem['sName'])?$aItem['sName']:''?>" class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div>       

        <div class="form-group col-sm-10">
            <label for="iParentCat" class="col-sm-3 control-label"> <span class="tubiao">*</span>体检大类：</label>
            <div class="col-sm-9">
                <select id="iParentCat" name="iParentCat" class="form-control input-validate">
                    <option value='0' <?php echo !isset($aItem['iParentCat']) ?'selected' : ''?>>请选择</option>
                    <?php foreach ($parentCat as $k => $v) {?>                        
                        <option value="<?php echo $k?>" <?php echo isset($aItem['iParentCat'])&&$aItem['iParentCat']==$k?'selected':''?>><?php echo $v?></option>
                    <?php }?>
                </select>
            </div>
        </div>

        <div class="form-group col-sm-10">
            <label for="iCat" class="col-sm-3 control-label"> <span class="tubiao">*</span>单项分类：</label>
            <div class="col-sm-9">
                <select id="iCat" name="iCat" class="form-control input-validate">
                    <option value='0' <?php echo !isset($aItem['iCat']) ?'selected' : ''?>>请选择</option>
                    <?php foreach ($subCat as $k => $v) {?>
                        <option value="<?php echo $k?>" <?php echo isset($aItem['iCat'])&&$aItem['iCat']==$k?'selected':''?>><?php echo $v?></option>
                    <?php }?>
                </select>
            </div>
        </div>

        <div class="form-group col-sm-10">
            <label for="iCanAdd" class="col-sm-3 control-label"> <span class="tubiao">*</span>可作为单项加项：</label>
            <div class="col-sm-9">
                <input type='radio' name='iCanAdd' value='1' 
                <?php echo isset($aItem['iCanAdd']) && 1 == $aItem['iCanAdd'] ? 'checked': '';?>>可以</input>
                <input type='radio' name='iCanAdd' value='2'
                <?php echo !isset($aItem['iCanAdd']) || 2 == $aItem['iCanAdd'] ? 'checked': '';?>>不可以</input>
                <span class="validate_checktip"></span>
            </div>
        </div>        

        <div class="form-group col-sm-10">
            <label for="iCanMan" class="col-sm-3 control-label"> <span class="tubiao">*</span>男性是否可用：</label>
            <div class="col-sm-9">
                <input type='radio' name='iCanMan' value='1' 
                <?php echo !isset($aItem['iCanMan']) || 1 == $aItem['iCanMan'] ? 'checked': '';?>>可以</input>
                <input type='radio' name='iCanMan' value='2'
                <?php echo isset($aItem['iCanMan']) && 2 == $aItem['iCanMan'] ? 'checked': '';?>>不可以</input>
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group col-sm-10">
            <label for="iCanWomanNoMarry" class="col-sm-3 control-label"> <span class="tubiao">*</span>女性未婚是否可用：</label>
            <div class="col-sm-9">
                <input type='radio' name='iCanWomanNoMarry' value='1' 
                <?php echo !isset($aItem['iCanWomanNoMarry']) || 1 == $aItem['iCanWomanNoMarry'] ? 'checked': '';?>>可以</input>
                <input type='radio' name='iCanWomanNoMarry' value='2'
                <?php echo isset($aItem['iCanWomanNoMarry']) && 2 == $aItem['iCanWomanNoMarry'] ? 'checked': '';?>>不可以</input>
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group col-sm-10">
            <label for="iCanWomanMarry" class="col-sm-3 control-label"> <span class="tubiao">*</span>女性已婚是否可用：</label>
            <div class="col-sm-9">
                <input type='radio' name='iCanWomanMarry' value='1' 
                <?php echo !isset($aItem['iCanWomanMarry']) || 1 == $aItem['iCanWomanMarry'] ? 'checked': '';?>>可以</input>
                <input type='radio' name='iCanWomanMarry' value='2'
                <?php echo isset($aItem['iCanWomanMarry']) &&  2 == $aItem['iCanWomanMarry'] ? 'checked': '';?>>不可以</input>
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="form-group col-sm-10">
            <label for="sMark" class="col-sm-3 control-label">检查意义：</label>
            <div class="col-sm-9"> 
                <textarea id='sMark' name='sMark' class="form-control input-validate"><?php echo isset($aItem['sMark']) ? $aItem['sMark'] : ''?></textarea>
                <span class="validate_checktip"></span>
            </div>
        </div>

        <div class="btn-toolbar text-center col-sm-12">
            <button id="save" class="btn btn-primary">保存</button>
            <a class="text-right btn btn-default" href='<?php echo $sUrl;?>'>取消</a>
        </div>
    </form>
</div>

<script type="text/javascript">
$(function() {
    $("#myform").validate({submitHandler: function(form) {
        $.post(form.action, $(form).serialize(), function(ret){
            alert(ret.data);
            if (ret.status) {
               location.href = '<?php echo $sUrl;?>';
            }
        }, 'json');
        return false;
    }});
});

$('#iParentCat').on('change',function(){
    var cid = $(this).find('option:selected').val();
    $('#iCat').empty();
    $.post('/admin/category/getsubcate', {iCateID: cid}, function(ret){
        console.log(ret);
        if (ret.status) {
            $('#iCat').append('<option value="0">请选择</option>');
            $.each(ret.data, function(i,e) {
                $('#iCat').append('<option value="'+e.iAutoID+'">'+e.sCateName+'</option>');
            });
            return false;
        }else {
            alert('请求数据失败!');
        }
    }, 'json');
});

$('#iCat').on('change',function(){
    var cid = $(this).find('option:selected').val();
    $.post('/admin/category/getremark', {iCateID: cid}, function(ret){
        console.log(ret);
        if (ret.status) {
            $('#sMark').val('');
            $('#sMark').val(ret.data.sRemark);
            return false;
        }else {
            alert('请求数据失败!');
        }
    }, 'json');
});

</script>