<div class="pheader clearfix">单项管理</div>
<form id="myform" class="form-horizontal" role="form" method="post" action="">
    <div class="pcate clearfix">
        <div class="pmargin clearfix">
            <div class="catetitle col-sm-1 text-center">支持供应商</div>
            <div class="col-sm-11">
                <span class="supplierall <?php echo !empty($aParam['aSupplier']) ? 'pcursor' : 'pbold' ?>">全部</span>
                <?php if (!empty($supplier)) {
                    foreach ($supplier as $key => $value) { ?>
                        <span class="supplier <?php echo in_array($key,$aParam['aSupplier']) ? 'pbold' : 'pcursor' ?>" data-key="<?php echo $key; ?>"><?php echo $value ?></span>
                        <input <?php echo in_array($key,$aParam['aSupplier']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aSupplier_<?php echo $key; ?>" name="aSupplier[<?php echo $key; ?>]">
                    <?php
                    }
                } ?>
            </div>
        </div>

        <div class="pmargin clearfix">
            <div class="catetitle col-sm-1 text-center">支持城市</div>
            <div class="col-sm-11">
                <span class="cityall <?php echo !empty($aParam['aCity']) ? 'pcursor' : 'pbold' ?>">全部</span>
                <?php if (!empty($city)) {
                    foreach ($city as $key => $value) { ?>
                        <span class="city <?php echo in_array($key,$aParam['aCity']) ? 'pbold' : 'pcursor' ?>" data-key="<?php echo $key; ?>"><?php echo $value ?></span>
                        <input <?php echo in_array($key,$aParam['aCity']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aCity_<?php echo $key; ?>" name="aCity[<?php echo $key; ?>]">
                    <?php
                    }
                } ?>
            </div>
        </div>

        <div class="pmargin clearfix">
            <div class="catetitle col-sm-1 text-center">支持门店</div>
            <div class="col-sm-11">
                <span class="storeall <?php echo !empty($aParam['iStore']) ? 'pcursor' : 'pbold' ?>">全部</span>                
                <span class="store <?php echo !empty($aParam['iStore']) ? 'pbold' : 'pcursor' ?>" data-key="1">部分</span>
                <input <?php echo !empty($aParam['iStore']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="iStore_1" name="iStore">               
            </div>
             <input type="submit" id="formbtn" class="btn btn-primary" value="查询">            
        </div>
    </div>
</form>
    <?php if (1==$aParam['iStore'] && !empty($aList)) { ?>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center"><input id="news_all_check" name="news_all_check" value="" type='checkbox'></th>
            <th class="text-center">门店</th>
            <th class="text-center">供应商</th>
            <th class="text-center">城市</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($aList as $key => $value) {?>
                <tr>
                    <td class="text-center"><input type='checkbox' name='news_check_id' 
                id="news_check_id_<?php echo $value['iStoreID'];?>" value="<?php echo $value['iStoreID'];?>"></td>
                    <td class="text-center"><?php echo $value['sName'] ?></td>
                    <td class="text-center"><?php echo $supplier[$value['iSupplierID']] ?></td>
                    <td class="text-center"><?php echo $city[$value['iCityID']] ?></td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
    <input id='ids' value='<?php echo !empty($sIds) ? $sIds : '';?>' type='hidden'/>
    <hr/>
    <div class="form-group col-sm-10">            
        <input type='' id='sFileKeyExt' name='sFile' value=''>
        <label  class="col-sm-3 control-label" for="file">请选择导入文件：</label>
        <input type='button' value="选择文件" class='plupload' data-target='#sFileKeyExt'>
        <a href="<?php echo $sStaticRoot . '/doc/itemprice.xls'?>" target="_blank" style="color: Blue">（点击此处下载导入模版）</a>
    </div> 

<div class="btn-toolbar text-center col-sm-12">
    <a id="batch_transfer" class="text-right btn btn-default">完成</a>
    <a class="text-right btn btn-default" href='/admin/item/list'>取消</a>
</div>

<script type="text/javascript">
    global.sUploadUrl = '<?php echo Util_Common::getConf('upload', 'url')?>';
    global.sDfsViewUrl = '<?php echo Util_Common::getConf('dfsview', 'url')?>';
</script>

<script type="text/javascript" src="<?php echo $sStaticRoot ?>/plupload/plupload.full.min.js"></script>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/upload.js"></script>
<script type="text/javascript" src="<?php echo $sStaticRoot ?>/plupload/zh_CN.js"></script>

<script type="text/javascript">
    //供应商门店点击效果
    $('.supplier').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.supplierall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#aSupplier_'+key).prop("checked",true);
    });
    //供应商全部点击效果
    $('.supplierall').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.supplier').addClass('pcursor').removeClass('pbold');
        $('.aCategory').prop("checked", false);
    });

    //城市门店点击效果
    $('.city').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.cityall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#aCity_'+key).prop("checked",true);
    });
    //城市全部点击效果
    $('.cityall').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.city').addClass('pcursor').removeClass('pbold');
        $('.aCategory').prop("checked", false);
    });

    //支持门店点击效果
    $('.store').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.storeall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#iStore_'+key).prop("checked",true);
    });
    //支持门店点击效果
    $('.storeall').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.store').addClass('pcursor').removeClass('pbold');
        $('.aCategory').prop("checked", false);
    });

    $('#batch_transfer').bind('click', {
        msg : '没有选择单项'        
    }, piliang);

    function piliang(event) {
        var msg = event.data.msg;
        var url = event.data.url;
        var ids = $('#ids').val();
        var selIds = '';

        $("input[name='news_check_id']").each(function() {
            if ($(this).prop('checked')) {
                selIds += $(this).val() + ',';
            }
        });

        if (selIds != '') {
            ids = selIds.substring(0, selIds.length-1);
        }
        
        if (ids == '') {
            alert(msg);
            return false;
        }

        $('#ids').val(ids);
        submitExcel(ids);
    }

    function submitExcel(ids) {
        $.ajax({
            url : '/admin/item/excelimport',
            type : 'post',
            data : {
                ids : ids,
                file : $('#sFileKeyExt').val()        
            },
            dataType : 'json',
            success : function(ret) {
                alert(ret.data);
                if (ret.status) {
                    window.location.reload();
                }
            }
        });
    };

    $('#news_all_check').click(function() {
        var is_checked = $(this).prop('checked');
        $("input[name='news_check_id']").each(function() {
            $(this).prop('checked', is_checked);
        });
    });

</script>