    <div class="pheader clearfix">单项管理</div>
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <div class="pcate clearfix">
            <div class="pmargin clearfix">
                <div class="catetitle col-sm-1 text-center">体检大类</div>
                <div class="col-sm-11">
                    <span class="cateall <?php echo !empty($aParam['aParentCat']) ? 'pcursor' : 'pbold' ?>">全部</span>
                    <?php if (!empty($parentCat)) {
                        foreach ($parentCat as $key => $value) { ?>
                            <span class="category <?php echo in_array($key,$aParam['aParentCat']) ? 'pbold' : 'pcursor' ?>" data-key="<?php echo $key; ?>"><?php echo $value ?></span>
                            <input <?php echo in_array($key,$aParam['aParentCat']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aCategory_<?php echo $key; ?>" name="aParentCat[<?php echo $key; ?>]">
                        <?php
                        }
                    } ?>
                </div>
            </div>

            <div class="pmargin clearfix">
                <div class="catetitle col-sm-1 text-center">体检项目分类</div>
                <div class="col-sm-11">
                    <span class="catall <?php echo !empty($aParam['aCat']) ? 'pcursor' : 'pbold' ?>">全部</span>
                    <?php if (!empty($subCat)) {
                        foreach ($subCat as $key => $value) { ?>
                            <span class="cat <?php echo in_array($key,$aParam['aCat']) ? 'pbold' : 'pcursor' ?>" data-key="<?php echo $key; ?>"><?php echo $value ?></span>
                            <input <?php echo in_array($key,$aParam['aCat']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aCat_<?php echo $key; ?>" name="aCat[<?php echo $key; ?>]">
                        <?php
                        }
                    } ?>
                </div>
            </div>

            <div class="pmargin clearfix">
                <div class="catetitle col-sm-1 text-center">男性</div>
                <div class="col-sm-11">
                    <span class="manall <?php echo !empty($aParam['aCanMan']) ? 'pcursor' : 'pbold' ?>">全部</span>

                    <span class="man <?php echo in_array(1, $aParam['aCanMan']) ? 'pbold' : 'pcursor' ?>" data-key="1"> 可用 </span>
                    <input <?php echo in_array(1,$aParam['aCanMan']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aCanMan_1" name="aCanMan[1]">

                    <span class="man <?php echo in_array(2, $aParam['aCanMan']) ? 'pbold' : 'pcursor' ?>" data-key="2">不可用 </span>
                    <input <?php echo in_array(2,$aParam['aCanMan']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aCanMan_2" name="aCanMan[2]">                        
                </div>
            </div>

            <div class="pmargin clearfix">
                <div class="catetitle col-sm-1 text-center">女未婚</div>
                <div class="col-sm-11">
                    <span class="nowomanall <?php echo !empty($aParam['aCanWomanNoMarry']) ? 'pcursor' : 'pbold' ?>">全部</span>

                    <span class="nowoman <?php echo in_array(1, $aParam['aCanWomanNoMarry']) ? 'pbold' : 'pcursor' ?>" data-key="1"> 可用 </span>
                    <input <?php echo in_array(1,$aParam['aCanWomanNoMarry']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aCanWomanNoMarry_1" name="aCanWomanNoMarry[1]">

                    <span class="nowoman <?php echo in_array(2, $aParam['aCanWomanNoMarry']) ? 'pbold' : 'pcursor' ?>" data-key="2">不可用 </span>
                    <input <?php echo in_array(2,$aParam['aCanWomanNoMarry']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aCanWomanNoMarry_2" name="aCanWomanNoMarry[2]">
                </div>
            </div>  

            <div class="pmargin clearfix">
                <div class="catetitle col-sm-1 text-center">女已婚</div>
                <div class="col-sm-11">
                    <span class="womanall <?php echo !empty($aParam['aCanWomanMarry']) ? 'pcursor' : 'pbold' ?>">全部</span>
                    <span class="woman <?php echo in_array(1, $aParam['aCanWomanMarry']) ? 'pbold' : 'pcursor' ?>" data-key="1"> 可用 </span>
                    <input <?php echo in_array(1,$aParam['aCanWomanMarry']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aCanWomanMarry_1" name="aCanWomanMarry[1]">

                    <span class="woman <?php echo in_array(2, $aParam['aCanWomanMarry']) ? 'pbold' : 'pcursor' ?>" data-key="2">不可用 </span>
                    <input <?php echo in_array($key,$aParam['aCanWomanMarry']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aCanWomanMarry_2" name="aCanWomanMarry[2]">
                </div>
            </div>

            <div class="pmargin clearfix">
                <div class="catetitle col-sm-1 text-center">单项加项</div>
                <div class="col-sm-11">
                    <span class="addall <?php echo !empty($aParam['aCanAdd']) ? 'pcursor' : 'pbold' ?>">全部</span>

                    <span class="add <?php echo in_array(1, $aParam['aCanAdd']) ? 'pbold' : 'pcursor' ?>" data-key="1"> 可用 </span>
                    <input <?php echo in_array(1,$aParam['aCanAdd']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aCanAdd_1" name="aCanAdd[1]">

                    <span class="add <?php echo in_array(2, $aParam['aCanAdd']) ? 'pbold' : 'pcursor' ?>" data-key="2">不可用 </span>
                    <input <?php echo in_array(2,$aParam['aCanAdd']) ? 'checked' : '' ?> type="checkbox" class="aCategory" id="aCanAdd_2" name="aCanAdd[2]">     
                </div>
            </div> 

            <div class="pmargin clearfix">
                <div class="catetitle col-sm-1 text-center">关键字</div>
                <div>
                    <input placeholder="支持搜索单项名称或编号" name="sKeyword" type="text" value="<?php echo !empty($aParam['sKeyword'])?$aParam['sKeyword']:''?>" class="input-margin-right input-width form-control input-validate">
                    <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
                    <a class="text-right btn btn-default" href='/admin/item/import'>价格导入</a>
                    <a class="text-right btn btn-default" href='/admin/category/list'>分类维护</a>
                    <a class="text-right btn btn-default" href='/admin/item/add'>新增单项</a>
                    <a class="text-right btn btn-default" href='/admin/item/namelist'>单项名称对应</a>
                </div>
            </div>
        </div>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th class="text-center">大类</th>
                <th class="text-center">分类</th>
                <th style="width:30%;">单项名称</th>
                <th class="text-center">单项加项</th>
                <th class="text-center">男</th>
                <th class="text-center">女未婚</th>
                <th class="text-center">女已婚</th>
                <th class="text-center">成本价</th>
                <th class="text-center">操作</th>
            </tr>
            </thead>
            <tbody>
            <?php if (!empty($aList['aList'])) {
                foreach ($aList['aList'] as $value) {?>
                    <tr>
                        <td class="text-center"><?php echo $parentCat[$value['iParentCat']] ?></td>
                        <td class="text-center"><?php echo $subCat[$value['iCat']] ?></td>
                        <td style="text-center"><?php echo $value['sName'] ?></td>
                        <td class="text-center"><?php echo 1 == $value['iCanadd'] ? '√' : '' ?></td>
                        <td class="text-center"><?php echo 1 == $value['iCanMan'] ? '√' : '' ?></td>
                        <td class="text-center"><?php echo 1 == $value['iCanWomanNoMarry'] ? '√' : '' ?></td>
                        <td class="text-center"><?php echo 1 == $value['iCanWomanMarry'] ? '√' : '' ?></td>
                        <td class="text-center"><?php echo $value['sCost']?></td>
                        <td class="text-center">
                            <a href="/admin/item/edit?id=<?php echo $value['iItemID']?>">内容</a>
                            <a href="/admin/item/editprice?id=<?php echo $value['iItemID']?>" title="发送账号">价格</a>  
                        </td>
                    </tr>
                <?php }
            } ?>
            </tbody>
        </table>
        <?php echo !empty($aList['aPager']) ? $aList['aPager'] : '' ?>        
    </form>
</div>

<script type="text/javascript">
    //大类单项点击效果
    $('.category').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.cateall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#aCategory_'+key).prop("checked",true);
    });
    //大类全部点击效果
    $('.cateall').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.category').addClass('pcursor').removeClass('pbold');
        $('.aCategory').prop("checked", false);
    });

    //分类单项点击效果
    $('.cat').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.catall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#aCat_'+key).prop("checked",true);
    });
    //分类全部点击效果
    $('.catall').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.cat').addClass('pcursor').removeClass('pbold');
        $('.aCategory').prop("checked", false);
    });

    //男性点击效果
    $('.man').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.manall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#aCanMan_'+key).prop("checked",true);
    });
    //男性全部点击效果
    $('.manall').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.man').addClass('pcursor').removeClass('pbold');
        $('.aCategory').prop("checked", false);
    });

    //未婚女性点击效果
    $('.woman').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.womanall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#aCanWomanMarry_'+key).prop("checked",true);
    });
    //未婚女性全部点击效果
    $('.womanall').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.woman').addClass('pcursor').removeClass('pbold');
        $('.aCategory').prop("checked", false);
    });

    //女性点击效果
    $('.nowoman').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.nowomanall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#aCanWomanNoMarry_'+key).prop("checked",true);
    });
    //女性全部点击效果
    $('.nowomanall').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.nowoman').addClass('pcursor').removeClass('pbold');
        $('.aCategory').prop("checked", false);
    });

    //加项点击效果
    $('.add').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.addall').addClass('pcursor').removeClass('pbold');
        var key = $(this).data('key');
        $('#aCanAdd_'+key).prop("checked",true);
    });
    //加项全部点击效果
    $('.addall').click(function(){
        $(this).addClass('pbold').removeClass('pcursor');
        $('.add').addClass('pcursor').removeClass('pbold');
        $('.aCategory').prop("checked", false);
    });
</script>