<div class="pheader clearfix"><?php echo isset($aFront['iAutoID'])?'编辑':'增加'?><?php echo $aClass['sName']?></div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <input type="hidden" class="form-control" name="iAutoID" value="<?php echo isset($aFront['iAutoID'])?$aFront['iAutoID']:''?>">
        <input type="hidden" class="form-control" name="sClass" value="<?php echo $sClass?>">
	    <?php if ($aClass['sTitle'] != '') {?>
		<div class="form-group">
			<label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 标题：</label>
			<div class="col-sm-10">
			<?php if ($aClass['sSource'] == '') {?>
				<input type="text" class="form-control input-validate" validate="!length:2-50" name="sTitle" value="<?php echo isset($aFront['sTitle'])?$aFront['sTitle']:''?>">
			<?php } else {?>
			    <input type="hidden" name="sSourceID" id="sSourceID" value="<?php echo isset($aFront['sSourceID'])?$aFront['sSourceID']:''?>"> 
			    <input type="text" class="form-control input-validate yyauto" autocomplete="off" id="sTitle" name="sTitle" value="<?php echo isset($aFront['sTitle'])?$aFront['sTitle']:''?>"
				source="<?php echo $aClass['sSource']?>" ivalue="<?php echo $aClass['sValue']?>" ishow="item.<?php echo $aClass['sValue']?>" iresult="<?php echo $aClass['sTarget']?>"
				>
			<?php }?>
				<span class="validate_checktip"></span>
			</div>
		</div>
		<?php }?>
		<?php if ($aClass['sImage'] != '') {?>
		<div class="form-group">
            <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 图片：</label>
            <div class="col-sm-10">
                <input type="hidden" validate="!required:请上传<?php echo $aClass['sImage']?>" id="sImage" name="sImage" value="<?php echo isset($aFront['sImage']) ? $aFront['sImage'] : '' ?>">
                <img id="sImageShow" style="width:160px;height:120px;" src="<?php if (isset($aFront['sImage']) && !empty($aFront)) { echo Util_Uri::getDFSViewURL($aFront['sImage']); }else{ echo '';}?>">
                <input type="button" value="选择" class="plupload" data-target="#sImage" data-img="#sImageShow" data-fsize="100kb">
                <span class="text-muted">请上传大小≤100K，支持png、jpg图片</span>
                <span class="validate_checktip"></span>
            </div>
        </div>
		<?php }?>
		<?php if ($aClass['sUrl'] != '') {?>
		<div class="form-group">
			<label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 链接：</label>
			<div class="col-sm-10">
				<input type="text" class="form-control input-validate" validate="!url:true" id="sUrl" name="sUrl" value="<?php echo isset($aFront['sUrl'])?$aFront['sUrl']:''?>">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<?php }?>
		<?php if ($aClass['sDiy1'] != '') {?>
		<div class="form-group">
			<label class="col-sm-2 control-label"><strong style="color:red;">*</strong> <?php echo $aClass['sDiy1']?>：</label>
			<div class="col-sm-10">
				<input type="text" class="form-control input-validate" id="sDiy1" name="sDiy1" value="<?php echo isset($aFront['sDiy1'])?$aFront['sDiy1']:''?>">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<?php }?>
		<?php if ($aClass['sDiy2'] != '') {?>
		<div class="form-group">
			<label class="col-sm-2 control-label"><strong style="color:red;">*</strong> <?php echo $aClass['sDiy2']?>：</label>
			<div class="col-sm-10">
				<input type="text" class="form-control input-validate" id="sDiy2" name="sDiy2" value="<?php echo isset($aFront['sDiy2'])?$aFront['sDiy2']:''?>">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<?php }?>
		<?php if ($aClass['sDiy3'] != '') {?>
		<div class="form-group">
			<label class="col-sm-2 control-label"><strong style="color:red;">*</strong> <?php echo $aClass['sDiy3']?>：</label>
			<div class="col-sm-10">
				<input type="text" class="form-control input-validate" id="sDiy3" name="sDiy3" value="<?php echo isset($aFront['sDiy3'])?$aFront['sDiy3']:''?>">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<?php }?>
		<?php if ($aClass['sColor'] != '') {?>
		<div class="form-group">
			<label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 颜色：</label>
			<div class="col-sm-10">
				<input type="text" class="form-control input-validate" id="sDiy3" name="sDiy3" value="<?php echo isset($aFront['sTitle'])?$aFront['sTitle']:''?>">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<?php }?>
		<?php if ($aClass['sRemark'] != '') {?>
		<div class="form-group">
			<label class="col-sm-2 control-label">备注：</label>
			<div class="col-sm-10">
			    <textarea name="sRemark" id="sRemark" class="form-control input-validate"><?php echo isset($aFront['sRemark'])?$aFront['sRemark']:''?></textarea>
				<span class="validate_checktip"></span>
			</div>
		</div>
		<?php }?>
		
		<div class="btn-toolbar text-center">
			<input type="submit" class="btn btn-primary" value="保存">
    	    <button id="cancel"class="btn" onclick="location.href='/admin/front/<?php echo empty($sClass)?"list":$sClass?>.html';return false;">取消</button>
		</div>
	</form>
</div>
<script type="text/javascript">
$(function() {
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            location.href = '/admin/front/<?php echo empty($sClass)?"list":$sClass?>.html';
	        }
	    }, 'json');
		return false;
	}});
});
</script>

<script type="text/javascript">
    global.sUploadUrl = '<?php echo Yaf_G::getConf('upload', 'url')?>';
    global.sDfsViewUrl = '<?php echo Yaf_G::getConf('dfsview', 'url')?>';
</script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/plupload/plupload.full.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/upload.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot?>/plupload/zh_CN.js"></script>
<link rel="stylesheet" href="<?php echo $sStaticRoot ?>/jquery-ui/1.11.1/jquery-ui.min.css" type="text/css"/>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/jquery-ui/1.11.1/jquery-ui.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/autocomplete.js"></script>