<div class="pheader clearfix">体检卡购买记录</div>
<div class="pbody clearfix">
	<ul class="nav nav-tabs">
	    <li role="presentation" <?php echo $aParam['type'] == 0 ? 'class="active"' : '' ?>><a href="<?php echo $aParam['type'] == 0  ? 'javascript:;' : '/admin/order/refund/type/0.html' ?>">未处理</a></li>
	    <li role="presentation" <?php echo $aParam['type'] == 1 ? 'class="active"' : '' ?>><a href="<?php echo $aParam['type'] == 1 ? 'javascript:;' : '/admin/order/refund/type/1.html' ?>">已处理</a></li>
	</ul>
</div>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="/admin/order/refund/">
        <input type="hidden" name="type" value="<?php echo intval($aParam['type']);?>" />
        <div class="row">
            <div class="form-group col-sm-3">
                <label style="width: 70px">姓名：</label>
                <input type="text" value="<?php echo !empty($aParam['sRealName']) ? $aParam['sRealName'] : '' ?>"
                       class="form-control" name="sRealName" style="width: 100px">
            </div>
            <div class="form-group col-sm-3">
                <label style="width: 70px">身份证：</label>
                <input type="text" value="<?php echo !empty($aParam['sIdentityCard']) ? $aParam['sIdentityCard'] : '' ?>"
                       class="form-control" name="sIdentityCard" style="width: 100px">
            </div>
            <div class="form-group col-sm-3">
                <label style="width: 100px">订单流水号：</label>
                <input type="text" value="<?php echo !empty($aParam['sKeyword']) ? $aParam['sKeyword'] : '' ?>"
                       class="form-control" name="sKeyword" style="width: 100px">
            </div>
            
            <div class="form-group">
                <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
                <input type="hidden" name="exportexcel" id="exportexcel" value="0">
                <input type="button" id="export" class="btn btn-primary" value="导出">
            </div>
        </div>
    </form>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center">员工姓名</th>
            <th class="text-center">身份证</th>
            <th class="text-center">退费金额</th>
            <th class="text-center">订单流水号</th>
            <th class="text-center">第三方订单号</th>
            <th class="text-center">升级订单流水号</th>
            <th class="text-center">升级第三方订单号</th>
            <th class="text-center">申请时间</th>
            <?php if (!empty($iType)) {
                ?>
                <th class="text-center">处理结果</th>
                <?php
            } else {
                ?>
                <th class="text-center">操作</th>
            <?php
            } ?>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($aData['aList'])) {
            foreach ($aData['aList'] as $aRefund) { ?>
                <tr>
                    <td class="text-center"><?php echo !empty($aRefund['sRealName']) ? $aRefund['sRealName'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aRefund['sIdentityCard']) ? $aRefund['sIdentityCard'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aRefund['sMoney']) ? $aRefund['sMoney'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aRefund['sOrderCode']) ? $aRefund['sOrderCode'] : ''; ?></td>
                    <td class="text-center"><?php echo !empty($aRefund['sPayOrderID']) ? $aRefund['sPayOrderID'] : ''; ?></td>
                    <td class="text-center"><?php echo !empty($aRefund['sUpgradeOrderCode']) ? $aRefund['sUpgradeOrderCode'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aRefund['sUpgradePayOrderID']) ? $aRefund['sUpgradePayOrderID'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aRefund['iCreateTime']) ? date("Y-m-d", $aRefund['iCreateTime']) : '' ?></td>
                    <?php if (!empty($iType)) {
                        ?>
                        <td class="text-center"><?php echo !empty($aRefundStatus[$aRefund['iStatus']]) ? $aRefundStatus[$aRefund['iStatus']] : '' ?></td>
                    <?php
                    } else {
                        ?>
                        <td class="text-center">
                            <a  href="javascript:checkrefund(<?php echo $aRefund['iAutoID'] ?>,1);" title="允许退款"><i
                                    class="fa fa-check-square fa-large"></i></a>
                            <a  href="javascript:checkrefund(<?php echo $aRefund['iAutoID'] ?>,0);" title="拒绝退款"><i
                                    class="fa fa-minus-square fa-large"></i></a>
                        </td>
                    <?php
                    } ?>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
    <?php echo !empty($aData['aPager']) ? $aData['aPager'] : '' ?>
</div>
<script type="text/javascript">
    function checkrefund(id,type){
        var url = '/admin/order/refundcheck';
        var data = {icpID: id,type:type};
        var msg = type == 1 ? '允许退款' : '拒绝退款';

        if (confirm("您确认"+msg+"吗？")) {
            $.post(url, data, function (ret) {
                if (ret.status) {
                    alert(ret.data);
                    location.reload();
                }else {
                    alert(ret.data);
                }
            }, 'json');
        }
    }

    $('#export').click(function(){
        $('#exportexcel').val(1);
        $('#myform').submit();
    });
</script>