<?php include('statheader.phtml'); ?>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="">
        <div class="row">
            <div class="form-group col-sm-5">
                <label>体检周期(开始时间)：</label>
                <input type="text" value="<?php echo !empty($aParam['sStartDate']) ? $aParam['sStartDate'] : '' ?>"
                       format="YYYY-MM-DD" class="laydatetime form-control" name="sStartDate" style="width: 120px">
				至
				<input type="text" value="<?php echo !empty($aParam['sEndDate']) ? $aParam['sEndDate'] : '' ?>"
                       format="YYYY-MM-DD" class="laydatetime form-control" name="sEndDate" style="width: 120px">
            </div>
            <div class="form-group">
                <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
            </div>
        </div>
    </form>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center">企业名称</th>
            <th class="text-center">销售总额</th>
            <th class="text-center">AF结算总额</th>
            <th class="text-center">安排人次</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($aList)) {
            foreach ($aList as $v) { ?>
                <tr>
                    <td class="text-center"><?php echo !empty($v['sCoName']) ? $v['sCoName'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($v['sCost']) ? $v['sCost'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($v['sCost']) ? $v['sCost'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($v['iUserCnt']) ? $v['iUserCnt'] : '' ?></td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
</div>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/laydate/laydate.js"></script>