<ul class="nav nav-tabs">
    <li role="presentation" <?php echo $iType == 1 ? 'class="active"' : '' ?>><a href="<?php echo $iType == 1 ? 'javascript:;' : $sExpressUrl.'?type=1' ?>">快递收入</a></li>
    <li role="presentation" <?php echo $iType == 2 ? 'class="active"' : '' ?>><a href="<?php echo $iType == 2 ? 'javascript:;' : $sExpressUrl.'?type=2' ?>">自交件收入</a></li>
    <li role="presentation" <?php echo $iType == 3 ? 'class="active"' : '' ?>><a href="<?php echo $iType == 3 ? 'javascript:;' : $sExpressUrl.'?type=3' ?>">已打印收入件</a></li>
</ul>