<?php include('clientinfoheader.phtml'); ?>
<style>
    .search-form .form-group {
        margin-bottom: 15px;
    }
</style>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="">
        <div class="col-sm-12 form-group">
            <div class="col-sm-9">
                <label>体检计划名称：</label>
                <input type="text" value="<?php echo !empty($aParam['sPlanName']) ? $aParam['sPlanName'] : ''?>" class="form-control" name="sPlanName" style="width: 100px">
                <label>状态：</label>
                <select name="iStatus" class="form-control" style="width: 100px">
                    <option value="-1" <?php echo $aParam['iStatus']=='-1'  ? 'selected' : '' ?>>全部</option>
                    <option value="0" <?php echo $aParam['iStatus']=='0'  ? 'selected' : '' ?>>未启动</option>
                    <option value="1" <?php echo $aParam['iStatus']=='1'  ? 'selected' : '' ?>>进行中</option>
                    <option value="2" <?php echo $aParam['iStatus']=='2'  ? 'selected' : '' ?>>已结束</option>
                    <?php foreach ($aStatus as $k => $v) { ?>
                        <option value="<?php echo $k ?>" <?php echo isset($aParam['iStatus']) && $aParam['iStatus'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="col-sm-3">
                <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
            </div>
        </div>
    </form>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center">体检计划名称</th>
            <th class="text-center">开始时间</th>
            <th class="text-center">截止时间</th>
            <th class="text-center">发布时间</th>
            <th class="text-center">状态</th>
            <th class="text-center">查看</th>
        </tr>
        </thead>
        <tbody>
        <?php if ($aPlan['iTotal'] > 0) {
            foreach ($aPlan['aList'] as $key => $aUser) { ?>
                <tr>
                    <td class="text-center"><?php echo $aUser['sPlanName'] ?></td>
                    <td class="text-center"><?php echo $aUser['sStartDate'] ?></td>
                    <td class="text-center"><?php echo $aUser['sEndDate'] ?></td>
                    <td class="text-center"><?php echo $aUser['sPublishTime'] ?></td>
                    <td class="text-center"><?php echo $aUser['sStatus'] ?></td>
                    <td class="text-center">
                        <a href="/company/physical/plandetail/id/<?php echo $aUser['iAutoID'] ?>" title="查看详情">查看</a>
                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
    <?php echo !empty($aPlan['aPager']) ? $aPlan['aPager'] : '' ?>
</div>