<?php include('clientinfoheader.phtml');?>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="">
        <div class="row">

            <div class="form-group col-sm-3">
                <label>沟通内容：</label>
                <input type="text" value="<?php echo !empty($aParam['sContent']) ? $aParam['sContent'] : '' ?>"
                       class="form-control" name="sContent" style="width: 160px">
            </div>

            <div class="form-group col-sm-3">
                <label>沟通开始时间：</label>
                <input type="text" value="<?php echo !empty($aParam['iStime']) ? date('Y-m-d H:i:s',
                    $aParam['iStime']) : '' ?>"
                       class="form-control laydatetime" name="iStime" style="width: 160px">
            </div>

            <div class="form-group col-sm-3">
                <label>沟通结束时间：</label>
                <input type="text" value="<?php echo !empty($aParam['iEtime']) ? date('Y-m-d H:i:s',
                    $aParam['iEtime']) : '' ?>"
                       class="form-control laydatetime" name="iEtime" style="width: 160px">
            </div>

            <div class="form-group col-sm-2">
                <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
                <input type="button" onclick="location.href='/admin/communicate/add?id=<?php echo !empty($aUser['iUserID']) ? $aUser['iUserID'] : '' ?>';return false;" class="btn btn-primary" value="添加沟通记录">
            </div>
        </div>
    </form>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center">沟通日期</th>
            <th class="text-center">联系人姓名</th>
            <th class="text-center">联系人电话</th>
            <th class="text-center">重要程度</th>
            <th class="text-center">沟通结果</th>
            <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($aData['aList'])) {
            foreach ($aData['aList'] as $value) {?>
                <tr>
                    <td class="text-center"><?php echo !empty($value['iTime']) ? date('Y-m-d',$value['iTime']) : '' ?></td>
                    <td class="text-center"><?php echo !empty($value['sRealName']) ? $value['sRealName'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($value['sMobile']) ? $value['sMobile'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aCommunicateLevel[$value['iLevel']]) ? $aCommunicateLevel[$value['iLevel']] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aCommunicateResult[$value['iResult']]) ? $aCommunicateResult[$value['iResult']] : '' ?></td>
                    <td class="text-center">
                        <a href="/admin/communicate/edit?id=<?php echo !empty($value['iID']) ? $value['iID'] : '' ?>" title="编辑"><i
                                class="fa fa-pencil fa-large"></i></a>
                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
    <?php echo !empty($aData['aPager']) ? $aData['aPager'] : '' ?>
</div>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/laydate/laydate.js"></script>
