<div class="pheader clearfix"><?php echo isset($aUser['iUserID'])?'编辑':'增加'?>员工</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <input name="iUserID" type="hidden" value="<?php echo isset($aUser['iUserID'])?$aUser['iUserID']:''?>">

		<div class="form-group">
			<label for="sUserName" class="col-sm-2 control-label"> 员工编号：</label>
			<div class="col-sm-10">
				<input name="sUserName" type="text" disabled="disabled" value="<?php echo isset($aUser['sUserName'])?$aUser['sUserName']:'自动生成'?>" class="form-control input-validate">
			</div>
		</div>

		<div class="form-group">
			<label for="sRealName" class="col-sm-2 control-label"> 员工姓名：</label>
			<div class="col-sm-10">
				<input name="sRealName" type="text" value="<?php echo !empty($aUser['sRealName'])?$aUser['sRealName']:''?>" class="form-control input-validate">
			</div>
		</div>

		<div class="form-group">
			<label for="sJobTitleName" class="col-sm-2 control-label"> 职位：</label>
			<div class="col-sm-10">
				<input name="sJobTitleName" type="text" value="<?php echo !empty($aUser['sJobTitleName'])?$aUser['sJobTitleName']:''?>" class="form-control input-validate">
			</div>
		</div>

		<div class="form-group">
			<label for="sEmail" class="col-sm-2 control-label"> Email：</label>
			<div class="col-sm-10">
				<input name="sEmail" type="text" value="<?php echo !empty($aUser['sEmail'])?$aUser['sEmail']:''?>" class="form-control input-validate">
			</div>
		</div>

		<div class="form-group">
			<label for="sMobile" class="col-sm-2 control-label"> 手机号码：</label>
			<div class="col-sm-10">
				<input name="sMobile" type="text" value="<?php echo !empty($aUser['sMobile'])?$aUser['sMobile']:''?>" class="form-control input-validate">
			</div>
		</div>

		<div class="form-group">
			<label for="sJobDate" class="col-sm-2 control-label"> 入职日期：</label>
			<div class="col-sm-10">
				<input name="sJobDate" type="text" value="<?php echo !empty($aUser['sJobDate'])?$aUser['sJobDate']:''?>" class="form-control input-validate">
			</div>
		</div>

		<div class="form-group">
			<label for="sRemark" class="col-sm-2 control-label"> 备注：</label>
			<div class="col-sm-10">
				<textarea class="form-control input-validate" name="sRemark"><?php echo !empty($aUser['sRemark'])?$aUser['sRemark']:''?></textarea>
			</div>
		</div>

		<div class="form-group">
			<label for="iSex" class="col-sm-2 control-label">性别：</label>
			<div class="col-sm-10">
				<select name="iSex" class="form-control input-validate">
					<?php foreach ($aSex as $k => $v) {?>
						<option value="<?php echo $k?>" <?php echo isset($aUser['iSex'])&&$aUser['iSex']==$k?'selected':''?>><?php echo $v?></option>
					<?php }?>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label for="iSex" class="col-sm-2 control-label">部门：</label>
			<div class="col-sm-10">
				<select name="iDeptID" class="form-control input-validate">
					<?php foreach ($aDept as $k => $v) {?>
						<option value="<?php echo $k?>" <?php echo isset($aUser['iDeptID'])&&$aUser['iDeptID']==$k?'selected':''?>><?php echo $v?></option>
					<?php }?>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label for="iJobGradeID" class="col-sm-2 control-label">职级：</label>
			<div class="col-sm-10">
				<select name="iJobGradeID" class="form-control input-validate">
					<?php foreach ($aJobTitleID as $k => $v) {?>
						<option value="<?php echo $k?>" <?php echo isset($aUser['iJobGradeID'])&&$aUser['iJobGradeID']==$k?'selected':''?>><?php echo $v?></option>
					<?php }?>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label for="iStatus" class="col-sm-2 control-label">账号状态：</label>
			<div class="col-sm-10">
				<select name="iStatus" class="form-control input-validate">
					<?php foreach ($aStatus as $k => $v) {?>
						<option value="<?php echo $k?>" <?php echo isset($aUser['iStatus'])&&$aUser['iStatus']==$k?'selected':''?>><?php echo $v?></option>
					<?php }?>
				</select>
			</div>
		</div>
    	<div class="btn-toolbar text-center">
        	<button id="save" class="btn btn-primary">保存</button>
        	<button id="cancel"class="btn" onclick="location.href='/admin/user/list/';return false;">取消</button>
        </div>
    </form>
</div>
<script type="text/javascript">
$(function() {
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	           location.href = '/admin/user/list/';
	        }
	    }, 'json');
		return false;
	}});
});
</script>