<style>
    .search-form .form-group {
        margin-bottom: 15px;
    }
</style>
<div class="pheader clearfix">企业用户账号</div>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="/admin/user/hrlist/">
        <div class="row">

            <div class="form-group col-sm-3">
                <label>企业账号：</label>
                <input type="text" value="<?php echo !empty($aParam['sUserName']) ? $aParam['sUserName'] : '' ?>"
                       class="form-control" name="sUserName" style="width: 180px">
            </div>
            <div class="form-group col-sm-3">
                <label>企业名称：</label>
                <input type="text" value="<?php echo !empty($aParam['sRealName']) ? $aParam['sRealName'] : '' ?>"
                       class="form-control" name="sRealName" style="width: 180px">
            </div>
            <div class="form-group col-sm-3">
                <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
            </div>
        </div>
    </form>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center">企业账号</th>
            <th class="text-center">所属企业</th>
            <th class="text-center">状态</th>
            <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($aData['aList'])) {
            foreach ($aData['aList'] as $aUser) { ?>
                <tr>
                    <td class="text-center"><?php echo !empty($aUser['sUserName']) ? $aUser['sUserName'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aUser['sRealName']) ? $aUser['sRealName'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aStatus[$aUser['iStatus']]) ? $aStatus[$aUser['iStatus']] : '' ?></td>
                    <td class="text-center">
                        <a class="user_lock" href="javascript:;" data-url="/admin/user/lockuser?id=<?php echo $aUser['iUserID'] ?>">账号<span><?php echo ($aUser['iStatus'] == Model_User::STATUS_TYPE_LOCK) ? '解锁' : '锁定';?></span></a>
                        <a class="user_reset" href="javascript:;" data-url="/admin/user/resetuserpwd?id=<?php echo $aUser['iUserID'] ?>">密码重置</a>
                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
    <?php echo !empty($aData['aPager']) ? $aData['aPager'] : '' ?>
</div>

<script>
    $('.user_lock').click(function () {
        var url = $(this).data('url');
        var lock_status = $(this).find('span').html();
        if (confirm("您确认要"+lock_status+"该用户吗？")) {
            $.get(url, function (ret) {
                alert(ret.data);
                if (ret.status) {
                    location.reload();
                }
            }, 'json');
        }
    });

    $('.user_reset').click(function () {
        var url = $(this).data('url');
        if (confirm("您确认要重置该用户密码吗？")) {
            $.get(url, function (ret) {
                alert(ret.data);
                if (ret.status) {
                    location.reload();
                }
            }, 'json');
        }
    });

    $('.user_role_set').click(function () {
        var url = $(this).data('url');
        location.href = url;
        return false;
    });
</script>