<style>
    .search-form .form-group {
        margin-bottom: 15px;
    }
</style>
<div class="pheader clearfix">站点新闻列表</div>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="">
        <div class="row">

            <div class="form-group col-sm-3">
                <label>标题关键字：</label>
                <input type="text" value="<?php echo !empty($aParam['sTitle']) ? $aParam['sTitle'] : '' ?>"
                       class="form-control" name="sTitle" style="width: 100px">
            </div>

            <div class="form-group col-sm-3">
                <label>新闻类别：</label>
                <select name="iType" class="form-control" style="width: 100px">
                    <option value="0">请选择</option>
                    <?php foreach ($aJobTitleID as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aParam['iJobTitleID']) && $aParam['iJobTitleID'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>

            <div class="form-group col-sm-3">
                <label>是否显示：</label>
                <select name="iIsShow" class="form-control" style="width: 100px">
                    <option value="0" <?php echo !isset($aParam['iIsShow']) ? 'selected' : '' ?>>请选择</option>
                    <option value="1" <?php echo isset($aParam['iIsShow']) && $aParam['iIsShow'] == 1 ? 'selected' : ''?>>是</option>
                    <option value="2" <?php echo isset($aParam['iIsShow']) && $aParam['iIsShow'] == 2 ? 'selected' : ''?>>否</option>
                </select>
            </div>

            <div class="form-group col-sm-3">
                <label>是否可以申请：</label>
                <select name="iIsApply" class="form-control" style="width: 100px">
                    <option value="0" <?php echo !isset($aParam['iIsApply']) ? 'selected' : '' ?>>请选择</option>
                    <option value="1" <?php echo isset($aParam['iIsApply']) && $aParam['iIsApply'] == 1 ? 'selected' : ''?>>是</option>
                    <option value="2" <?php echo isset($aParam['iIsApply']) && $aParam['iIsApply'] == 2 ? 'selected' : ''?>>否</option>
                </select>
            </div>

            <div class="form-group col-sm-3">
                <label>是否可以分享：</label>
                <select name="iIsShare" class="form-control" style="width: 100px">
                    <option value="0" <?php echo !isset($aParam['iIsShare']) ? 'selected' : '' ?>>请选择</option>
                    <option value="1" <?php echo isset($aParam['iIsShare']) && $aParam['iIsShare'] == 1 ? 'selected' : ''?>>是</option>
                    <option value="2" <?php echo isset($aParam['iIsShare']) && $aParam['iIsShare'] == 2 ? 'selected' : ''?>>否</option>
                </select>
            </div>

             <div class="form-group col-sm-3">
                <label>是否置顶：</label>
                <select name="iIsTop" class="form-control" style="width: 100px">
                    <option value="0" <?php echo !isset($aParam['iIsTop']) ? 'selected' : '' ?>>请选择</option>
                    <option value="1" <?php echo isset($aParam['iIsTop']) && $aParam['iIsTop'] == 1 ? 'selected' : ''?>>是</option>
                    <option value="2" <?php echo isset($aParam['iIsTop']) && $aParam['iIsTop'] == 2 ? 'selected' : ''?>>否</option>
                </select>
            </div>

            <div class="form-group col-sm-2">
                <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
                <button class="btn btn-primary" id="user_add">新增</button>                
            </div>
        </div>
    </form>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center">标题关键字</th>
            <th class="text-center">新闻类别</th>
            <th class="text-center">是否显示</th>
            <th class="text-center">是否可以申请</th>
            <th class="text-center">是否可以分享</th>
            <th class="text-center">是否置顶</th>            
            <th class="text-center">操作</th>
            <th class="text-center">预览</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($aData['aList'])) {
            foreach ($aData['aList'] as $aFaq) { ?>
                <tr>
                    <td class="text-center"><?php echo !empty($aFaq['sTitle']) ? $aFaq['sTitle'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aFaq['sType']) ? $aFaq['sType'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aFaq['sIsShow']) ? $aFaq['sIsShow'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aFaq['sIsApply']) ? $aFaq['sIsApply'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aFaq['sIsShare']) ? $aFaq['sIsApply'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($aFaq['sIsTop']) ? $aFaq['sIsTop'] : '' ?></td>
                    <td class="text-center">
                        <a href="/admin/faq/edit?id=<?php echo $aFaq['iAutoID'] ?>">修改</a>
                    </td>
                    <td class="text-center">
                        <a href="/admin/faq/edit?id=<?php echo $aFaq['iAutoID'] ?>">预览</a>
                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>

    <?php echo !empty($aData['aPager']) ? $aData['aPager'] : '' ?>
    
</div>

<script>
    $('.user_delete').click(function () {
        var url = $(this).data('url');
        if (confirm("您确认要删除该用户吗？")) {
            $.get(url, function (ret) {
                alert(ret.data);
                if (ret.status) {
                    location.reload();
                }
            }, 'json');
        }
    });
    $('#user_add').click(function () {
        location.href = '/admin/faq/add';
        return false;
    });
</script>