<div class="row row-main-margin">
	<form method="post" id="myform" action="<?php echo !empty($sPayPostUrl) ? $sPayPostUrl : '' ?>">
		<div class="order-attention">
			友情提示，请在下单后15分钟内支付
		</div>
		<div class="pay-info">
			<div class="form-group clearfix">
				<div class="col-xs-4 order-label order-total-price-title">订购时间：</div>
				<div class="col-xs-7 order-input">
					<?php echo !empty($aOrder['iCreateTime']) ? date('Y-m-d H:i:s', $aOrder['iCreateTime']) : '' ?>
				</div>
			</div>
			<div class="form-group clearfix">
				<div class="col-xs-4 order-label order-total-price-title">姓名：</div>
				<div class="col-xs-7 order-input">
					<?php echo !empty($aOrder['sConsignee']) ? $aOrder['sConsignee'] : '' ?>
				</div>
			</div>
			<div class="form-group clearfix">
				<div class="col-xs-4 order-label order-total-price-title">手机：</div>
				<div class="col-xs-7 order-input">
					<?php echo !empty($aOrder['sMobile']) ? $aOrder['sMobile'] : '' ?>
				</div>
			</div>
			<div class="form-group clearfix">
				<div class="col-xs-4 order-label order-total-price-title">邮箱：</div>
				<div class="col-xs-7 order-input">
					<?php echo !empty($aOrder['sEmail']) ? $aOrder['sEmail'] : '' ?>
				</div>
			</div>
			<div class="form-group clearfix">
				<div class="col-xs-4 order-label order-total-price-title">发票：</div>
				<div class="col-xs-7 order-input">
					<?php echo !empty($aOrder['iIfInv']) ? '需要发票' : '不需要发票' ?>
				</div>
			</div>
			<?php if (!empty($aOrder['iIfInv'])) {
				?>
				<div class="form-group clearfix">
					<div class="col-xs-4 order-label order-total-price-title">发票抬头：</div>
					<div class="col-xs-7 order-input">
						<?php echo !empty($aOrder['sInvPayee']) ? $aOrder['sInvPayee'] : '' ?>
					</div>
				</div>
				<div class="form-group clearfix">
					<div class="col-xs-4 order-label order-total-price-title">邮寄地址：</div>
					<div class="col-xs-7 order-input">
						<?php echo !empty($aOrder['sAddress']) ? $aOrder['sAddress'] : '' ?>
					</div>
				</div>
				<div class="form-group clearfix">
					<div class="col-xs-4 order-label order-total-price-title">邮编：</div>
					<div class="col-xs-7 order-input">
						<?php echo !empty($aOrder['sZipcode']) ? $aOrder['sZipcode'] : '' ?>
					</div>
				</div>
			<?php
			} ?>
			<div class="form-group clearfix">
				<div class="col-xs-4 order-label order-total-price-title">支付金额：</div>
				<div class="col-xs-7 order-input">
                <span
					class="order-price"><?php echo !empty($aOrder['sProductAmount']) ? $aOrder['sProductAmount'] : '' ?></span>元
				</div>
			</div>
		</div>
		<div class="order-list" style="margin-top: 20px;">
			<div class="order-list-title">
				商品明细
			</div>
			<div class="order-list-content">
				<?php
				if (!empty($aOrderProduct)) {
					foreach ($aOrderProduct as $key => $value) {
						?>
						<div class="order-item">
							<div>名称：<?php echo !empty($value['sProductName']) ? $value['sProductName'] : '' ?></div>
							<div>价格：<span
									class="order-price"><?php echo !empty($value['sProductPrice']) ? $value['sProductPrice'] : '' ?></span>元*<?php echo !empty($value['iProductNumber']) ? $value['iProductNumber'] : '' ?>
								=<?php echo !empty($value['sTotalPrice']) ? $value['sTotalPrice'] : number_format(0,2) ;?>元
							</div>
						</div>
					<?php
					}
				}
				?>
			</div>
		</div>
		<div class="col-xs-4 col-xs-offset-1">
			<input type="hidden" name="sOrderCode" value="<?php echo !empty($aOrder['sOrderCode']) ? $aOrder['sOrderCode'] : '' ?>">
			<input type="hidden" name="sProductAmount" value="<?php echo !empty($aOrder['sProductAmount']) ? $aOrder['sProductAmount'] : '' ?>">
			<input type="submit" value="支付" class="form-control btn-warning">
		</div>
		<div class="col-xs-4 col-xs-offset-1">
			<input class="form-control" value="返回" type="button" onclick="window.history.back()">
		</div>
	</form>
</div>
<script>
	$(function () {
		var orderlist = '<?php echo $sOrderListUrl ?>';
		$("#myform").validate({submitHandler: function(form) {
			$.post(form.action, $(form).serialize(), function(ret){
				//alert(ret.data);
				if (ret.status) {
					callpay();
					//location.href = orderlist;
				}
			}, 'json');
			return false;
		}});

		//调用微信JS api 支付
		function jsApiCall()
		{
			WeixinJSBridge.invoke(
				'getBrandWCPayRequest',
				<?php echo $aData['jsApiParameters']; ?>,
				function(res){
					WeixinJSBridge.log(res.err_msg);
					if(res.err_msg == "get_brand_wcpay_request:ok" ) {// 使用以上方式判断前端返回,微信团队郑重提示：res.err_msg将在用户支付成功后返回    ok，但并不保证它绝对可靠。
						window.location.href = orderlist;
					}
				}
			);
		}

		function callpay()
		{
			if (typeof WeixinJSBridge == "undefined"){
				if( document.addEventListener ){
					document.addEventListener('WeixinJSBridgeReady', jsApiCall, false);
				}else if (document.attachEvent){
					document.attachEvent('WeixinJSBridgeReady', jsApiCall);
					document.attachEvent('onWeixinJSBridgeReady', jsApiCall);
				}
			}else{
				jsApiCall();
			}
		}
		//获取共享地址
		function editAddress()
		{
			WeixinJSBridge.invoke(
				'editAddress',
				<?php echo $aData['editAddress']; ?>,
				function(res){
					var value1 = res.proviceFirstStageName;
					var value2 = res.addressCitySecondStageName;
					var value3 = res.addressCountiesThirdStageName;
					var value4 = res.addressDetailInfo;
					var tel = res.telNumber;

					//alert(value1 + value2 + value3 + value4 + ":" + tel);
				}
			);
		}

		window.onload = function(){
			if (typeof WeixinJSBridge == "undefined"){
				if( document.addEventListener ){
					document.addEventListener('WeixinJSBridgeReady', editAddress, false);
				}else if (document.attachEvent){
					document.attachEvent('WeixinJSBridgeReady', editAddress);
					document.attachEvent('onWeixinJSBridgeReady', editAddress);
				}
			}else{
				editAddress();
			}
		};

	})
</script>