<div class="pbody clearfix">
    <?php include('listheader.phtml'); ?>
</div>
<div class="pbody clearfix">
    <form id="myform" class="form-inline" role="form" method="post"
          action="<?php echo !empty($sAcceptErrorUrl) ? $sAcceptErrorUrl : '' ?>">
        <div>
            <div class="col-sm-3 list-caozuo">
                <label>快递单号：</label>
                <input placeholder="请输入快递单号" type="text"
                       value="<?php echo !empty($aParam['sExpressCode']) ? $aParam['sExpressCode'] : '' ?>"
                       class="form-control" name="sExpressCode">
            </div>
            <div class="col-sm-3 list-caozuo">
                <label>操作日期：</label>
                <input format="YYYY-MM-DD" placeholder="请选择日期" type="text"
                       value="<?php echo !empty($aParam['iUpdateTime']) ? $aParam['iUpdateTime'] : '' ?>"
                       class="form-control laydatetime" name="iUpdateTime">
            </div>

            <div class="col-sm-3 list-caozuo">
                <label>处理状态：</label>
                <select name="iStatus" id="iStatus" class="form-control">
                    <option value="0">请选择</option>
                    <?php if (!empty($aStatus)) {
                        foreach ($aStatus as $key => $value) {
                            ?>
                            <option <?php echo (!empty($aParam['iStatus']) && $aParam['iStatus'] == $key) ? 'selected' : '' ?>
                                value="<?php echo $key ?>"><?php echo $value ?></option>
                        <?php
                        }
                    } ?>
                </select>
            </div>

            <input type="hidden" name="type" value="<?php echo !empty($iType) ? $iType : '' ?>">
            <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
            <input type="button" id="print" class="btn btn-primary" value="签办">
        </div>
    </form>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center"><input type="checkbox" id="expressall"></th>
            <th class="text-center">快递单号</th>
            <th class="text-center">问题类型</th>
            <th class="text-center" style="max-width:300px">备注</th>
            <th class="text-center">操作员</th>
            <th class="text-center">操作时间</th>
            <th class="text-center">处理状态</th>
            <th class="text-center" style="max-width:300px">处理结果</th>
            <th class="text-center">重新受理</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($aData['aList'])) {
            foreach ($aData['aList'] as $value) { ?>
                <tr>
                    <td class="text-center"><input type="checkbox" class="expresslist"
                                                   value="<?php echo !empty($value['iAutoID']) ? $value['iAutoID'] : '' ?>">
                    </td>
                    <td class="text-center"><?php echo !empty($value['sExpressCode']) ? $value['sExpressCode'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($value['sType']) ? $value['sType'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($value['sRemark']) ? $value['sRemark'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($value['sUpdateUserName']) ? $value['sUpdateUserName'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($value['iUpdateTime']) ? date('Y-m-d H:i:s', $value['iUpdateTime']) : '' ?></td>
                    <td class="text-center"><?php echo !empty($value['sStatus']) ? $value['sStatus'] : '' ?></td>
                    <td class="text-center"><?php echo !empty($value['sTreatedRemark']) ? $value['sTreatedRemark'] : '' ?></td>
                    <td class="text-center">
                        <?php if ($value['iStatus'] == 3) {//已处理完成
                            if (!empty($value['iEmployeeID'])) {
                                ?>
                                <a class="delexpress" href="<?php echo !empty($sAcceptAddCaseUrl) ? $sAcceptAddCaseUrl : '' ?>?id=<?php echo $value['iEmployeeID'] ?>" title="重新受理"><i
                                        class="fa fa-hand-o-right fa-large"></i></a>
                                <?php
                            } else {
                                ?>
                                <a class="delexpress" href="<?php echo !empty($sAcceptAddCaseUrl) ? $sAcceptAddCaseUrl : '' ?>?errorid=<?php echo $value['iAutoID'] ?>" title="重新受理"><i
                                        class="fa fa-hand-o-right fa-large"></i></a>
                                <?php
                            }
                        } ?>

                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
    <?php echo !empty($aData['aPager']) ? $aData['aPager'] : '' ?>
</div>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/laydate/laydate.js"></script>
<script>
    $(function () {
        //全选效果
        $('#expressall').click(function () {
            if ($(this).prop("checked") == false) {
                $('.expresslist').prop("checked", false);
            } else {
                $('.expresslist').prop("checked", true);
            }
        });

        $('.delexpress').click(function () {
            var Url = $(this).data('url');
            $.get(Url, function (ret) {
                if (ret.status) {
                    alert(ret.data);
                    location.reload();
                } else {
                    alert(ret.data);
                }
            }, 'json');
        });

        $('#print').click(function () {
            var ids = '';
            var Url = '<?php echo $sPrintExpressUrl; ?>';
            $('.expresslist:checked').each(function () {
                ids += $(this).val() + ',';
            });
            if (!ids) {
                alert('请先选择快递单');
                return false;
            } else {
                ids = ids.substring(0, ids.length - 1);
                $.get(Url, {id: ids}, function (ret) {
                    if (ret.status) {
                        alert(ret.data);
                        location.reload();
                    } else {
                        alert(ret.data);
                    }
                }, 'json');
            }
        });
    });
</script>