<ul class="nav nav-tabs">
    <li role="presentation" <?php echo $iType == 1 ? 'class="active"' : '' ?>><a href="<?php echo $iType == 1 ? 'javascript:;' : $sAcceptEmployeeUrl ?>">受理案件</a></li>
    <li role="presentation" <?php echo $iType == 2 ? 'class="active"' : '' ?>><a href="<?php echo $iType == 2 ? 'javascript:;' : $sAcceptCaseUrl ?>">未打印批次案件</a></li>
    <li role="presentation" <?php echo $iType == 3 ? 'class="active"' : '' ?>><a href="<?php echo $iType == 3 ? 'javascript:;' : $sAcceptErrorUrl ?>">转问题岗案件</a></li>
    <li role="presentation" <?php echo $iType == 4 ? 'class="active"' : '' ?>><a href="<?php echo $iType == 4 ? 'javascript:;' : $sAcceptBackUrl ?>">扫描岗退回案件</a></li>
</ul>