<style>
    .search-form .form-group {
        margin-bottom: 15px;
    }
</style>
<div class="pheader clearfix">选择体检员工</div>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="">
        <div>体检产品：安心入职套餐（通用产品）</div>
        <input id='iHRProductID' type='hidden' value='<?php echo $iHRProductID;?>'></input>
        <div class="row">
            <div class="form-group col-sm-3">
                <label>员工姓名：</label>
                <input type="text" value="<?php echo !empty($aParam['sRealName']) ? $aParam['sRealName'] : '' ?>" class="form-control" name="sRealName" style="width: 100px">
            </div>
             <div class="form-group col-sm-3">
                <label>所属机构：</label>
                <select name="iDeptID" class="form-control" style="width: 100px">
                    <option value="0" <?php echo empty($aParam['iDeptID'])  ? 'selected' : '' ?>>全部</option>
                    <?php foreach ($aDeptSet as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aParam['iDeptID']) && $aParam['iDeptID'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-sm-3">
                <label>员工职级：</label>
                <select name="iJobGradeID" class="form-control" style="width: 100px">
                    <option value="0" <?php echo empty($aParam['iJobGradeID'])  ? 'selected' : '' ?>>全部</option>
                    <?php foreach ($aLevel as $k => $v) { ?>
                        <option
                            value="<?php echo $k ?>" <?php echo isset($aParam['iJobGradeID']) && $aParam['iJobGradeID'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>          
                <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
            </div>
            <div class="form-group col-sm-12">
                <input type="checkbox" id='iIsAll' name='iIsAll' value="<?php echo $iIsAll ? 1: 0;?>" <?php echo $iIsAll ? 'checked': '';?>/>
                显示全部员工【默认情况下仅显示最近三个月未参加过该体检的员工信息】
            </div>
        </div>
    </form>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center"><input id="news_all_check" name="news_all_check" value="" type='checkbox'></th>
            <th class="text-center">员工编号</th>
            <th class="text-center">员工姓名</th>
            <th class="text-center">机构名称</th>
            <th class="text-center">邮箱</th>
            <th class="text-center">联系电话</th>
            <th class="text-center">职级</th>
        </tr>
        </thead>
        <tbody>
        <?php if ($aEmpolyee) {
            foreach ($aEmpolyee as $key => $aUser) { ?>
                <tr>
                    <td class="text-center"><input type='checkbox' name='news_check_id' 
                    id="news_check_id_<?php echo $aUser['iUserID'];?>" value="<?php echo $aUser['iUserID'];?>"></td>
                    <td class="text-center"><?php echo $aUser['sUserName'] ?></td>
                    <td class="text-center"><?php echo $aUser['sRealName'] ?></td>
                    <td class="text-center"><?php echo $aDeptSet[$aUser['iDeptID']] ?></td>
                    <td class="text-center"><?php echo $aUser['sEmail'] ?></td>
                    <td class="text-center"><?php echo $aUser['sMobile'] ?></td>
                    <td class="text-center"><?php echo $aLevel[$aUser['iJobGradeID']] ?></td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>

    <div class="btn-toolbar text-center col-sm-12">
        <a class="text-center btn btn-primary" id="batch_transfer">下一步</a>
    </div>
</div>

<input id='ids' value='' type='hidden'/>
<script>
    $('#iIsAll').click(function() {
        var is_checked = $(this).prop('checked');
        if (!is_checked) {
            $(this).val(0);    
        } else {
            $(this).val(1);
        }
       $("#myform").submit();
    });

    $('#news_all_check').click(function() {
        var is_checked = $(this).prop('checked');
        $("input[name='news_check_id']").each(function() {
            $(this).prop('checked', is_checked);
        });
    });

    $('#batch_transfer').bind('click', {
        msg : '没有选中的员工'        
    }, piliang);

    function piliang(event) {
        var msg = event.data.msg;
        var url = event.data.url;
        var ids = '';

        $("input[name='news_check_id']").each(function() {
            if ($(this).prop('checked')) {
                ids += $(this).val() + ',';
            }
        });
        if (ids == '') {
            alert(msg);
            return false;
        }

        ids = ids.substring(0, ids.length-1);
        $('#ids').val(ids);
        if ($('#ids').val() != '') {
            window.location.href='/company/physical/addnext?iHRProductID='+$('#iHRProductID').val()+'&&ids='+$('#ids').val();
        }     
    }

</script>