<style>
    .search-form .form-group {
        margin-bottom: 15px;
    }
</style>
<div class="pheader clearfix">每月体检订购信息</div>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="">
        <div class="col-sm-12 form-group">
            <div class="col-sm-9">
                <label>开始日期：</label>
                <input type="text" value="<?php echo !empty($aParam['sStartDate']) ? $aParam['sStartDate'] : '' ?>"
                       class="laydatetime form-control" id="sStartDate" name="sStartDate" style="width: 100px">
           
                <label>截止日期：</label>
                <input type="text" value="<?php echo !empty($aParam['sEndDate']) ? $aParam['sEndDate'] : '' ?>"
                       class="laydatetime form-control" id="sEndDate" name="sEndDate" style="width: 100px">

                <label>状态：</label>
                <select id='iStatus' name="iStatus" class="form-control" style="width: 100px">
                    <option value="-1" <?php echo empty($aParam['iStatus'])  ? 'selected' : '' ?>>全部</option>
                    <?php foreach ($aStatus as $k => $v) { ?>
                        <option value="<?php echo $k ?>" <?php echo isset($aParam['iStatus']) && $aParam['iStatus'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="col-sm-3">
                <input type="button" id="formbtn" class="btn btn-primary" value="查询">
                <input type="button" id="export" class="btn btn-primary" value="导出">
            </div>
        </div>
    </form>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>            
            <th class="text-center">订购人</th>
            <th class="text-center">体检产品</th>
            <th class="text-center">安排时间</th>
            <th class="text-center">体检日期</th>
            <th class="text-center">体检状态</th>
        </tr>
        </thead>
        <tbody>
        <?php if ($aProduct['iTotal'] > 0) {
            foreach ($aProduct['aList'] as $key => $aUser) { ?>
                <tr>                   
                    <td class="text-center"><?php echo $aUser['sRealName'] ?></td>
                    <td class="text-center"><?php echo $aUser['sProductName'] ?></td>
                    <td class="text-center"><?php echo $aUser['sReserveTime'] ?></td>
                    <td class="text-center"><?php echo $aUser['sPhysicalTime'] ?></td>
                    <td class="text-center"><?php echo $aUser['sBookStatus'] ?></td>                    
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
    <?php echo !empty($aProduct['aPager']) ? $aProduct['aPager'] : '' ?>
</div>

<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/laydate/laydate.js"></script>
<script>
    $('#formbtn').click(function() {
        document.getElementById('myform').action = '/company/physical/monthly/'
        $('#myform').submit();
    });

    $('#export').click(function () {
        document.getElementById('myform').action = '/company/physical/monthly/isexport/1'
        $('#myform').submit();
    });
</script>