<style>
    .search-form .form-group {
        margin-bottom: 15px;
    }
</style>
<div class="pheader clearfix">员工体检记录</div>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="">
        <div class="col-sm-12 form-group">
            <div class="col-sm-9">
                <label>开始日期：</label>
                <input type="text" value="<?php echo !empty($aParam['sStartDate']) ? $aParam['sStartDate'] : '' ?>"
                       class="laydatetime form-control" name="sStartDate" style="width: 100px">
           
                <label>截止日期：</label>
                <input type="text" value="<?php echo !empty($aParam['sEndDate']) ? $aParam['sEndDate'] : '' ?>"
                       class="laydatetime form-control" name="sEndDate" style="width: 100px">

                <label>员工姓名：</label>
                <input type="text" value="<?php echo !empty($aParam['sRealName']) ? $aParam['sRealName'] : '' ?>"
                       class="form-control" name="sRealName" style="width: 100px">

                <label>状态：</label>
                <select name="iStatus" class="form-control" style="width: 100px">
                    <option value="-1" <?php echo empty($aParam['iStatus'])  ? 'selected' : '' ?>>全部</option>
                    <?php foreach ($aStatus as $k => $v) { ?>
                        <option value="<?php echo $k ?>" <?php echo isset($aParam['iStatus']) && $aParam['iStatus'] == $k ? 'selected' : '' ?>><?php echo $v ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="col-sm-3">
                <input type="submit" id="formbtn" class="btn btn-primary" value="查询">
                <input type="button" class="btn btn-primary" id="item-add-select"  value="发送体检通知">
            </div>
        </div>
    </form>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="text-center"><input id="news_all_check" name="news_all_check" value="" type='checkbox'></th>
            <th class="text-center">员工姓名</th>
            <th class="text-center">开始时间</th>
            <th class="text-center">截止时间</th>
            <th class="text-center">手机号码</th>
            <th class="text-center">体检类型</th>
            <th class="text-center">预约状态</th>
            <th class="text-center">操作时间</th>
            <th class="text-center">是否发送通知</th>
            <th class="text-center">查看</th>
        </tr>
        </thead>
        <tbody>
        <?php if ($aProduct['iTotal'] > 0) {
            foreach ($aProduct['aList'] as $key => $aUser) { ?>
                <tr>
                    <td class="text-center"><input class='itemlist' type='checkbox' name='news_check_id' 
                    id="news_check_id_<?php echo $aUser['iAutoID'];?>" value="<?php echo $aUser['iAutoID'];?>"></td>
                    <td class="text-center"><?php echo $aUser['sRealName'] ?></td>
                    <td class="text-center"><?php echo $aUser['sStartDate'] ?></td>
                    <td class="text-center"><?php echo $aUser['sEndDate'] ?></td>
                    <td class="text-center"><?php echo $aUser['sMobile'] ?></td>
                    <td class="text-center"><?php echo $aUser['sPhysicalType'] ?></td>
                    <td class="text-center"><?php echo $aUser['sBookStatus'] ?></td>
                    <td class="text-center"><?php echo $aUser['sOperateTime'] ?></td>
                    <td class="text-center"><?php echo $aUser['sNotice'] ?></td>
                    <td class="text-center">
                        <a href="/company/physical/detail/id/<?php echo $aUser['iAutoID'] ?>" title="查看详情">查看</a>                      
                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>
    </table>
    <?php echo !empty($aProduct['aPager']) ? $aProduct['aPager'] : '' ?>
</div>

<input id='ids' value='' type='hidden'/>
<div class='modal fade' id='tModal'>
    <div class='modal-dialog'>
        <div class='modal-content'>
            <div class='modal-body'>
                <form class='form-horizontal'>
                    <div class="form-group col-sm-4">
                        <label>将选中人员转移至：</label>
                        <select id='deptID' name="deptID" class="" style="width: 100px">
                            <?php foreach ($aDeptSet as $k => $v) { ?>
                                <option value="<?php echo $k ?>" ><?php echo $v ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </form>
                <button type='button' class='btn btn-primary' id='tSave'>确定</button>
        </div>
    </div>
</div>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/laydate/laydate.js"></script>
<script>
    //发送账号
    $('#item-add-select').click(function(){
        var select_item = '';
        var count_num = 0;
        var url = '<?php echo !empty($sInsertItemUrl) ? $sInsertItemUrl : '' ?>?pid=<?php echo !empty($iPlanID) ? $iPlanID : 0 ?>&id=';
        $('.itemlist').each(function(index,dom){
            if ($(dom).prop('checked')) {
                select_item +=$(dom).val()+',';
                count_num++;
            }
        });
        if (!count_num) {
            alert('请选择员工');
            return false;
        }
        select_item=select_item.substring(0,select_item.length-1);

        window.location.href = '/company/physical/send/ids/'+select_item;
    });

    $('#news_all_check').click(function() {
        var is_checked = $(this).prop('checked');
        $("input[name='news_check_id']").each(function() {
            $(this).prop('checked', is_checked);
        });
    });

</script>