<div class="pheader clearfix"><?php echo $sTypeName?>列表</div>
<div class="pbody clearfix">
	<form class="form-inline search-form" role="form" method="post" id="myform" action="/admin/field/list.html">
        <div class="row sousuo_now">
            <div class="form-group">
                <label><?php echo $sTypeName?>：</label>
                <input type="text" value="<?php echo isset($aParam['sName']) ? $aParam['sName'] : '' ?>" class="form-control" name="sName" style="width: 100px">
            </div>
            <div class="form-group">
                <input type="submit" id="formbtn" class="btn btn-default btn-sm" value="搜索">
            </div>
        </div>
    </form>
    <hr />
    <div class="btn-toolbar list-toolbar">
    	<button class="btn btn-primary" id="field_add">
    		<i class="fa fa-plus"></i> 增加<?php echo $sTypeName?>
    	</button>
    </div>
    <table class="table table-bordered table-hover">
    	<thead>
    		<tr>
    			<th class="col-sm-1 text-center">#</th>
    			<th class="text-center"><?php echo $sTypeName?></th>
    			<th class="text-center">备注</th>
    			<th class="text-center">排序</th>
    			<th class="text-center">更新时间</th>
    			<th class="text-center">操作</th>
    		</tr>
    	</thead>
    	<tbody>
        <?php foreach ($aList['aList'] as $v) {?>
            <tr>
    			<td class="col-sm-1 text-center"><?php echo $v['iAutoID']?></td>
    			<td class="text-center"><?php echo $v['sName'];?></td>
    			<td class="text-center"><?php echo $v['sRemark']?></td>
    			<td class="text-center"><?php echo $v['iOrder']?></td>
    			<td class="text-center"><?php echo date('Y-m-d H:i:s' , $v['iCreateTime'])?></td>
    			<td class="text-center">
    			    <a href="/admin/field/edit?id=<?php echo $v['iAutoID']?>" title="编辑"><i class="fa fa-pencil fa-large"></i></a>
    			    <a class="field_delete" href="/admin/field/del?id=<?php echo $v['iAutoID']?>" role="button" data-toggle="modal" title="删除"><i class="fa fa-trash fa-large"></i></a>
    			</td>
    		</tr>
        <?php }?>
    	</tbody>
    </table>
    <?php echo $aList['aPager']?>
</div><script type="text/javascript" src="<?php echo $sStaticRoot ?>/js/xcConfirm.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/js/xcConfirm.css"/>
<style type="text/css">
.sgBtn{width: 135px; height: 35px; line-height: 35px; margin-left: 10px; margin-top: 10px; text-align: center; background-color: #0095D9; color: #FFFFFF; float: left; border-radius: 5px;}
</style>
<script>
$('.field_delete').click(function() {
	var url = this.href;
	if (confirm("您确认要删除该基础配置吗？")) {
		$.get(url, function(ret){
			alert(ret.data);
			if (ret.status) {
				location.reload();
			}
		}, 'json');
	}
	return false;
});
$('#field_add').click(function(){
	location.href = '/admin/field/add/type/<?php echo $sType?>.html';
});
</script>